using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S1.Words.AssociatedMersenne;

internal sealed class CircularWordsDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S1/Words/AssociatedMersenne/CircularWords.";
    private static readonly LibraryNoteRef Source = LibraryNoteRef.Create("D5/L/Words/wei2024associatedmersenne");
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create("Degree enumeration for labelled circular run-constrained words.", H("CircularWords"), Blocks(
        Node("split_reverse_map", "Split under reversal and transport", Disp(All(Name("alpha"), Name("Type"), All(Name("beta"), Name("Type"), All(Name("r"), Seq(Name("alpha"), Sp, To, Sp, Name("alpha"), Sp, To, Sp, Name("Bool")), All(Name("s"), Seq(Name("beta"), Sp, To, Sp, Name("beta"), Sp, To, Sp, Name("Bool")), All(Name("f"), Seq(Name("alpha"), Sp, To, Sp, Name("beta")), All(Name("l"), Seq(Name("List"), Sp, Name("alpha")), Seq(Parenthesized(Seq(Forall, Sp, Name("a"), Sp, InMacro, Sp, Name("l"), Sp, Comma, Sp, Forall, Sp, Name("b"), Sp, InMacro, Sp, Name("l"), Sp, Comma, Sp, Name("s"), Sp, Parenthesized(Seq(Name("f"), Sp, Name("b"))), Sp, Parenthesized(Seq(Name("f"), Sp, Name("a"))), Sp, Eq, Sp, Name("r"), Sp, Name("a"), Sp, Name("b"))), Sp, To, Sp, Parenthesized(Seq(Seq(Parenthesized(Seq(Name("l.reverse.map"), Sp, Name("f"))), Sp, Dot, Sp, Name("splitBy"), Sp, Name("s")), Sp, Eq, Sp, Seq(Parenthesized(Seq(Name("l.splitBy"), Sp, Name("r"))), Sp, Dot, Sp, Name("reverse.map"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("b"), Sp, Mapsto, Sp, Name("b.reverse.map"), Sp, Name("f")))))))))))))), "Reversing each block and the block order preserves internal links and separating boundaries under the transported relation.", DescribeRole.Lemma),
        Node("cycAdd", "cycAdd", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("j"), Name("Nat"), Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("j"), Sp, Eq, Sp, Parenthesized(Seq(Name("Fin.ofNat"), Sp, Name("n"), Sp, Parenthesized(Seq(Name("i.val"), Sp, Plus, Sp, Name("j")))))))))), "Adding a natural offset and reducing modulo the length gives the labelled circular position.", DescribeRole.Definition),
        Node("cycSub", "cycSub", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("j"), Name("Nat"), Seq(Name("cycSub"), Sp, Name("i"), Sp, Name("j"), Sp, Eq, Sp, Parenthesized(Seq(Name("Fin.ofNat"), Sp, Name("n"), Sp, Parenthesized(Seq(Name("i.val"), Sp, Plus, Sp, Name("n"), Sp, Minus, Sp, Name("j")))))))))), "The predecessor offset uses natural subtraction before reduction modulo the length.", DescribeRole.Definition),
        Node("IsOneRunStart", "IsOneRunStart", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("r"), Name("Nat"), Seq(Name("IsOneRunStart"), Sp, Name("w"), Sp, Name("i"), Sp, Name("r"), Sp, Iff, Sp, Parenthesized(Seq(Name("w"), Sp, Parenthesized(Seq(Name("cycSub"), Sp, Name("i"), Sp, D(1))), Sp, Eq, Sp, Name("false"), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, Name("j"), Sp, Lt, Sp, Name("r"), Sp, Comma, Sp, Name("w"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("j"))), Sp, Eq, Sp, Name("true"))), Sp, Land, Sp, Name("w"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("r"))), Sp, Eq, Sp, Name("false"))))))))), "The preceding and following letters are zero and all r intermediate letters are one. This predicate permits r=0. Genuine marks use IsMarkedStart, which requires positive r.", DescribeRole.Definition),
        Node("Admissible", "Admissible", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), Seq(Name("Admissible"), Sp, Name("w"), Sp, Iff, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("n"), Sp, Eq, Sp, D(0), Sp, Lor, Sp, Exists, Sp, Name("i"), Sp, Comma, Sp, Name("w"), Sp, Name("i"), Sp, Eq, Sp, Name("false"))), Sp, Land, Sp, Forall, Sp, Name("i"), Sp, Name("r"), Sp, Comma, Sp, Name("IsOneRunStart"), Sp, Name("w"), Sp, Name("i"), Sp, Name("r"), Sp, To, Sp, Forall, Sp, Name("j"), Sp, Le, Sp, Name("r"), Sp, Comma, Sp, Name("w"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("r"))), Sp, Name("j"))), Sp, Eq, Sp, Name("false"))))))), "Wei and Yang, arXiv v1, pp. 3–4: “A string of 𝐁ₙ is called run-constrained-circularly if every run of 1s appearing in this string is immediately followed by a strictly longer run of 0s in a circular manner.” Positions are labelled Fin n and letters are Bool. The all-ones word is excluded for positive n; n=0 denotes the empty word.", DescribeRole.Definition, true),
        Node("flip", "flip", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("flip"), Sp, Name("w"), Sp, Name("i"), Sp, Eq, Sp, Parenthesized(Seq(Name("Function.update"), Sp, Name("w"), Sp, Name("i"), Sp, Parenthesized(Seq(Bang, Sp, Name("w"), Sp, Name("i")))))))))), "Updating one Boolean letter to its negation gives the one-bit neighbour.", DescribeRole.Definition),
        Node("degree", "degree", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), Seq(Name("degree"), Sp, Name("w"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("Finset.univ.filter"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("i"), Sp, Colon, Sp, Name("Fin"), Sp, Name("n"), Sp, Mapsto, Sp, Name("Admissible"), Sp, Parenthesized(Seq(Name("CircularWords.flip"), Sp, Name("w"), Sp, Name("i"))))))), Sp, Dot, Sp, Name("card"))))))), "Filtering all positions by admissibility of their one-bit neighbours counts the degree.", DescribeRole.Definition),
        Node("N", "N", Disp(All(Name("n"), Name("Nat"), All(Name("k"), Name("Nat"), Seq(Name("N"), Sp, Name("n"), Sp, Name("k"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("Finset.univ.filter"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("w"), Sp, Colon, Sp, Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool"), Sp, Mapsto, Sp, Name("Admissible"), Sp, Name("w"), Sp, Land, Sp, Name("degree"), Sp, Name("w"), Sp, Eq, Sp, Name("k"))))), Sp, Dot, Sp, Name("card"))))))), "Filtering labelled words by admissibility and degree gives the degree histogram.", DescribeRole.Definition),
        Node("cycAdd_sub_one", "cycAdd sub one", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("cycAdd"), Sp, Name("i"), Sp, Parenthesized(Seq(Name("n"), Sp, Minus, Sp, D(1))), Sp, Eq, Sp, Name("cycSub"), Sp, Name("i"), Sp, D(1))))), "Positivity of the length identifies the offset n minus one with the predecessor.", DescribeRole.Lemma),
        Node("start_large_false", "start large false", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("r"), Name("Nat"), Seq(Parenthesized(Seq(Name("n"), Sp, Le, Sp, Name("r"))), Sp, To, Sp, Parenthesized(Seq(Neg, Sp, Name("IsOneRunStart"), Sp, Name("w"), Sp, Name("i"), Sp, Name("r"))))))))), "A run of at least the full length would make its zero predecessor a one.", DescribeRole.Lemma),
        Node("cycAdd_zero", "cycAdd zero", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("cycAdd"), Sp, Name("i"), Sp, D(0), Sp, Eq, Sp, Name("i"))))), "Reduction modulo the length leaves the original position unchanged at offset zero.", DescribeRole.Lemma),
        Node("cycAdd_val", "cycAdd val", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("j"), Name("Nat"), Seq(Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("j"))), Sp, Dot, Sp, Name("val"), Sp, Eq, Sp, Parenthesized(Seq(Name("i.val"), Sp, Plus, Sp, Name("j"))), Sp, Name("Nat.mod"), Sp, Name("n")))))), "The value of circular addition is the remainder of the sum of the labelled index and offset.", DescribeRole.Lemma),
        Node("cycAdd_assoc", "cycAdd assoc", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("j"), Name("Nat"), All(Name("k"), Name("Nat"), Seq(Name("cycAdd"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("j"))), Sp, Name("k"), Sp, Eq, Sp, Name("cycAdd"), Sp, Name("i"), Sp, Parenthesized(Seq(Name("j"), Sp, Plus, Sp, Name("k"))))))))), "Remainder arithmetic identifies successive offsets with their sum.", DescribeRole.Lemma),
        Node("cycAdd_inj", "cycAdd inj", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("j"), Name("Nat"), All(Name("k"), Name("Nat"), Seq(Parenthesized(Seq(Name("j"), Sp, Lt, Sp, Name("n"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("k"), Sp, Lt, Sp, Name("n"))), Sp, To, Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("j"), Sp, Eq, Sp, Name("cycAdd"), Sp, Name("i"), Sp, Name("k"), Sp, Iff, Sp, Name("j"), Sp, Eq, Sp, Name("k"))))))))))), "Offsets below the length are uniquely determined by their circular positions.", DescribeRole.Lemma),
        Node("zero_admissible", "zero admissible", Disp(All(Name("n"), Name("Nat"), Seq(Name("Admissible"), Sp, Parenthesized(Seq(Name("Function.const"), Sp, Parenthesized(Seq(Name("Fin"), Sp, Name("n"))), Sp, Name("false")))))), "The zero word has no positive run and satisfies every required zero-gap condition.", DescribeRole.Lemma),
        Node("zero_degree", "zero degree", Disp(All(Name("n"), Name("Nat"), Seq(Name("degree"), Sp, Parenthesized(Seq(Name("Function.const"), Sp, Parenthesized(Seq(Name("Fin"), Sp, Name("n"))), Sp, Name("false"))), Sp, Eq, Sp, Name("if"), Sp, Name("n"), Sp, Le, Sp, D(2), Sp, Name("then"), Sp, D(0), Sp, Name("else"), Sp, Name("n")))), "A singleton one is admissible precisely when the length exceeds two, determining every flip of the zero word.", DescribeRole.Lemma),
        Node("offset", "offset", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("q"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("offset"), Sp, Name("i"), Sp, Name("q"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("q.val"), Sp, Plus, Sp, Name("n"), Sp, Minus, Sp, Name("i.val"))), Sp, Name("Nat.mod"), Sp, Name("n")))))))), "The remainder of the target index minus the starting index gives a bounded forward offset.", DescribeRole.Definition),
        Node("cycAdd_offset", "cycAdd offset", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("q"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("cycAdd"), Sp, Name("i"), Sp, Parenthesized(Seq(Name("offset"), Sp, Name("i"), Sp, Name("q"))), Sp, Eq, Sp, Name("q")))))), "Adding the remainder offset recovers the target labelled position.", DescribeRole.Lemma),
        Node("offset_lt", "offset lt", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("q"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("offset"), Sp, Name("i"), Sp, Name("q"), Sp, Lt, Sp, Name("n")))))), "The remainder defining an offset is strictly below the positive word length.", DescribeRole.Lemma),
        Node("cycAdd_bijective", "cycAdd bijective", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("Function.Bijective"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("j"), Sp, Colon, Sp, Name("Fin"), Sp, Name("n"), Sp, Mapsto, Sp, Name("cycAdd"), Sp, Name("i"), Sp, Name("j.val"))))))), "The bounded offset gives an inverse to circular addition on all labelled positions.", DescribeRole.Lemma),
        Node("linearize", "linearize", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("linearize"), Sp, Name("w"), Sp, Name("i"), Sp, Eq, Sp, Parenthesized(Seq(Name("List.ofFn"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("j"), Sp, Colon, Sp, Name("Fin"), Sp, Name("n"), Sp, Mapsto, Sp, Name("w"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("j.val")))))))))))), "Reading one complete circle from the marked position gives a linear Boolean list.", DescribeRole.Definition),
        Node("linearize_injective", "linearize injective", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("Function.Injective"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("w"), Sp, Colon, Sp, Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool"), Sp, Mapsto, Sp, Name("linearize"), Sp, Name("w"), Sp, Name("i"))))))), "Every labelled position occurs in the linear reading, so equal readings determine equal words.", DescribeRole.Lemma),
        Node("linearize_length", "linearize length", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Parenthesized(Seq(Name("linearize"), Sp, Name("w"), Sp, Name("i"))), Sp, Dot, Sp, Name("length"), Sp, Eq, Sp, Name("n")))))), "The finite list of labelled positions has exactly the word length.", DescribeRole.Lemma),
        Node("one_run_length_unique", "one run length unique", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("r"), Name("Nat"), All(Name("s"), Name("Nat"), Seq(Parenthesized(Seq(Name("IsOneRunStart"), Sp, Name("w"), Sp, Name("i"), Sp, Name("r"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("IsOneRunStart"), Sp, Name("w"), Sp, Name("i"), Sp, Name("s"))), Sp, To, Sp, Parenthesized(Seq(Name("r"), Sp, Eq, Sp, Name("s")))))))))))), "The zero ending a run contradicts any longer run from the same start.", DescribeRole.Lemma),
        Node("IsMarkedStart", "IsMarkedStart", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("IsMarkedStart"), Sp, Name("w"), Sp, Name("i"), Sp, Iff, Sp, Parenthesized(Seq(Exists, Sp, Name("r"), Sp, Comma, Sp, D(0), Sp, Lt, Sp, Name("r"), Sp, Land, Sp, Name("IsOneRunStart"), Sp, Name("w"), Sp, Name("i"), Sp, Name("r")))))))), "A mark records a one-run start with strictly positive run length.", DescribeRole.Definition),
        Node("marked_start_true", "marked start true", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Parenthesized(Seq(Name("IsMarkedStart"), Sp, Name("w"), Sp, Name("i"))), Sp, To, Sp, Parenthesized(Seq(Name("w"), Sp, Name("i"), Sp, Eq, Sp, Name("true")))))))), "The zero offset in a positive run forces the marked letter to be one.", DescribeRole.Lemma),
        Node("marked_start_predecessor", "marked start predecessor", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Parenthesized(Seq(Name("IsMarkedStart"), Sp, Name("w"), Sp, Name("i"))), Sp, To, Sp, Parenthesized(Seq(Name("w"), Sp, Parenthesized(Seq(Name("cycSub"), Sp, Name("i"), Sp, D(1))), Sp, Eq, Sp, Name("false")))))))), "The defining predecessor condition forces the letter before a mark to be zero.", DescribeRole.Lemma),
        Node("marked_start_iff", "marked start iff", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("IsMarkedStart"), Sp, Name("w"), Sp, Name("i"), Sp, Iff, Sp, Name("w"), Sp, Parenthesized(Seq(Name("cycSub"), Sp, Name("i"), Sp, D(1))), Sp, Eq, Sp, Name("false"), Sp, Land, Sp, Name("w"), Sp, Name("i"), Sp, Eq, Sp, Name("true")))))), "A one after a zero extends to its first following zero, giving a positive marked run.", DescribeRole.Lemma),
        Node("cycAdd_predecessor_pos", "cycAdd predecessor pos", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("j"), Name("Nat"), Seq(Parenthesized(Seq(D(0), Sp, Lt, Sp, Name("j"))), Sp, To, Sp, Parenthesized(Seq(Name("cycSub"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("j"))), Sp, D(1), Sp, Eq, Sp, Name("cycAdd"), Sp, Name("i"), Sp, Parenthesized(Seq(Name("j"), Sp, Minus, Sp, D(1)))))))))), "Moving back one position from a positive offset agrees with adding the offset minus one.", DescribeRole.Lemma),
        Node("nonzero_has_marked_start", "nonzero has marked start", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), Seq(Parenthesized(Seq(Exists, Sp, Name("p"), Sp, Comma, Sp, Name("w"), Sp, Name("p"), Sp, Eq, Sp, Name("false"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Exists, Sp, Name("q"), Sp, Comma, Sp, Name("w"), Sp, Name("q"), Sp, Eq, Sp, Name("true"))), Sp, To, Sp, Parenthesized(Seq(Exists, Sp, Name("i"), Sp, Comma, Sp, Name("IsMarkedStart"), Sp, Name("w"), Sp, Name("i"))))))))), "A least one encountered after a zero supplies a zero-to-one transition and hence a mark.", DescribeRole.Lemma),
        Node("admissible_nonzero_has_marked_start", "admissible nonzero has marked start", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), Seq(Parenthesized(Seq(Name("Admissible"), Sp, Name("w"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Exists, Sp, Name("q"), Sp, Comma, Sp, Name("w"), Sp, Name("q"), Sp, Eq, Sp, Name("true"))), Sp, To, Sp, Parenthesized(Seq(Exists, Sp, Name("i"), Sp, Comma, Sp, Name("IsMarkedStart"), Sp, Name("w"), Sp, Name("i"))))))))), "Admissibility supplies a zero, while a nonzero word supplies the one needed for a marked transition.", DescribeRole.Lemma),
        Node("runCount", "runCount", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), Seq(Name("runCount"), Sp, Name("w"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("Finset.univ.filter"), Sp, Parenthesized(Seq(Name("IsMarkedStart"), Sp, Name("w"))))), Sp, Dot, Sp, Name("card"))))))), "Counting positive marked starts counts the circular runs of ones.", DescribeRole.Definition),
        Node("DegreeRunWords", "DegreeRunWords", Disp(All(Name("n"), Name("Nat"), All(Name("ell"), Name("Nat"), All(Name("k"), Name("Nat"), Seq(Name("DegreeRunWords"), Sp, Name("n"), Sp, Name("ell"), Sp, Name("k"), Sp, Eq, Sp, Parenthesized(Seq(OpenBrace, Sp, Seq(Name("w"), Sp, Colon, Sp, Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool"), Sp, Seq(Slash,Slash), Sp, Name("Admissible"), Sp, Name("w"), Sp, Land, Sp, Name("degree"), Sp, Name("w"), Sp, Eq, Sp, Name("k"), Sp, Land, Sp, Name("runCount"), Sp, Name("w"), Sp, Eq, Sp, Name("ell")), Sp, CloseBrace))))))), "The subtype fixes admissibility, run count and degree for labelled words of a given length.", DescribeRole.Definition),
        Node("MarkedDegreeRunWords", "MarkedDegreeRunWords", Disp(All(Name("n"), Name("Nat"), All(Name("ell"), Name("Nat"), All(Name("k"), Name("Nat"), Seq(Name("MarkedDegreeRunWords"), Sp, Name("n"), Sp, Name("ell"), Sp, Name("k"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("w"), Sp, Colon, Sp, Name("DegreeRunWords"), Sp, Name("n"), Sp, Name("ell"), Sp, Name("k"))), Sp, Times, Sp, Seq(OpenBrace, Sp, Seq(Name("i"), Sp, Colon, Sp, Name("Fin"), Sp, Name("n"), Sp, Seq(Slash,Slash), Sp, Name("IsMarkedStart"), Sp, Name("w.val"), Sp, Name("i")), Sp, CloseBrace)))))))), "The subtype pairs a degree-and-run-count word with one of its positive marked starts.", DescribeRole.Definition),
        Node("instFintypeDegreeRunWords", "instFintypeDegreeRunWords", Disp(All(Name("n"), Name("Nat"), All(Name("ell"), Name("Nat"), All(Name("k"), Name("Nat"), Seq(Name("instFintypeDegreeRunWords"), Sp, Name("n"), Sp, Name("ell"), Sp, Name("k"), Sp, Colon, Sp, Name("Fintype"), Sp, Parenthesized(Seq(Name("DegreeRunWords"), Sp, Name("n"), Sp, Name("ell"), Sp, Name("k")))))))), "This instance is inferInstanceAs for the subtype of Fin n → Bool satisfying Admissible, degree = k and runCount = ell.", DescribeRole.Definition),
        Node("instFintypeMarkedDegreeRunWords", "instFintypeMarkedDegreeRunWords", Disp(All(Name("n"), Name("Nat"), All(Name("ell"), Name("Nat"), All(Name("k"), Name("Nat"), Seq(Name("instFintypeMarkedDegreeRunWords"), Sp, Name("n"), Sp, Name("ell"), Sp, Name("k"), Sp, Colon, Sp, Name("Fintype"), Sp, Parenthesized(Seq(Name("MarkedDegreeRunWords"), Sp, Name("n"), Sp, Name("ell"), Sp, Name("k")))))))), "This instance is inferInstanceAs for the dependent pair of a DegreeRunWords n ell k word and a Fin n position satisfying IsMarkedStart.", DescribeRole.Definition),
        Node("marked_double_count_of_equiv", "marked double count of equiv", Disp(All(Name("n"), Name("Nat"), All(Name("ell"), Name("Nat"), All(Name("k"), Name("Nat"), All(Name("T"), Name("Type"), Seq(OpenBracket, Seq(Name("Fintype"), Sp, Name("T")), CloseBracket, Comma, Sp, Seq(Parenthesized(Seq(Name("MarkedDegreeRunWords"), Sp, Name("n"), Sp, Name("ell"), Sp, Name("k"), Sp, Equiv, Sp, Name("Fin"), Sp, Name("n"), Sp, Times, Sp, Name("T"))), Sp, To, Sp, Parenthesized(Seq(Name("ell"), Sp, Cdot, Sp, Name("Fintype.card"), Sp, Parenthesized(Seq(Name("DegreeRunWords"), Sp, Name("n"), Sp, Name("ell"), Sp, Name("k"))), Sp, Eq, Sp, Name("n"), Sp, Cdot, Sp, Name("Fintype.card"), Sp, Name("T")))))))))), "T is a finite type in an arbitrary universe. An equivalence between labelled marked words and Fin n × T gives the displayed double count without dividing by the number of runs.", DescribeRole.Theorem),
        Node("rotateWord", "rotateWord", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("rotateWord"), Sp, Name("w"), Sp, Name("i"), Sp, Eq, Sp, Parenthesized(Seq(Name("fun"), Sp, Name("j"), Sp, Mapsto, Sp, Name("w"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("j.val")))))))))), "Changing the starting labelled position reads the same circular word by circular addition.", DescribeRole.Definition),
        Node("rotateWord_admissible_iff", "rotateWord admissible iff", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("Admissible"), Sp, Parenthesized(Seq(Name("rotateWord"), Sp, Name("w"), Sp, Name("i"))), Sp, Iff, Sp, Name("Admissible"), Sp, Name("w")))))), "Circular addition transports each run start and its following zero gap in both directions.", DescribeRole.Theorem),
        Node("rotateWord_degree", "rotateWord degree", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("degree"), Sp, Parenthesized(Seq(Name("rotateWord"), Sp, Name("w"), Sp, Name("i"))), Sp, Eq, Sp, Name("degree"), Sp, Name("w")))))), "The bijection on positions transports legal one-bit flips and preserves their count.", DescribeRole.Lemma),
        Node("next_one_gap_bound", "next one gap bound", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("a"), Seq(Name("Fin"), Sp, Name("n")), All(Name("r"), Name("Nat"), All(Name("z"), Name("Nat"), Seq(Parenthesized(Seq(Name("Admissible"), Sp, Name("w"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("IsOneRunStart"), Sp, Name("w"), Sp, Name("a"), Sp, Name("r"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("w"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("a"), Sp, Parenthesized(Seq(Name("r"), Sp, Plus, Sp, Name("z"))))), Sp, Eq, Sp, Name("true"))), Sp, To, Sp, Parenthesized(Seq(Name("r"), Sp, Lt, Sp, Name("z")))))))))))))), "A later one cannot occur inside the zero gap forced by admissibility of the preceding run.", DescribeRole.Theorem),
        Node("linearize_move_mark", "linearize move mark", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("p"), Name("Nat"), Seq(Name("linearize"), Sp, Name("w"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("p"))), Sp, Eq, Sp, Parenthesized(Seq(Name("linearize"), Sp, Name("w"), Sp, Name("i"))), Sp, Dot, Sp, Name("rotate"), Sp, Name("p"))))))), "Moving the marked origin rotates the linear list by the corresponding bounded offset.", DescribeRole.Theorem),
        Describe.Lean(DescribeId.Create("amg-circularwords-card-marks"), DeclarationHandle.Create(Prefix + "card_marks"), H("Cardinality of marked starts"), StatementSource.FromAuthor(Disp(All(Name("n"), Seq(Name("Nat")), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), Seq(Name("Fintype.card"), Sp, Seq(OpenBrace, Name("i"), Sp, Colon, Sp, Name("Fin"), Sp, Name("n"), Sp, Bar, Sp, Name("IsMarkedStart"), Sp, Name("w"), Sp, Name("i"), CloseBrace), Sp, Eq, Sp, Name("runCount"), Sp, Name("w")))))), AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text("The finite set of marked starts has cardinality equal to the run count."))), DescribeRole.Lemma)
)));

    private static DocumentBlock Node(string name, string title, Formula formula, string prose, DescribeRole role, bool literature = false) => Describe.Lean(
        DescribeId.Create("amg-circularwords-" + name.Replace('_', '-').Replace('.', '-').ToLowerInvariant()),
        DeclarationHandle.Create(Prefix + name), H(title), StatementSource.FromAuthor(formula),
        literature ? AssessedProvenance.FromLiterature(Source) : AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text(prose))), role);

    private static Formula Parenthesized(Formula value) => Seq(Open, value, Close);
    private static Formula All(Formula variable, Formula type, Formula body) => Seq(Forall, Sp, Parenthesized(Seq(variable, Colon, Sp, type)), Comma, Sp, body);
    private static Formula Name(string name) {
        var parts = name.Split('.');
        Formula value = Word(parts[0]);
        for (var i = 1; i < parts.Length; i++) value = Seq(value, Dot, Word(parts[i]));
        return value;
    }
    private static Formula Word(string word) {
        if (word == "") return Sp;
        if (word == "0") return D(0);
        if (word == "1") return D(1);
        if (word == "2") return D(2);
        if (word.EndsWith("'", StringComparison.Ordinal)) return Seq(Word(word[..^1]), Apos);
        var parts = word.Split('_');
        Formula value = Seq(Operatorname, Grp(F.Id(parts[0])));
        for (var i = 1; i < parts.Length; i++) value = new Formula.Subscript(value, Seq(Operatorname, Grp(F.Id(parts[i]))));
        return value;
    }
}
