using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S1.Words.AssociatedMersenne;

internal sealed class RunTupleBijectionDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S1/Words/AssociatedMersenne/RunTupleBijection.";
    private static readonly LibraryNoteRef Source = LibraryNoteRef.Create("D5/L/Words/wei2024associatedmersenne");
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create("Degree enumeration for labelled circular run-constrained words.", H("RunTupleBijection"), Blocks(
        Node("tupleList", "tupleList", Disp(All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), Seq(Name("tupleList"), Sp, Name("t"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("t.flatMap"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("b"), Sp, Mapsto, Sp, Seq(OpenBracket, Sp, Seq(Name("List.replicate"), Sp, Name("b.1"), Sp, Name("true"), Sp, Comma, Sp, Name("List.replicate"), Sp, Parenthesized(Seq(Name("b.1"), Sp, Plus, Sp, D(1), Sp, Plus, Sp, Name("b.2"))), Sp, Name("false")), Sp, CloseBracket))))), Sp, Dot, Sp, Name("flatten")))))), "Each positive run is followed by its compulsory longer zero block and its additional slack.", DescribeRole.Definition),
        Node("blockLengths", "blockLengths", Disp(All(Name("w"), Seq(Name("List"), Sp, Name("Bool")), Seq(Name("blockLengths"), Sp, Name("w"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("w.splitBy"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("a"), Sp, Name("b"), Sp, Mapsto, Sp, App(Q("BEq", "beq"), Name("a"), Name("b")))))), Sp, Dot, Sp, Name("map"), Sp, Name("List.length")))))), "Splitting at changes of Boolean value records the successive constant-block lengths.", DescribeRole.Definition),
        Node("tupleList_length", "tupleList length", Disp(All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), Seq(Parenthesized(Seq(Name("tupleList"), Sp, Name("t"))), Sp, Dot, Sp, Name("length"), Sp, Eq, Sp, Parenthesized(Seq(Name("t.map"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("b"), Sp, Mapsto, Sp, D(2), Sp, Cdot, Sp, Name("b.1"), Sp, Plus, Sp, D(1), Sp, Plus, Sp, Name("b.2"))))), Sp, Dot, Sp, Name("sum")))), "The run and zero blocks contribute two times the run length plus one plus the slack.", DescribeRole.Lemma),
        Node("decodeLengths", "decodeLengths", Disp(new Formula.Aligned([Seq(Name("decodeLengths"), Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket), Sp, Eq, Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket)), Seq(Forall, Sp, Parenthesized(Seq(Name("r"), Sp, Name("z"), Sp, Colon, Sp, Name("Nat"))), Sp, Parenthesized(Seq(Name("rest"), Sp, Colon, Sp, Name("List"), Sp, Name("Nat"))), Sp, Comma, Sp, Name("decodeLengths"), Sp, Parenthesized(Seq(Name("r"), Sp, Seq(Colon,Colon), Sp, Name("z"), Sp, Seq(Colon,Colon), Sp, Name("rest"))), Sp, Eq, Sp, Parenthesized(Seq(Name("r"), Sp, Comma, Sp, Name("z"), Sp, Minus, Sp, Parenthesized(Seq(Name("r"), Sp, Plus, Sp, D(1))))), Sp, Seq(Colon,Colon), Sp, Name("decodeLengths"), Sp, Name("rest")), Seq(Forall, Sp, Parenthesized(Seq(Name("r"), Sp, Colon, Sp, Name("Nat"))), Sp, Comma, Sp, Name("decodeLengths"), Sp, Seq(OpenBracket, Sp, Name("r"), Sp, CloseBracket), Sp, Eq, Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket))])), "Successive one and zero block lengths determine a run length and its excess zero slack.", DescribeRole.Definition),
        Node("extractListTuple", "extractListTuple", Disp(All(Name("w"), Seq(Name("List"), Sp, Name("Bool")), Seq(Name("extractListTuple"), Sp, Name("w"), Sp, Eq, Sp, Parenthesized(Seq(Name("decodeLengths"), Sp, Parenthesized(Seq(Name("blockLengths"), Sp, Name("w")))))))), "Constant-block splitting followed by length decoding extracts the ordered run-and-slack tuple.", DescribeRole.Definition),
        Node("wordOfTuple", "wordOfTuple", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), All(Name("hlen"), Seq(Parenthesized(Seq(Name("tupleList"), Sp, Name("t"))), Sp, Dot, Sp, Name("length"), Sp, Eq, Sp, Name("n")), All(Name("q"), Seq(Name("Fin"), Sp, Name("n")), Seq(Name("wordOfTuple"), Sp, Name("i"), Sp, Name("t"), Sp, Name("hlen"), Sp, Name("q"), Sp, Eq, Sp, Parenthesized(Seq(Name("tupleList"), Sp, Name("t"))), Sp, Seq(OpenBracket, Sp, Seq(Name("offset"), Sp, Name("i"), Sp, Name("q")), Sp, CloseBracket)))))))), "The defining list access uses the bound obtained from hlen and offset_lt; proof arguments do not change the returned letter.", DescribeRole.Definition),
        Node("linearize_wordOfTuple", "linearize wordOfTuple", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), All(Name("hlen"), Seq(Parenthesized(Seq(Name("tupleList"), Sp, Name("t"))), Sp, Dot, Sp, Name("length"), Sp, Eq, Sp, Name("n")), Seq(Name("linearize"), Sp, Parenthesized(Seq(Name("wordOfTuple"), Sp, Name("i"), Sp, Name("t"), Sp, Name("hlen"))), Sp, Name("i"), Sp, Eq, Sp, Name("tupleList"), Sp, Name("t"))))))), "The inverse circular offset reads the reconstructed word as its original tuple list.", DescribeRole.Theorem),
        Node("rawWord", "rawWord", Disp(All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), Seq(Name("rawWord"), Sp, Name("t"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("t.map"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("b"), Sp, Mapsto, Sp, Name("List.replicate"), Sp, Name("b.1"), Sp, Name("true"), Sp, Seq(Plus, Plus), Sp, Name("List.replicate"), Sp, Name("b.2"), Sp, Name("false"))))), Sp, Dot, Sp, Name("flatten")))))), "Flattening alternating replicated one and zero blocks encodes the unadjusted run-and-gap lengths.", DescribeRole.Definition),
        Node("rawWord_cons", "rawWord cons", Disp(All(Name("b"), Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")), All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), Seq(Name("rawWord"), Sp, Parenthesized(Seq(Name("b"), Sp, Seq(Colon,Colon), Sp, Name("t"))), Sp, Eq, Sp, Name("List.replicate"), Sp, Name("b.1"), Sp, Name("true"), Sp, Seq(Plus, Plus), Sp, Name("List.replicate"), Sp, Name("b.2"), Sp, Name("false"), Sp, Seq(Plus, Plus), Sp, Name("rawWord"), Sp, Name("t"))))), "The first raw pair contributes its replicated one block and zero block before the remaining pairs.", DescribeRole.Lemma),
        Node("rawWord_append", "rawWord append", Disp(All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), All(Name("u"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), Seq(Name("rawWord"), Sp, Parenthesized(Seq(Name("t"), Sp, Seq(Plus, Plus), Sp, Name("u"))), Sp, Eq, Sp, Name("rawWord"), Sp, Name("t"), Sp, Seq(Plus, Plus), Sp, Name("rawWord"), Sp, Name("u"))))), "Flattening the block encoding transports concatenation of pair lists to concatenation of words.", DescribeRole.Lemma),
        Node("raw_encoding_marked", "raw encoding marked", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), Seq(Parenthesized(Seq(Name("t"), Sp, Neq, Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Forall, Sp, Name("b"), Sp, InMacro, Sp, Name("t"), Sp, Comma, Sp, D(0), Sp, Lt, Sp, Name("b.1"), Sp, Land, Sp, D(0), Sp, Lt, Sp, Name("b.2"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("linearize"), Sp, Name("w"), Sp, Name("i"), Sp, Eq, Sp, Name("rawWord"), Sp, Name("t"))), Sp, To, Sp, Parenthesized(Seq(Name("IsMarkedStart"), Sp, Name("w"), Sp, Name("i"))))))))))))), "Positive first and last block lengths give a one at the origin and a zero at its predecessor.", DescribeRole.Lemma),
        Node("first_raw_run_start", "first raw run start", Disp(All(Name("n"), Name("Nat"), All(Name("r"), Name("Nat"), All(Name("z"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("post"), Seq(Name("List"), Sp, Name("Bool")), Seq(Parenthesized(Seq(D(0), Sp, Lt, Sp, Name("r"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(D(0), Sp, Lt, Sp, Name("z"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("IsMarkedStart"), Sp, Name("w"), Sp, Name("i"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("linearize"), Sp, Name("w"), Sp, Name("i"), Sp, Eq, Sp, Name("List.replicate"), Sp, Name("r"), Sp, Name("true"), Sp, Seq(Plus, Plus), Sp, Name("List.replicate"), Sp, Name("z"), Sp, Name("false"), Sp, Seq(Plus, Plus), Sp, Name("post"))), Sp, To, Sp, Parenthesized(Seq(Name("IsOneRunStart"), Sp, Name("w"), Sp, Name("i"), Sp, Name("r"))))))))))))))))), "The first replicated one block and its adjacent zero blocks delimit the first run.", DescribeRole.Lemma),
        Node("linearize_get_optional", "linearize get optional", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("j"), Name("Nat"), Seq(Parenthesized(Seq(Name("j"), Sp, Lt, Sp, Name("n"))), Sp, To, Sp, Parenthesized(Seq(Name("some"), Sp, Parenthesized(Seq(Parenthesized(Seq(Name("linearize"), Sp, Name("w"), Sp, Name("i"))), Sp, Seq(OpenBracket, Sp, Name("j"), Sp, CloseBracket))), Sp, Eq, Sp, Name("some"), Sp, Parenthesized(Seq(Name("w"), Sp, Parenthesized(Seq(Name("cycAdd"), Sp, Name("i"), Sp, Name("j"))))))))))))), "Optional list access equals some of the indexed letter. Since j<n and linearize has length n, the displayed ordinary indexing has the same value; the two occurrences of some retain the optional equality.", DescribeRole.Lemma),
        Node("marked_admissible_tuple", "marked admissible tuple", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), Seq(Parenthesized(Seq(Name("Admissible"), Sp, Name("w"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("IsMarkedStart"), Sp, Name("w"), Sp, Name("i"))), Sp, To, Sp, Parenthesized(Seq(Exists, Sp, Name("t"), Sp, Colon, Sp, Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat"))), Sp, Comma, Sp, Name("t"), Sp, Neq, Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, Name("b"), Sp, InMacro, Sp, Name("t"), Sp, Comma, Sp, D(0), Sp, Lt, Sp, Name("b.1"))), Sp, Land, Sp, Parenthesized(Seq(Name("t.map"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("b"), Sp, Mapsto, Sp, D(2), Sp, Cdot, Sp, Name("b.1"), Sp, Plus, Sp, D(1), Sp, Plus, Sp, Name("b.2"))))), Sp, Dot, Sp, Name("sum"), Sp, Eq, Sp, Name("n"), Sp, Land, Sp, Name("tupleList"), Sp, Name("t"), Sp, Eq, Sp, Name("linearize"), Sp, Name("w"), Sp, Name("i"), Sp, Land, Sp, Name("extractListTuple"), Sp, Parenthesized(Seq(Name("linearize"), Sp, Name("w"), Sp, Name("i"))), Sp, Eq, Sp, Name("t")))))))))), "Alternating positive blocks recover the raw pairs, and admissibility turns every excess gap into nonnegative slack.", DescribeRole.Theorem),
        Node("raw_encoding_admissible", "raw encoding admissible", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), Seq(Parenthesized(Seq(Name("t"), Sp, Neq, Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Forall, Sp, Name("b"), Sp, InMacro, Sp, Name("t"), Sp, Comma, Sp, D(0), Sp, Lt, Sp, Name("b.1"), Sp, Land, Sp, Name("b.1"), Sp, Lt, Sp, Name("b.2"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("linearize"), Sp, Name("w"), Sp, Name("i"), Sp, Eq, Sp, Name("rawWord"), Sp, Name("t"))), Sp, To, Sp, Parenthesized(Seq(Name("Admissible"), Sp, Name("w"))))))))))))), "Every marked run lies at a block boundary whose longer zero block fulfils the circular gap condition.", DescribeRole.Theorem),
        Node("raw_encoding_admissible_iff", "raw encoding admissible iff", Disp(All(Name("n"), Name("Nat"), All(Name("w"), Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool")), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), Seq(Parenthesized(Seq(Name("t"), Sp, Neq, Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Forall, Sp, Name("b"), Sp, InMacro, Sp, Name("t"), Sp, Comma, Sp, D(0), Sp, Lt, Sp, Name("b.1"), Sp, Land, Sp, D(0), Sp, Lt, Sp, Name("b.2"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("linearize"), Sp, Name("w"), Sp, Name("i"), Sp, Eq, Sp, Name("rawWord"), Sp, Name("t"))), Sp, To, Sp, Parenthesized(Seq(Name("Admissible"), Sp, Name("w"), Sp, Iff, Sp, Forall, Sp, Name("b"), Sp, InMacro, Sp, Name("t"), Sp, Comma, Sp, Name("b.1"), Sp, Lt, Sp, Name("b.2"))))))))))))), "The block-boundary run starts make admissibility equivalent to the strict inequality for each following gap.", DescribeRole.Theorem),
        Node("pairPrefix", "pairPrefix", Disp(All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), All(Name("p"), Name("Nat"), Seq(Name("pairPrefix"), Sp, Name("t"), Sp, Name("p"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("rawWord"), Sp, Parenthesized(Seq(Name("t.take"), Sp, Name("p"))))), Sp, Dot, Sp, Name("length"))))))), "Summing earlier pair lengths gives the labelled offset of a raw pair boundary.", DescribeRole.Definition),
        Node("rawPairs", "rawPairs", Disp(All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), Seq(Name("rawPairs"), Sp, Name("t"), Sp, Eq, Sp, Parenthesized(Seq(Name("t.map"), Sp, Parenthesized(Seq(Name("fun"), Sp, Name("b"), Sp, Mapsto, Sp, Parenthesized(Seq(Name("b.1"), Sp, Comma, Sp, Name("b.1"), Sp, Plus, Sp, D(1), Sp, Plus, Sp, Name("b.2")))))))))), "Adding the compulsory run length plus one to the slack converts tuples into raw run-and-gap pairs.", DescribeRole.Definition),
        Node("tupleList_eq_rawPairs", "tupleList eq rawPairs", Disp(All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), Seq(Name("tupleList"), Sp, Name("t"), Sp, Eq, Sp, Name("rawWord"), Sp, Parenthesized(Seq(Name("rawPairs"), Sp, Name("t")))))), "The compulsory zero lengths identify the slack encoding with the raw-pair encoding.", DescribeRole.Lemma),
        Node("tuple_word_admissible", "tuple word admissible", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), All(Name("hlen"), Seq(Parenthesized(Seq(Name("tupleList"), Sp, Name("t"))), Sp, Dot, Sp, Name("length"), Sp, Eq, Sp, Name("n")), Seq(Parenthesized(Seq(Name("t"), Sp, Neq, Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Forall, Sp, Name("b"), Sp, InMacro, Sp, Name("t"), Sp, Comma, Sp, D(0), Sp, Lt, Sp, Name("b.1"))), Sp, To, Sp, Parenthesized(Seq(Name("Admissible"), Sp, Parenthesized(Seq(Name("wordOfTuple"), Sp, Name("i"), Sp, Name("t"), Sp, Name("hlen"))))))))))))), "Every positive tuple run has its compulsory strictly longer zero block in the reconstructed word.", DescribeRole.Lemma),
        Node("tuple_word_marked", "tuple word marked", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), All(Name("hlen"), Seq(Parenthesized(Seq(Name("tupleList"), Sp, Name("t"))), Sp, Dot, Sp, Name("length"), Sp, Eq, Sp, Name("n")), Seq(Parenthesized(Seq(Name("t"), Sp, Neq, Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(Forall, Sp, Name("b"), Sp, InMacro, Sp, Name("t"), Sp, Comma, Sp, D(0), Sp, Lt, Sp, Name("b.1"))), Sp, To, Sp, Parenthesized(Seq(Name("IsMarkedStart"), Sp, Parenthesized(Seq(Name("wordOfTuple"), Sp, Name("i"), Sp, Name("t"), Sp, Name("hlen"))), Sp, Name("i"))))))))))), "A nonempty positive tuple begins with a one and ends with a zero, marking its reconstruction origin.", DescribeRole.Lemma),
        Node("GoodTuple", "GoodTuple", Disp(All(Name("n"), Name("Nat"), Seq(Name("GoodTuple"), Sp, Name("n"), Sp, Eq, Sp, Parenthesized(Seq(OpenBrace, Sp, Seq(Name("t"), Sp, Colon, Sp, Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat"))), Sp, Seq(Slash,Slash), Sp, Name("t"), Sp, Neq, Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, Name("b"), Sp, InMacro, Sp, Name("t"), Sp, Comma, Sp, D(0), Sp, Lt, Sp, Name("b.1"))), Sp, Land, Sp, Parenthesized(Seq(Name("tupleList"), Sp, Name("t"))), Sp, Dot, Sp, Name("length"), Sp, Eq, Sp, Name("n")), Sp, CloseBrace))))), "The subtype fixes a nonempty positive-run tuple whose encoded length is the prescribed length.", DescribeRole.Definition),
        Node("MarkedWords", "MarkedWords", Disp(All(Name("n"), Name("Nat"), Seq(Name("MarkedWords"), Sp, Name("n"), Sp, Eq, Sp, Parenthesized(Seq(OpenBrace, Sp, Seq(Name("p"), Sp, Colon, Sp, Parenthesized(Seq(Name("Fin"), Sp, Name("n"), Sp, To, Sp, Name("Bool"))), Sp, Times, Sp, Name("Fin"), Sp, Name("n"), Sp, Seq(Slash,Slash), Sp, Name("Admissible"), Sp, Name("p.1"), Sp, Land, Sp, Name("IsMarkedStart"), Sp, Name("p.1"), Sp, Name("p.2")), Sp, CloseBrace))))), "The subtype records an admissible labelled word together with a positive marked start.", DescribeRole.Definition),
        Node("extractMarked", "extractMarked", Disp(new Formula.Aligned([All(Name("n"), Name("Nat"), All(Name("x"), Seq(Name("MarkedWords"), Sp, Name("n")), Seq(Parenthesized(Seq(Name("extractMarked"), Sp, Name("x"))), Sp, Dot, Sp, D(1), Sp, Eq, Sp, Name("x.val.2")))), All(Name("n"), Name("Nat"), All(Name("x"), Seq(Name("MarkedWords"), Sp, Name("n")), Seq(Parenthesized(Seq(Name("extractMarked"), Sp, Name("x"))), Sp, Dot, Sp, D(2), Sp, Dot, Sp, Name("val"), Sp, Eq, Sp, Name("extractListTuple"), Sp, Parenthesized(Seq(Name("linearize"), Sp, Name("x.val.1"), Sp, Name("x.val.2"))))))])), "The first component is the labelled run mark. The second component has the displayed underlying list, with its nonemptiness, positivity and total-length proofs supplied by marked_admissible_tuple.", DescribeRole.Definition),
        Node("reconstructMarked", "reconstructMarked", Disp(All(Name("n"), Name("Nat"), All(Name("x"), Seq(Name("Fin"), Sp, Name("n"), Sp, Times, Sp, Name("GoodTuple"), Sp, Name("n")), Seq(Parenthesized(Seq(Name("reconstructMarked"), Sp, Name("x"))), Sp, Dot, Sp, Name("val"), Sp, Eq, Sp, Parenthesized(Seq(Name("wordOfTuple"), Sp, Name("x.1"), Sp, Name("x.2.val"), Sp, Name("x.2.property.2.2"), Sp, Comma, Sp, Name("x.1"))))))), "The displayed value is the underlying labelled word and mark. The subtype proof is supplied by tuple_word_admissible and tuple_word_marked.", DescribeRole.Definition),
        Node("markedTupleEquiv", "markedTupleEquiv", Disp(new Formula.Aligned([All(Name("n"), Name("Nat"), Seq(Name("markedTupleEquiv"), Sp, Name("n"), Sp, Colon, Sp, Name("MarkedWords"), Sp, Name("n"), Sp, Equiv, Sp, Name("Fin"), Sp, Name("n"), Sp, Times, Sp, Name("GoodTuple"), Sp, Name("n"))), All(Name("n"), Name("Nat"), Seq(Parenthesized(Seq(Name("markedTupleEquiv"), Sp, Name("n"))), Sp, Dot, Sp, Name("toFun"), Sp, Eq, Sp, Name("extractMarked"))), All(Name("n"), Name("Nat"), Seq(Parenthesized(Seq(Name("markedTupleEquiv"), Sp, Name("n"))), Sp, Dot, Sp, Name("invFun"), Sp, Eq, Sp, Name("reconstructMarked")))])), "Extraction and reconstruction are inverse through constant-block decoding and the marked boundary conditions.", DescribeRole.Definition),
        Node("instFiniteGoodTuple", "instFiniteGoodTuple", Disp(All(Name("n"), Name("Nat"), Seq(Name("instFiniteGoodTuple"), Sp, Name("n"), Sp, Colon, Sp, Name("Finite"), Sp, Parenthesized(Seq(Name("GoodTuple"), Sp, Name("n")))))), "Finiteness is constructed by Finite.of_injective, using the map that sends a good tuple to its reconstructed List.Vector Bool n and the injectivity of that map.", DescribeRole.Definition),
        Node("instFintypeGoodTuple", "instFintypeGoodTuple", Disp(All(Name("n"), Name("Nat"), Seq(Name("instFintypeGoodTuple"), Sp, Name("n"), Sp, Colon, Sp, Name("Fintype"), Sp, Parenthesized(Seq(Name("GoodTuple"), Sp, Name("n")))))), "The enumerating instance is Fintype.ofFinite (GoodTuple n).", DescribeRole.Definition),
        Node("runCount_wordOfTuple", "runCount wordOfTuple", Disp(All(Name("n"), Name("Nat"), All(Name("i"), Seq(Name("Fin"), Sp, Name("n")), All(Name("t"), Seq(Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")))), All(Name("hlen"), Seq(Parenthesized(Seq(Name("tupleList"), Sp, Name("t"))), Sp, Dot, Sp, Name("length"), Sp, Eq, Sp, Name("n")), Seq(Parenthesized(Seq(Forall, Sp, Name("b"), Sp, InMacro, Sp, Name("t"), Sp, Comma, Sp, D(0), Sp, Lt, Sp, Name("b.1"))), Sp, To, Sp, Parenthesized(Seq(Name("runCount"), Sp, Parenthesized(Seq(Name("wordOfTuple"), Sp, Name("i"), Sp, Name("t"), Sp, Name("hlen"))), Sp, Eq, Sp, Name("t.length"))))))))), "The distinct pair-prefix positions enumerate exactly the marked starts of the reconstructed word.", DescribeRole.Theorem),
        Node("extractMarked_runs", "extractMarked runs", Disp(All(Name("n"), Name("Nat"), All(Name("x"), Seq(Name("MarkedWords"), Sp, Name("n")), Seq(Name("runCount"), Sp, Name("x.val.1"), Sp, Eq, Sp, Parenthesized(Seq(Name("extractMarked"), Sp, Name("x"))), Sp, Dot, Sp, D(2), Sp, Dot, Sp, Name("val.length"))))), "Reconstruction preserves the word, and the tuple length counts its marked run starts.", DescribeRole.Lemma),
        Node("RunTuples", "RunTuples", Disp(All(Name("n"), Name("Nat"), All(Name("ell"), Name("Nat"), Seq(Name("RunTuples"), Sp, Name("n"), Sp, Name("ell"), Sp, Eq, Sp, Parenthesized(Seq(OpenBrace, Sp, Seq(Name("t"), Sp, Colon, Sp, Name("GoodTuple"), Sp, Name("n"), Sp, Seq(Slash,Slash), Sp, Name("t.val.length"), Sp, Eq, Sp, Name("ell")), Sp, CloseBrace)))))), "The subtype restricts good tuples to a prescribed number of run-and-slack pairs.", DescribeRole.Definition))));

    private static DocumentBlock Node(string name, string title, Formula formula, string prose, DescribeRole role, bool literature = false) => Describe.Lean(
        DescribeId.Create("amg-runtuplebijection-" + name.Replace('_', '-').Replace('.', '-').ToLowerInvariant()),
        DeclarationHandle.Create(Prefix + name), H(title), StatementSource.FromAuthor(formula),
        literature ? AssessedProvenance.FromLiterature(Source) : AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text(prose))), role);

    private static Formula Parenthesized(Formula value) => Seq(Open, value, Close);
    private static Formula All(Formula variable, Formula type, Formula body) => Seq(Forall, Sp, Parenthesized(Seq(variable, Colon, Sp, type)), Comma, Sp, body);
    private static Formula Q(string owner, string name) => Seq(Operatorname, Grp(Seq(F.Id(owner), Dot, F.Id(name))));
    private static Formula App(Formula f, params Formula[] args) => new Formula.Apply(f, [.. args]);
    private static Formula Name(string name) {
        var parts = name.Split('.');
        Formula value = Word(parts[0]);
        for (var i = 1; i < parts.Length; i++) value = Seq(value, Dot, Word(parts[i]));
        return value;
    }
    private static Formula Word(string word) {
        if (word == "") return Sp;
        if (word == "0") return D(0);
        if (word == "1") return D(1);
        if (word == "2") return D(2);
        if (word.EndsWith("'", StringComparison.Ordinal)) return Seq(Word(word[..^1]), Apos);
        var parts = word.Split('_');
        Formula value = Seq(Operatorname, Grp(F.Id(parts[0])));
        for (var i = 1; i < parts.Length; i++) value = new Formula.Subscript(value, Seq(Operatorname, Grp(F.Id(parts[i]))));
        return value;
    }
}
