using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S1.Words.AssociatedMersenne;

internal sealed class TransferTuplesDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S1/Words/AssociatedMersenne/TransferTuples.";
    private static readonly LibraryNoteRef Source = LibraryNoteRef.Create("D5/L/Words/wei2024associatedmersenne");
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create("Degree enumeration for labelled circular run-constrained words.", H("TransferTuples"), Blocks(
        Node("geom", "geom", Disp(All(Name("z"), Seq(Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z")))))), Seq(Name("geom"), Sp, Name("z"), Sp, Eq, Sp, Parenthesized(Seq(Name("PowerSeries.invOfUnit"), Sp, Parenthesized(Seq(D(1), Sp, Minus, Sp, Name("z"))), Sp, D(1)))))), "The inverse of one minus a positive-order series supplies its formal geometric series.", DescribeRole.Definition),
        Node("Rser", "Rser", Disp(Seq(Name("Rser"), Sp, Eq, Sp, Parenthesized(Seq(new Formula.Power(Parenthesized(Seq(Name("PowerSeries.X"), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), D(3)), Sp, Cdot, Sp, Parenthesized(Seq(Name("PowerSeries.C"), Sp, Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Plus, Sp, new Formula.Power(Parenthesized(Seq(Name("PowerSeries.X"), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), D(5)), Sp, Cdot, Sp, new Formula.Power(Parenthesized(Seq(Name("PowerSeries.C"), Sp, Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), D(2)), Sp, Cdot, Sp, Name("geom"), Sp, Parenthesized(new Formula.Power(Parenthesized(Seq(Name("PowerSeries.X"), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), D(2))))))), "The run series separates a singleton one-run weight from the geometric tail of longer runs.", DescribeRole.Definition),
        Node("Qser", "Qser", Disp(Seq(Name("Qser"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("PowerSeries.X"), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Cdot, Sp, Name("geom"), Sp, Parenthesized(Seq(Parenthesized(Seq(Name("PowerSeries.C"), Sp, Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Cdot, Sp, Parenthesized(Seq(Name("PowerSeries.X"), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))))))))), "The slack series records a compulsory position followed by an arbitrary weighted slack tail.", DescribeRole.Definition),
        Node("A", "A", Disp(new Formula.Aligned([Seq(Name("A"), Sp, D(0), Sp, D(0), Sp, Eq, Sp, Name("Rser")), Seq(Name("A"), Sp, D(0), Sp, D(1), Sp, Eq, Sp, Name("Rser"), Sp, Cdot, Sp, Name("Qser")), Seq(Name("A"), Sp, D(1), Sp, D(0), Sp, Eq, Sp, Name("Rser")), Seq(Name("A"), Sp, D(1), Sp, D(1), Sp, Eq, Sp, Name("Rser"), Sp, Cdot, Sp, Parenthesized(Seq(Name("PowerSeries.C"), Sp, Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Cdot, Sp, Name("Qser"))])), "The two slack states determine the transfer entries from run and gap weight factors.", DescribeRole.Definition),
        Node("det_A", "det A", Disp(Seq(Name("Matrix.det"), Sp, Parenthesized(Seq(D(1), Sp, Minus, Sp, Name("A"))), Sp, Eq, Sp, D(1), Sp, Minus, Sp, Name("Rser"), Sp, Minus, Sp, Name("Rser"), Sp, Cdot, Sp, Parenthesized(Seq(Name("PowerSeries.C"), Sp, Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Cdot, Sp, Name("Qser"), Sp, Plus, Sp, new Formula.Power(Name("Rser"), D(2)), Sp, Cdot, Sp, Parenthesized(Seq(Parenthesized(Seq(Name("PowerSeries.C"), Sp, Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Minus, Sp, D(1))), Sp, Cdot, Sp, Name("Qser"))), "Expanding the two-by-two determinant expresses the transfer denominator in run and slack series.", DescribeRole.Lemma),
        Node("geom_X2", "geom X2", Disp(Seq(Parenthesized(Seq(D(1), Sp, Minus, Sp, new Formula.Power(Parenthesized(Seq(Name("PowerSeries.X"), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), D(2)))), Sp, Cdot, Sp, Name("geom"), Sp, Parenthesized(new Formula.Power(Parenthesized(Seq(Name("PowerSeries.X"), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), D(2))), Sp, Eq, Sp, D(1))), "Multiplication by one minus the square of the length variable cancels its geometric series.", DescribeRole.Lemma),
        Node("geom_YX", "geom YX", Disp(Seq(Parenthesized(Seq(D(1), Sp, Minus, Sp, Parenthesized(Seq(Name("PowerSeries.C"), Sp, Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Cdot, Sp, Parenthesized(Seq(Name("PowerSeries.X"), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))))), Sp, Cdot, Sp, Name("geom"), Sp, Parenthesized(Seq(Parenthesized(Seq(Name("PowerSeries.C"), Sp, Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Cdot, Sp, Parenthesized(Seq(Name("PowerSeries.X"), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))))), Sp, Eq, Sp, D(1))), "Multiplication by one minus the joint length-and-degree variable cancels its geometric series.", DescribeRole.Lemma),
        Node("AgreeUpTo", "AgreeUpTo", Disp(All(Name("N"), Name("Nat"), All(Name("f"), Parenthesized(Seq(Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), All(Name("g"), Parenthesized(Seq(Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Seq(Name("AgreeUpTo"), Sp, Name("N"), Sp, Name("f"), Sp, Name("g"), Sp, Iff, Sp, Parenthesized(Seq(Forall, Sp, Name("n"), Sp, Comma, Sp, Name("n"), Sp, Le, Sp, Name("N"), Sp, To, Sp, Name("PowerSeries.coeff"), Sp, Name("n"), Sp, Name("f"), Sp, Eq, Sp, Name("PowerSeries.coeff"), Sp, Name("n"), Sp, Name("g")))))))), "Agreement of coefficients through a bound records the finite precision needed for enumeration.", DescribeRole.Definition),
        Node("geom_monomial_approx", "geom monomial approx", Disp(All(Name("m"), Name("Nat"), All(Name("d"), Name("Nat"), All(Name("N"), Name("Nat"), Seq(Parenthesized(Seq(D(0), Sp, Lt, Sp, Name("m"))), Sp, To, Sp, Parenthesized(Seq(Name("AgreeUpTo"), Sp, Name("N"), Sp, Parenthesized(Seq(Name("geom"), Sp, Parenthesized(Seq(Name("PowerSeries.monomial"), Sp, Name("m"), Sp, Parenthesized(new Formula.Power(Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Name("d"))))))), Sp, Parenthesized(Seq(Sum, Sp, Name("j"), Sp, InMacro, Sp, Name("Finset.range"), Sp, Parenthesized(Seq(Name("N"), Sp, Plus, Sp, D(1))), Sp, Comma, Sp, new Formula.Power(Parenthesized(Seq(Name("PowerSeries.monomial"), Sp, Name("m"), Sp, Parenthesized(new Formula.Power(Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Name("d"))))), Name("j"))))))))))), "The finite geometric-sum identity and the positive monomial order remove all omitted low-degree coefficients.", DescribeRole.Theorem),
        Node("slackState", "slackState", Disp(All(Name("s"), Name("Nat"), Seq(Name("slackState"), Sp, Name("s"), Sp, Eq, Sp, Parenthesized(Seq(Name("if"), Sp, Name("s"), Sp, Eq, Sp, D(0), Sp, Name("then"), Sp, D(0), Sp, Name("else"), Sp, D(1)))))), "Zero slack selects one transfer state and positive slack selects the other.", DescribeRole.Definition),
        Node("pairLocal", "pairLocal", Disp(All(Name("b"), Seq(Name("Nat"), Sp, Times, Sp, Name("Nat")), Seq(Name("pairLocal"), Sp, Name("b"), Sp, Eq, Sp, Parenthesized(Seq(Name("min"), Sp, Name("b.1"), Sp, D(2), Sp, Plus, Sp, Parenthesized(Seq(Name("b.2"), Sp, Minus, Sp, D(1)))))))), "The local weight counts run deletion endpoints and the interior contribution from one gap.", DescribeRole.Definition),
        Node("adjacency", "adjacency", Disp(All(Name("i"), Seq(Name("Fin"), Sp, D(2)), All(Name("j"), Seq(Name("Fin"), Sp, D(2)), Seq(Name("adjacency"), Sp, Name("i"), Sp, Name("j"), Sp, Eq, Sp, Parenthesized(Seq(Name("if"), Sp, Name("i"), Sp, Eq, Sp, D(1), Sp, Land, Sp, Name("j"), Sp, Eq, Sp, D(1), Sp, Name("then"), Sp, D(1), Sp, Name("else"), Sp, D(0))))))), "The transition contributes one insertion exactly when both consecutive slack states are positive.", DescribeRole.Definition),
        Node("openDegree", "openDegree", Disp(new Formula.Aligned([All(Name("j"), Seq(Name("Fin"), Sp, D(2)), Seq(Name("openDegree"), Sp, Name("j"), Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket), Sp, Eq, Sp, D(0))), All(Name("j"), Seq(Name("Fin"), Sp, D(2)), Seq(Forall, Sp, Parenthesized(Seq(Name("b"), Sp, Colon, Sp, Name("Nat"), Sp, Times, Sp, Name("Nat"))), Sp, Comma, Sp, Name("openDegree"), Sp, Name("j"), Sp, Seq(OpenBracket, Sp, Name("b"), Sp, CloseBracket), Sp, Eq, Sp, Name("pairLocal"), Sp, Name("b"), Sp, Plus, Sp, Name("adjacency"), Sp, Parenthesized(Seq(Name("slackState"), Sp, Name("b.2"))), Sp, Name("j"))), All(Name("j"), Seq(Name("Fin"), Sp, D(2)), Seq(Forall, Sp, Parenthesized(Seq(Name("b"), Sp, Name("c"), Sp, Colon, Sp, Name("Nat"), Sp, Times, Sp, Name("Nat"))), Sp, Parenthesized(Seq(Name("t"), Sp, Colon, Sp, Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat"))))), Sp, Comma, Sp, Name("openDegree"), Sp, Name("j"), Sp, Parenthesized(Seq(Name("b"), Sp, Seq(Colon,Colon), Sp, Name("c"), Sp, Seq(Colon,Colon), Sp, Name("t"))), Sp, Eq, Sp, Name("pairLocal"), Sp, Name("b"), Sp, Plus, Sp, Name("adjacency"), Sp, Parenthesized(Seq(Name("slackState"), Sp, Name("b.2"))), Sp, Parenthesized(Seq(Name("slackState"), Sp, Name("c.2"))), Sp, Plus, Sp, Name("openDegree"), Sp, Name("j"), Sp, Parenthesized(Seq(Name("c"), Sp, Seq(Colon,Colon), Sp, Name("t")))))])), "Accumulating pair-local weights and state transitions gives the weight of an open tuple path.", DescribeRole.Definition),
        Node("provisionalDegree", "provisionalDegree", Disp(new Formula.Aligned([Seq(Name("provisionalDegree"), Sp, Seq(OpenBracket, Sp, Sp, Sp, CloseBracket), Sp, Eq, Sp, D(0)), Seq(Forall, Sp, Parenthesized(Seq(Name("b"), Sp, Colon, Sp, Name("Nat"), Sp, Times, Sp, Name("Nat"))), Sp, Parenthesized(Seq(Name("u"), Sp, Colon, Sp, Name("List"), Sp, Parenthesized(Seq(Name("Nat"), Sp, Times, Sp, Name("Nat"))))), Sp, Comma, Sp, Name("provisionalDegree"), Sp, Parenthesized(Seq(Name("b"), Sp, Seq(Colon,Colon), Sp, Name("u"))), Sp, Eq, Sp, Name("openDegree"), Sp, Parenthesized(Seq(Name("slackState"), Sp, Name("b.2"))), Sp, Parenthesized(Seq(Name("b"), Sp, Seq(Colon,Colon), Sp, Name("u"))))])), "Closing the tuple path adds the final transition back to the initial slack state.", DescribeRole.Definition),
        Node("trace_coefficient_tuples", "trace coefficient tuples", Disp(All(Name("n"), Name("Nat"), All(Name("ell"), Name("Nat"), Seq(Name("PowerSeries.coeff"), Sp, Name("n"), Sp, Parenthesized(Seq(Name("Matrix.trace"), Sp, Parenthesized(new Formula.Power(Name("A"), Parenthesized(Seq(Name("ell"), Sp, Plus, Sp, D(1))))))), Sp, Eq, Sp, Sum, Sp, Name("t"), Sp, Colon, Sp, Name("RunTuples"), Sp, Name("n"), Sp, Parenthesized(Seq(Name("ell"), Sp, Plus, Sp, D(1))), Sp, Comma, Sp, new Formula.Power(Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Seq(Name("provisionalDegree"), Sp, Name("t.val.val"))))))), "The matrix trace enumerates ordered tuples at each finite length, with provisionalDegree. No rotations of the word are identified.", DescribeRole.Theorem),
        Node("tuple_transfer_coefficient", "tuple transfer coefficient", Disp(All(Name("n"), Name("Nat"), All(Name("ell"), Name("Nat"), Seq(Name("tuplePolynomial"), Sp, Name("n"), Sp, Parenthesized(Seq(Name("ell"), Sp, Plus, Sp, D(1))), Sp, Eq, Sp, Name("PowerSeries.coeff"), Sp, Name("n"), Sp, Parenthesized(Seq(Name("Matrix.trace"), Sp, Parenthesized(new Formula.Power(Name("A"), Parenthesized(Seq(Name("ell"), Sp, Plus, Sp, D(1))))))), Sp, Plus, Sp, Name("if"), Sp, Name("ell"), Sp, Eq, Sp, D(0), Sp, Name("then"), Sp, Name("PowerSeries.coeff"), Sp, Name("n"), Sp, Parenthesized(Seq(Parenthesized(Seq(Name("PowerSeries.X"), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Cdot, Sp, Parenthesized(Seq(D(1), Sp, Minus, Sp, Parenthesized(Seq(Name("PowerSeries.C"), Sp, Parenthesized(Seq(Name("Polynomial.X"), Sp, Colon, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Colon, Sp, Name("PowerSeries"), Sp, Parenthesized(Seq(Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))))))))), Sp, Cdot, Sp, Name("Rser"))), Sp, Name("else"), Sp, D(0))))), "The correction PowerSeries.X * (1 - PowerSeries.C Polynomial.X) * Rser removes the extra singleton insertion. For [(r,1)], provisionalDegree is min r 2 + 1 and tupleDegree is min r 2.", DescribeRole.Theorem),
        Describe.Lean(DescribeId.Create("amg-transfertuples-geom-mul"), DeclarationHandle.Create(Prefix + "geom_mul"), H("Geometric series inverse"), StatementSource.FromAuthor(Disp(All(Name("z"), Seq(Name("PowerSeries"), Sp, Seq(Open, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))), Close)), All(Name("hz"), Seq(Name("PowerSeries.constantCoeff"), Sp, Name("z"), Sp, Eq, Sp, D(0)), Seq(Seq(Open, D(1), Sp, Minus, Sp, Name("z"), Close), Sp, Cdot, Sp, Name("geom"), Sp, Name("z"), Sp, Eq, Sp, D(1)))))), AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text("A series with zero constant coefficient has geometric series inverse to one minus the series."))), DescribeRole.Lemma),
        Describe.Lean(DescribeId.Create("amg-transfertuples-agreeupto-add"), DeclarationHandle.Create(Prefix + "add"), H("Agreement under addition"), StatementSource.FromAuthor(Disp(All(Name("N"), Seq(Name("Nat")), All(Name("f"), Seq(Seq(Open, Name("PowerSeries"), Sp, Seq(Open, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))), Close), Close)), All(Name("g"), Seq(Seq(Open, Name("PowerSeries"), Sp, Seq(Open, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))), Close), Close)), All(Name("u"), Seq(Seq(Open, Name("PowerSeries"), Sp, Seq(Open, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))), Close), Close)), All(Name("v"), Seq(Seq(Open, Name("PowerSeries"), Sp, Seq(Open, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))), Close), Close)), All(Name("h"), Seq(Name("AgreeUpTo"), Sp, Name("N"), Sp, Name("f"), Sp, Name("g")), All(Name("k"), Seq(Name("AgreeUpTo"), Sp, Name("N"), Sp, Name("u"), Sp, Name("v")), Seq(Name("AgreeUpTo"), Sp, Name("N"), Sp, Seq(Open, Name("f"), Sp, Plus, Sp, Name("u"), Close), Sp, Seq(Open, Name("g"), Sp, Plus, Sp, Name("v"), Close))))))))))), AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text("Coefficient agreement through a bound is preserved by addition."))), DescribeRole.Lemma),
        Describe.Lean(DescribeId.Create("amg-transfertuples-agreeupto-mul"), DeclarationHandle.Create(Prefix + "mul"), H("Agreement under multiplication"), StatementSource.FromAuthor(Disp(All(Name("N"), Seq(Name("Nat")), All(Name("f"), Seq(Seq(Open, Name("PowerSeries"), Sp, Seq(Open, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))), Close), Close)), All(Name("g"), Seq(Seq(Open, Name("PowerSeries"), Sp, Seq(Open, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))), Close), Close)), All(Name("u"), Seq(Seq(Open, Name("PowerSeries"), Sp, Seq(Open, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))), Close), Close)), All(Name("v"), Seq(Seq(Open, Name("PowerSeries"), Sp, Seq(Open, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))), Close), Close)), All(Name("h"), Seq(Name("AgreeUpTo"), Sp, Name("N"), Sp, Name("f"), Sp, Name("g")), All(Name("k"), Seq(Name("AgreeUpTo"), Sp, Name("N"), Sp, Name("u"), Sp, Name("v")), Seq(Name("AgreeUpTo"), Sp, Name("N"), Sp, Seq(Open, Name("f"), Sp, Cdot, Sp, Name("u"), Close), Sp, Seq(Open, Name("g"), Sp, Cdot, Sp, Name("v"), Close))))))))))), AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text("Coefficient agreement through a bound is preserved by multiplication."))), DescribeRole.Lemma),
        Describe.Lean(DescribeId.Create("amg-transfertuples-geom-finite-identity"), DeclarationHandle.Create(Prefix + "geom_finite_identity"), H("Finite geometric identity"), StatementSource.FromAuthor(Disp(All(Name("z"), Seq(Seq(Open, Name("PowerSeries"), Sp, Seq(Open, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z"))), Close), Close)), All(Name("N"), Seq(Name("Nat")), All(Name("hz"), Seq(Name("PowerSeries.constantCoeff"), Sp, Name("z"), Sp, Eq, Sp, D(0)), Seq(Name("geom"), Sp, Name("z"), Sp, Eq, Sp, Seq(Open, Sum, Sp, Name("j"), Sp, InMacro, Sp, Name("Finset.range"), Sp, Seq(Open, Name("N"), Sp, Plus, Sp, D(1), Close), Sp, Comma, Sp, new Formula.Power(Name("z"), Name("j")), Close), Sp, Plus, Sp, new Formula.Power(Name("z"), Seq(Open, Name("N"), Sp, Plus, Sp, D(1), Close)), Sp, Cdot, Sp, Name("geom"), Sp, Name("z"))))))), AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text("The geometric series equals its finite truncation plus the remaining tail."))), DescribeRole.Lemma),
        Describe.Lean(DescribeId.Create("amg-transfertuples-transferlength"), DeclarationHandle.Create(Prefix + "transferLength"), H("Transfer length"), StatementSource.FromAuthor(Disp(All(Name("t"), Seq(Name("List"), Sp, Seq(Open, Name("Nat"), Sp, Times, Sp, Name("Nat"), Close)), Seq(Name("transferLength"), Sp, Name("t"), Sp, Eq, Sp, Seq(Open, Name("t.map"), Sp, Name("pairLength"), Close), Sp, Name("."), Sp, Name("sum"))))), AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text("The transfer length is the sum of the pair lengths in a tuple."))), DescribeRole.Definition),
        Describe.Lean(DescribeId.Create("amg-transfertuples-alphabetpair"), DeclarationHandle.Create(Prefix + "alphabetPair"), H("Alphabet pair"), StatementSource.FromAuthor(Disp(All(Name("N"), Seq(Name("Nat")), All(Name("b"), Seq(Name("Fin"), Sp, Seq(Open, Name("N"), Sp, Plus, Sp, D(2), Close), Sp, Times, Sp, Name("Fin"), Sp, Seq(Open, Name("N"), Sp, Plus, Sp, D(2), Close)), Seq(Name("alphabetPair"), Sp, Name("b"), Sp, Eq, Sp, Seq(Open, Name("b.1.val"), Sp, Plus, Sp, D(1), Sp, Comma, Sp, Name("b.2.val"), Close)))))), AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text("A bounded alphabet pair maps to its natural run and gap lengths."))), DescribeRole.Definition),
        Describe.Lean(DescribeId.Create("amg-transfertuples-boundedlist"), DeclarationHandle.Create(Prefix + "boundedList"), H("Bounded tuple list"), StatementSource.FromAuthor(Disp(All(Name("n"), Seq(Name("Nat")), All(Name("ell"), Seq(Name("Nat")), All(Name("f"), Seq(Name("Fin"), Sp, Name("ell"), Sp, To, Sp, Name("Fin"), Sp, Seq(Open, Name("n"), Sp, Plus, Sp, D(2), Close), Sp, Times, Sp, Name("Fin"), Sp, Seq(Open, Name("n"), Sp, Plus, Sp, D(2), Close)), Seq(Name("boundedList"), Sp, Name("n"), Sp, Name("ell"), Sp, Name("f"), Sp, Eq, Sp, Name("List.ofFn"), Sp, Seq(Open, Name("fun"), Sp, Name("p"), Sp, Mapsto, Sp, Name("alphabetPair"), Sp, Seq(Open, Name("f"), Sp, Name("p"), Close), Close))))))), AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text("A bounded function of alphabet pairs is converted to a list of natural pairs."))), DescribeRole.Definition),
        Describe.Lean(DescribeId.Create("amg-transfertuples-bounded-weight-sum"), DeclarationHandle.Create(Prefix + "bounded_weight_sum"), H("Bounded weight sum"), StatementSource.FromAuthor(Disp(All(Name("n"), Seq(Name("Nat")), All(Name("ell"), Seq(Name("Nat")), All(Name("g"), Seq(Name("List"), Sp, Seq(Open, Name("Nat"), Sp, Times, Sp, Name("Nat"), Close), Sp, To, Sp, Name("Polynomial"), Sp, Seq(Mathbb, Grp(F.Id("Z")))), Seq(Seq(Open, Sum, Sp, Name("f"), Sp, Colon, Sp, Name("Fin"), Sp, Seq(Open, Name("ell"), Sp, Plus, Sp, D(1), Close), Sp, To, Sp, Name("Fin"), Sp, Seq(Open, Name("n"), Sp, Plus, Sp, D(2), Close), Sp, Times, Sp, Name("Fin"), Sp, Seq(Open, Name("n"), Sp, Plus, Sp, D(2), Close), Sp, Comma, Sp, Name("if"), Sp, Name("transferLength"), Sp, Seq(Open, Name("boundedList"), Sp, Name("n"), Sp, Seq(Open, Name("ell"), Sp, Plus, Sp, D(1), Close), Sp, Name("f"), Close), Sp, Eq, Sp, Name("n"), Sp, Name("then"), Sp, Name("g"), Sp, Seq(Open, Name("boundedList"), Sp, Name("n"), Sp, Seq(Open, Name("ell"), Sp, Plus, Sp, D(1), Close), Sp, Name("f"), Close), Sp, Name("else"), Sp, D(0), Close), Sp, Eq, Sp, Sum, Sp, Name("t"), Sp, Colon, Sp, Name("RunTuples"), Sp, Name("n"), Sp, Seq(Open, Name("ell"), Sp, Plus, Sp, D(1), Close), Sp, Comma, Sp, Name("g"), Sp, Name("t.val.val"))))))), AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text("Summing weights over bounded functions equals summing over the corresponding bounded tuples."))), DescribeRole.Theorem)
)));

    private static DocumentBlock Node(string name, string title, Formula formula, string prose, DescribeRole role, bool literature = false) => Describe.Lean(
        DescribeId.Create("amg-transfertuples-" + name.Replace('_', '-').Replace('.', '-').ToLowerInvariant()),
        DeclarationHandle.Create(Prefix + name), H(title), StatementSource.FromAuthor(formula),
        literature ? AssessedProvenance.FromLiterature(Source) : AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text(prose))), role);

    private static Formula Parenthesized(Formula value) => Seq(Open, value, Close);
    private static Formula All(Formula variable, Formula type, Formula body) => Seq(Forall, Sp, Parenthesized(Seq(variable, Colon, Sp, type)), Comma, Sp, body);
    private static Formula Name(string name) {
        var parts = name.Split('.');
        Formula value = Word(parts[0]);
        for (var i = 1; i < parts.Length; i++) value = Seq(value, Dot, Word(parts[i]));
        return value;
    }
    private static Formula Word(string word) {
        if (word == "") return Sp;
        if (word == "0") return D(0);
        if (word == "1") return D(1);
        if (word == "2") return D(2);
        if (word.EndsWith("'", StringComparison.Ordinal)) return Seq(Word(word[..^1]), Apos);
        var parts = word.Split('_');
        Formula value = Seq(Operatorname, Grp(F.Id(parts[0])));
        for (var i = 1; i < parts.Length; i++) value = new Formula.Subscript(value, Seq(Operatorname, Grp(F.Id(parts[i]))));
        return value;
    }
}
