using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.QuantumChannels.RenyiSufficiency;

internal sealed class PositiveMapJordanDomainDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S3/QuantumChannels/RenyiSufficiency/PositiveMapJordanDomain.";
    private static readonly LibraryNoteRef Kadison = LibraryNoteRef.Create("D5/L/QuantumChannels/kadison1952schwarz");

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Positive matrix maps and the two-triangle obstruction to Rényi sufficiency.",
        H("PositiveMapJordanDomain"),
        Blocks(
            Node("positive-map-hermitian", "positive map hermitian", "positive_map_hermitian",
                Disp(All("m", Seq(Mathbb, Grp(F.Id("N"))), All("n", Seq(Mathbb, Grp(F.Id("N"))), All("Phi", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("m"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(Forall, Sp, F.Id("X"), Sp, Comma, Sp, Seq(F.Id("X"), Dot, Call("PosSemidef")), Sp, To, Sp, Parenthesized(Seq(F.Id("Phi"), Sp, F.Id("X"))), Sp, Seq(Dot, Call("PosSemidef"))), All("H", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(F.Id("H"), Dot, Call("IsHermitian")), Seq(Parenthesized(Seq(F.Id("Phi"), Sp, F.Id("H"))), Sp, Seq(Dot, Call("IsHermitian")))))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("kadison-finite-weights", "kadison finite weights", "kadison_finite_weights",
                Disp(All("m", Seq(Mathbb, Grp(F.Id("N"))), All("k", Call("Type"), Seq(OpenBracket, Seq(Call("Fintype"), Sp, F.Id("k")), CloseBracket, Comma, Sp, All("A", Seq(F.Id("k"), Sp, To, Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("m"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("lambda", Seq(F.Id("k"), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("R")))), Imp(Seq(Forall, Sp, F.Id("i"), Sp, Comma, Sp, Parenthesized(Seq(F.Id("A"), Sp, F.Id("i"))), Sp, Seq(Dot, Call("PosSemidef"))), Imp(Seq(Sum, Sp, F.Id("i"), Sp, Comma, Sp, F.Id("A"), Sp, F.Id("i"), Sp, Eq, Sp, D(1)), Seq(Parenthesized(Seq(Sum, Sp, F.Id("i"), Sp, Comma, Sp, Parenthesized(Seq(F.Id("lambda"), Sp, F.Id("i"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("C"))))), Sp, Cdot, Sp, F.Id("A"), Sp, F.Id("i"))), Sp, Times, Sp, Parenthesized(Seq(Sum, Sp, F.Id("i"), Sp, Comma, Sp, Parenthesized(Seq(F.Id("lambda"), Sp, F.Id("i"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("C"))))), Sp, Cdot, Sp, F.Id("A"), Sp, F.Id("i"))), Sp, Leq, Sp, Sum, Sp, F.Id("i"), Sp, Comma, Sp, Parenthesized(new Formula.Power(Parenthesized(Seq(F.Id("lambda"), Sp, F.Id("i"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("C"))))), D(2))), Sp, Cdot, Sp, F.Id("A"), Sp, F.Id("i")))))))))),
                "A sum of the positive matrices (lambda(i)I−K) A(i) (lambda(i)I−K), where K is the weighted sum, proves the finite-weight Kadison inequality.", DescribeRole.Theorem, AssessedProvenance.FromLiterature(Kadison)),
            Node("kadison-hermitian", "kadison hermitian", "kadison_hermitian",
                Disp(All("m", Seq(Mathbb, Grp(F.Id("N"))), All("n", Seq(Mathbb, Grp(F.Id("N"))), All("Phi", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("m"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(Forall, Sp, F.Id("X"), Sp, Comma, Sp, Seq(F.Id("X"), Dot, Call("PosSemidef")), Sp, To, Sp, Parenthesized(Seq(F.Id("Phi"), Sp, F.Id("X"))), Sp, Seq(Dot, Call("PosSemidef"))), Imp(Seq(F.Id("Phi"), Sp, D(1), Sp, Eq, Sp, D(1)), All("H", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(F.Id("H"), Dot, Call("IsHermitian")), Seq(F.Id("Phi"), Sp, F.Id("H"), Sp, Times, Sp, F.Id("Phi"), Sp, F.Id("H"), Sp, Leq, Sp, F.Id("Phi"), Sp, Parenthesized(Seq(F.Id("H"), Sp, Times, Sp, F.Id("H")))))))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Theorem, AssessedProvenance.FromLiterature(Kadison)),
            Node("jordan", "jordan", "jordan",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("A", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("B", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Seq(Call("jordan"), Sp, F.Id("A"), Sp, F.Id("B"), Sp, Eq, Sp, Parenthesized(Seq(F.Id("A"), Sp, Times, Sp, F.Id("B"), Sp, Plus, Sp, F.Id("B"), Sp, Times, Sp, F.Id("A")))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Definition, AssessedProvenance.FromRepo()),
            Node("hermitian-jordan-domain", "hermitian jordan domain", "hermitian_jordan_domain",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("E", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(Call("IsPositive"), Sp, F.Id("E")), Imp(Seq(F.Id("E"), Sp, D(1), Sp, Eq, Sp, D(1)), All("H", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("Y", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(F.Id("H"), Dot, Call("IsHermitian")), Imp(Seq(F.Id("Y"), Dot, Call("IsHermitian")), Imp(Seq(F.Id("E"), Sp, Parenthesized(Seq(F.Id("H"), Sp, Times, Sp, F.Id("H"))), Sp, Eq, Sp, F.Id("E"), Sp, F.Id("H"), Sp, Times, Sp, F.Id("E"), Sp, F.Id("H")), Seq(F.Id("E"), Sp, Parenthesized(Seq(Call("jordan"), Sp, F.Id("H"), Sp, F.Id("Y"))), Sp, Eq, Sp, Call("jordan"), Sp, Parenthesized(Seq(F.Id("E"), Sp, F.Id("H"))), Sp, Parenthesized(Seq(F.Id("E"), Sp, F.Id("Y")))))))))))))),
                "Kadison equality for H makes the linear coefficient of the quadratic positivity inequality vanish, giving the Jordan identity with every Hermitian Y.", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("jordan-smul-right", "jordan smul right", "jordan_smul_right",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("c", Seq(Mathbb, Grp(F.Id("C"))), All("A", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("B", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Seq(Call("jordan"), Sp, F.Id("A"), Sp, Parenthesized(Seq(F.Id("c"), Sp, Cdot, Sp, F.Id("B"))), Sp, Eq, Sp, F.Id("c"), Sp, Cdot, Sp, Call("jordan"), Sp, F.Id("A"), Sp, F.Id("B"))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("jordan-smul-left", "jordan smul left", "jordan_smul_left",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("c", Seq(Mathbb, Grp(F.Id("C"))), All("A", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("B", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Seq(Call("jordan"), Sp, Parenthesized(Seq(F.Id("c"), Sp, Cdot, Sp, F.Id("A"))), Sp, F.Id("B"), Sp, Eq, Sp, F.Id("c"), Sp, Cdot, Sp, Call("jordan"), Sp, F.Id("A"), Sp, F.Id("B"))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("jordanmd", "JordanMD", "JordanMD",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("E", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("A", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Seq(Call("JordanMD"), Sp, F.Id("E"), Sp, F.Id("A"), Sp, Eq, Sp, Parenthesized(Seq(Forall, Sp, Parenthesized(Seq(F.Id("B"), Sp, Colon, Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))))), Sp, Comma, Sp, F.Id("E"), Sp, Parenthesized(Seq(Call("jordan"), Sp, F.Id("A"), Sp, F.Id("B"))), Sp, Eq, Sp, Call("jordan"), Sp, Parenthesized(Seq(F.Id("E"), Sp, F.Id("A"))), Sp, Parenthesized(Seq(F.Id("E"), Sp, F.Id("B")))))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Definition, AssessedProvenance.FromRepo()),
            Node("positive-map-star", "positive map star", "positive_map_star",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("E", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(Call("IsPositive"), Sp, F.Id("E")), All("A", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Seq(F.Id("E"), Sp, Parenthesized(Apply(Call("conjTranspose"), F.Id("A"))), Sp, Eq, Sp, Apply(Call("conjTranspose"), Parenthesized(Seq(F.Id("E"), Sp, F.Id("A")))))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("fixed-jordan-domain", "fixed jordan domain", "fixed_jordan_domain",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("E", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(Call("IsPositive"), Sp, F.Id("E")), Imp(Seq(F.Id("E"), Sp, D(1), Sp, Eq, Sp, D(1)), All("S", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("A", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(F.Id("S"), Dot, Call("PosDef")), Imp(Seq(Forall, Sp, F.Id("Y"), Sp, Comma, Sp, Parenthesized(Seq(F.Id("S"), Sp, Times, Sp, F.Id("E"), Sp, F.Id("Y"))), Sp, Seq(Dot, Call("trace")), Sp, Eq, Sp, Parenthesized(Seq(F.Id("S"), Sp, Times, Sp, F.Id("Y"))), Sp, Seq(Dot, Call("trace"))), Imp(Seq(F.Id("E"), Sp, F.Id("A"), Sp, Eq, Sp, F.Id("A")), Seq(Call("JordanMD"), Sp, F.Id("E"), Sp, F.Id("A")))))))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("fixed-jordan", "fixed jordan", "fixed_jordan",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("E", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(Call("IsPositive"), Sp, F.Id("E")), Imp(Seq(F.Id("E"), Sp, D(1), Sp, Eq, Sp, D(1)), All("S", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("A", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("B", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(F.Id("S"), Dot, Call("PosDef")), Imp(Seq(Forall, Sp, F.Id("Y"), Sp, Comma, Sp, Parenthesized(Seq(F.Id("S"), Sp, Times, Sp, F.Id("E"), Sp, F.Id("Y"))), Sp, Seq(Dot, Call("trace")), Sp, Eq, Sp, Parenthesized(Seq(F.Id("S"), Sp, Times, Sp, F.Id("Y"))), Sp, Seq(Dot, Call("trace"))), Imp(Seq(F.Id("E"), Sp, F.Id("A"), Sp, Eq, Sp, F.Id("A")), Imp(Seq(F.Id("E"), Sp, F.Id("B"), Sp, Eq, Sp, F.Id("B")), Seq(F.Id("E"), Sp, Parenthesized(Seq(Call("jordan"), Sp, F.Id("A"), Sp, F.Id("B"))), Sp, Eq, Sp, Call("jordan"), Sp, F.Id("A"), Sp, F.Id("B")))))))))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("arbitrary-square-extension", "arbitrary square extension", "arbitrary_square_extension",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("E", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("D", Seq(Call("Submodule"), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Parenthesized(Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))))), Imp(Seq(Forall, Sp, F.Id("A"), Sp, InMacro, Sp, F.Id("D"), Sp, Comma, Sp, Apply(Call("conjTranspose"), F.Id("A")), Sp, InMacro, Sp, F.Id("D")), Imp(Seq(Forall, Sp, F.Id("A"), Sp, InMacro, Sp, F.Id("D"), Sp, Comma, Sp, Seq(F.Id("A"), Dot, Call("IsHermitian")), Sp, To, Sp, F.Id("E"), Sp, Parenthesized(Seq(F.Id("A"), Sp, Times, Sp, F.Id("A"))), Sp, Eq, Sp, F.Id("E"), Sp, F.Id("A"), Sp, Times, Sp, F.Id("E"), Sp, F.Id("A")), All("A", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(F.Id("A"), Sp, InMacro, Sp, F.Id("D")), Seq(F.Id("E"), Sp, Parenthesized(Seq(F.Id("A"), Sp, Times, Sp, F.Id("A"))), Sp, Eq, Sp, F.Id("E"), Sp, F.Id("A"), Sp, Times, Sp, F.Id("E"), Sp, F.Id("A")))))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("positive-inverse-square-preserving", "positive inverse square preserving", "positive_inverse_square_preserving",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("Phi", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("Psi", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(Call("IsPositive"), Sp, F.Id("Phi")), Imp(Seq(Call("IsPositive"), Sp, F.Id("Psi")), Imp(Seq(F.Id("Phi"), Sp, D(1), Sp, Eq, Sp, D(1)), Imp(Seq(F.Id("Psi"), Sp, D(1), Sp, Eq, Sp, D(1)), Imp(Seq(Seq(F.Id("Psi"), Dot, Call("comp")), Sp, F.Id("Phi"), Sp, Eq, Sp, Seq(Call("LinearMap"), Dot, Call("id"))), All("H", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(F.Id("H"), Dot, Call("IsHermitian")), Seq(F.Id("Phi"), Sp, Parenthesized(Seq(F.Id("H"), Sp, Times, Sp, F.Id("H"))), Sp, Eq, Sp, F.Id("Phi"), Sp, F.Id("H"), Sp, Times, Sp, F.Id("Phi"), Sp, F.Id("H"))))))))))))),
                "Kadison applied to each member of the positive inverse pair gives opposing inequalities, and their equality preserves Hermitian squares.", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("positive-inverse-complex-jordan", "positive inverse complex jordan", "positive_inverse_complex_jordan",
                Disp(All("n", Seq(Mathbb, Grp(F.Id("N"))), All("Phi", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("Psi", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C"))), Sp, Seq(new Formula.Subscript(To, F.Id("l")), OpenBracket, Seq(Mathbb, Grp(F.Id("C"))), CloseBracket), Sp, Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Imp(Seq(Call("IsPositive"), Sp, F.Id("Phi")), Imp(Seq(Call("IsPositive"), Sp, F.Id("Psi")), Imp(Seq(F.Id("Phi"), Sp, D(1), Sp, Eq, Sp, D(1)), Imp(Seq(F.Id("Psi"), Sp, D(1), Sp, Eq, Sp, D(1)), Imp(Seq(Seq(F.Id("Psi"), Dot, Call("comp")), Sp, F.Id("Phi"), Sp, Eq, Sp, Seq(Call("LinearMap"), Dot, Call("id"))), All("A", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), All("B", Seq(Call("Matrix"), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Parenthesized(Seq(Call("Fin"), Sp, F.Id("n"))), Sp, Seq(Mathbb, Grp(F.Id("C")))), Seq(F.Id("Phi"), Sp, Parenthesized(Seq(Call("jordan"), Sp, F.Id("A"), Sp, F.Id("B"))), Sp, Eq, Sp, Call("jordan"), Sp, Parenthesized(Seq(F.Id("Phi"), Sp, F.Id("A"))), Sp, Parenthesized(Seq(F.Id("Phi"), Sp, F.Id("B"))))))))))))))),
                "The complete parameter telescope and conclusion are displayed. Matrix products, transpose and conjTranspose have their Mathlib meanings; arrows indexed by Complex denote LinearMap.", DescribeRole.Theorem, AssessedProvenance.FromRepo()))));

    private static DocumentBlock Node(string id, string title, string declaration,
        Formula formula, string prose, DescribeRole role, AssessedProvenance provenance) =>
        Describe.Lean(DescribeId.Create(id), DeclarationHandle.Create(Prefix + declaration),
            H(title), StatementSource.FromAuthor(formula), provenance,
            Blocks(Paragraph(Text(prose))), role);
    private static Formula Call(string name, params Formula[] args) =>
        args.Length == 0 ? Seq(Operatorname, Grp(F.Id(name)))
            : new Formula.FunctionCall(FormulaIdentifier.Create(name), [.. args]);
    private static Formula Apply(Formula name, params Formula[] args) => new Formula.Apply(name, [.. args]);
    private static Formula Parenthesized(Formula value) => Seq(Open, value, Close);
    private static Formula All(string name, Formula type, Formula body) =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id(name), Colon, Sp, type)), Comma, Sp, body);
    private static Formula Imp(Formula premise, Formula body) =>
        Seq(Parenthesized(premise), Sp, Rightarrow, Sp, body);
}
