using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.StatisticalMechanics.HardCore;

internal sealed class GibbsOccupationDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Actual occupation, normalized Gibbs probabilities and analytic response.",
        H("GibbsOccupation"),
        Blocks(
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-gibbs-mass"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.gibbsMass"),
                H("gibbsMass"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Actual normalized Gibbs mass. Configurations outside the finite independent family have zero mass. Its probability properties are proved for lambda >= 0."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-gibbs-mass-nonneg"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.gibbs_mass_nonneg"),
                H("gibbs mass nonneg"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("All actual masses are nonnegative, including the zero-activity endpoint."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-mass-moment-eq"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.mass_moment_eq"),
                H("mass moment eq"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Exact normalized raw moments, before imposing positivity or a probability interpretation. The normalization denominator is the actual partition."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-gibbs-mass-sum"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.gibbs_mass_sum"),
                H("gibbs mass sum"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The complete family of actual configurations has total probability one."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-gibbs-pmf"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.gibbsPMF"),
                H("gibbsPMF"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The Gibbs law is a standard Mathlib PMF on actual finite vertex sets. The ambient graph need not be finite. No external probability oracle is used."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-gibbs-pmf-to-real"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.gibbs_pmf_toReal"),
                H("gibbs pmf toReal"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The real-valued point masses of the actual PMF equal the normalized weights."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-mean-occupation"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.meanOccupation"),
                H("meanOccupation"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Mean particle number, subsequently identified with the actual PMF sum."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-gibbs-expected-card"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.gibbs_expected_card"),
                H("gibbs expected card"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The finite expectation of configuration cardinality under the actual PMF is exactly the first normalized occupation moment."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-gibbs-vertex-occupied"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.gibbs_vertex_occupied"),
                H("gibbs vertex occupied"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual probability that a marked vertex is occupied equals one minus the actual vacancy ratio. A vertex outside V has occupancy zero automatically."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-mean-eq-sum-vacancies"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.mean_eq_sum_vacancies"),
                H("mean eq sum vacancies"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Expected occupation is the sum of actual one-vertex occupancies. No independence among these Bernoulli indicators is assumed."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-mean-occupation-bounds"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.mean_occupation_bounds"),
                H("mean occupation bounds"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The mean lies between zero and the actual number of available vertices."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-occupation-variance"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.occupationVariance"),
                H("occupationVariance"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Centered second moment under the same actual Gibbs weights."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-gibbs-variance"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.gibbs_variance"),
                H("gibbs variance"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The centered second moment equals the conventional finite PMF variance."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-variance-eq-moments"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.variance_eq_moments"),
                H("variance eq moments"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Expansion of the actual centered variance into its first two raw moments."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-occupation-variance-nonneg"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.occupation_variance_nonneg"),
                H("occupation variance nonneg"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Nonnegativity is proved from squared centered deviations and actual nonnegative masses, not postulated from the derivative formula."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-mean-occupation-fluctuation-response"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.mean_occupation_fluctuation_response"),
                H("mean occupation fluctuation response"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Exact fluctuation-response identity. The factor lambda preserves the zero-activity endpoint and expresses differentiation in log activity."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-mean-occupation-deriv-nonneg"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.mean_occupation_deriv_nonneg"),
                H("mean occupation deriv nonneg"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For positive activity the expected particle number has nonnegative ordinary derivative, as a consequence of the proved fluctuation identity."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-gibbsoccupation-zero-activity-moments"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/GibbsOccupation.zero_activity_moments"),
                H("zero activity moments"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The zero-activity mean and variance are both zero, with the empty configuration still carrying unit mass. No limiting argument is needed."))), DescribeRole.Theorem))));
}
