using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.StatisticalMechanics.HardCore;

internal sealed class OccupationMomentsDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Actual occupation, normalized Gibbs probabilities and analytic response.",
        H("OccupationMoments"),
        Blocks(
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-configurations-erase-eq-filter"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.configurations_erase_eq_filter"),
                H("configurations erase eq filter"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Actual configurations omitting a vertex are exactly those on the erased vertex domain. The marked vertex need not belong to the domain."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-occupied-weight-add-erased"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.occupied_weight_add_erased"),
                H("occupied weight add erased"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Partition the full configuration weight by actual root occupancy, before any division. This semiring identity also holds at zeros of a partition."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-weighted-cardinality-eq-marked-sum"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.weighted_cardinality_eq_marked_sum"),
                H("weighted cardinality eq marked sum"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Count each weighted independent configuration once per occupied vertex. This is an exact finite double-counting identity; no independence of vertex indicators is assumed."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-weighted-cardinality-eq-partition-differences"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.weighted_cardinality_eq_partition_differences"),
                H("weighted cardinality eq partition differences"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The first weighted cardinality sum equals the sum of actual deletion partition differences. The identity is over every commutative ring."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-moment"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.moment"),
                H("moment"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Unnormalized occupation moment on the original configuration family. Order zero is the existing partition; no replacement graph model is introduced."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-moment-zero-order"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.moment_zero_order"),
                H("moment zero order"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The zeroth moment is exactly the existing constant-activity partition."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-moment-one-eq-deletions"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.moment_one_eq_deletions"),
                H("moment one eq deletions"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The first moment has a local-deletion expression at every activity, including activity zero and partition zeros."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-moment-succ-at-zero"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.moment_succ_at_zero"),
                H("moment succ at zero"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Every positive-order occupation moment vanishes at zero activity."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-moment-has-deriv-at"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.moment_hasDerivAt"),
                H("moment hasDerivAt"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Direct termwise differentiation of the actual finite configuration sum. The natural predecessor in the exponent is harmless at the empty configuration."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-euler-moment"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.euler_moment"),
                H("euler moment"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Euler differentiation raises the occupation moment order. No division by activity or nonzero-activity assumption occurs, for any order k."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-partition-euler-occupation"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.partition_euler_occupation"),
                H("partition euler occupation"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The targeted observable identity for every finite domain of every simple graph. It holds over the real or complex numbers even at a partition zero."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-occupation-occupationmoments-normalized-moment-response"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/OccupationMoments.normalized_moment_response"),
                H("normalized moment response"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Normalized moments satisfy a covariance-type response hierarchy wherever the actual partition is nonzero. Activity zero is retained in this formula."))), DescribeRole.Theorem))));
}
