using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S0.Certificates;

internal sealed class FiniteDomainSelectionRefutationDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S0/Certificates/FiniteDomainSelectionRefutation.";

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Support pruning and complete finite branching preserve all shared table-selection solutions and soundly certify their absence at arbitrary finite color capacity.",
        H("Finite Domain Selection Refutation"),
        Blocks(
            Describe.Lean(DescribeId.Create("selection-refutation-assignment"), DeclarationHandle.Create(Prefix + "Assignment"), H("Assignment"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A finite assignment into an arbitrary finite color carrier."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-domains"), DeclarationHandle.Create(Prefix + "Domains"), H("Domains"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Allowed values for every transition-table or trace variable at the chosen finite color capacity."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-in-domains"), DeclarationHandle.Create(Prefix + "InDomains"), H("InDomains"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("All coordinates of an assignment remain inside the current domains."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-selection"), DeclarationHandle.Create(Prefix + "Selection"), H("Selection"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A shared transition table is selected by the finite color of the parent node."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-selection-holds"), DeclarationHandle.Create(Prefix + "Selection.Holds"), H("Selection.Holds"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The exact deterministic local equation."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-solves"), DeclarationHandle.Create(Prefix + "Solves"), H("Solves"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("An assignment solves every supplied local equation."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-restrict"), DeclarationHandle.Create(Prefix + "restrict"), H("restrict"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Intersect one domain, leaving the other coordinates unchanged."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-restrict-preserves"), DeclarationHandle.Create(Prefix + "restrict_preserves"), H("restrict_preserves"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Restriction is sound whenever the actual value is among the allowed ones."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("selection-refutation-prune-parent"), DeclarationHandle.Create(Prefix + "pruneParent"), H("pruneParent"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Remove parent values lacking any compatible transition target."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-prune-child"), DeclarationHandle.Create(Prefix + "pruneChild"), H("pruneChild"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Remove child values lacking a compatible parent and table entry."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-prune-row"), DeclarationHandle.Create(Prefix + "pruneRow"), H("pruneRow"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("When the parent has one value, intersect that table row with the child."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-prune-parent-preserves"), DeclarationHandle.Create(Prefix + "pruneParent_preserves"), H("pruneParent_preserves"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Removing an unsupported parent never removes a satisfying assignment."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("selection-refutation-prune-child-preserves"), DeclarationHandle.Create(Prefix + "pruneChild_preserves"), H("pruneChild_preserves"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Removing an unsupported child never removes a satisfying assignment."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("selection-refutation-prune-row-preserves"), DeclarationHandle.Create(Prefix + "pruneRow_preserves"), H("pruneRow_preserves"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A singleton-parent table-row intersection is also solution preserving."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("selection-refutation-instruction"), DeclarationHandle.Create(Prefix + "Instruction"), H("Instruction"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A pruning instruction names an existing constraint, never a new premise."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-apply-instruction"), DeclarationHandle.Create(Prefix + "applyInstruction"), H("applyInstruction"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Executable semantics of one support-pruning instruction."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-instruction-preserves"), DeclarationHandle.Create(Prefix + "instruction_preserves"), H("instruction_preserves"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Every permitted instruction preserves every genuine solution."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("selection-refutation-apply-schedule"), DeclarationHandle.Create(Prefix + "applySchedule"), H("applySchedule"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Replay an arbitrary finite pruning schedule. A fixed-point hypothesis is unnecessary for soundness, so scheduling and early stopping remain untrusted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-schedule-preserves"), DeclarationHandle.Create(Prefix + "schedule_preserves"), H("schedule_preserves"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Soundness is independent of the choice and order of pruning instructions."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("selection-refutation-refutation"), DeclarationHandle.Create(Prefix + "Refutation"), H("Refutation"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Finite proof trees retain one child for every finite color. A child is skipped only when its value is absent from the current domain."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-check"), DeclarationHandle.Create(Prefix + "check"), H("check"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The checker accepts only an empty-domain leaf or every feasible color branch. It does not accept an external UNSAT flag as a premise."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selection-refutation-accepted-refutation-excludes-solution"), DeclarationHandle.Create(Prefix + "accepted_refutation_excludes_solution"), H("accepted_refutation_excludes_solution"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Accepted finite refutations exclude every assignment satisfying both the original domains and all shared transition equations at any finite color capacity."))), DescribeRole.Theorem)),
        []));
}
