import LeanInformationAudit.Syntax
import D5.S3.ConceptDynamics.InformationEscape.AgohCoefficientReadoutTemplate

section
open _root_.D5.S3.ConceptDynamics
open _root_.D5.S3.ConceptDynamics.InformationEscape
set_option autoImplicit false
set_option relaxedAutoImplicit false
open LeanInformationAudit
open _root_.D5.S3.ConceptDynamics.InformationEscape.AgohCoefficientReadoutTemplate
register_information_template coefficientRealization
end
