import LeanInformationAudit.Syntax
import D5.S3.ArithUnits.CenteredReducedResidueProgressions

section
open _root_.D5.S3.ConceptDynamics
open _root_.D5.S3.ConceptDynamics.InformationEscape
set_option autoImplicit false
set_option relaxedAutoImplicit false
open _root_.D5.S3.ArithUnits.CenteredReducedResidueProgressions
open _root_.D5.S3.ConceptDynamics.InformationEscape
open _root_.D5.S3.ConceptDynamics.InformationEscape.RegistrationTemplates
open LeanInformationAudit
set_option backward.isDefEq.respectTransparency.types false
register_information_template sourceCorrectionRealization
end
