import LeanInformationAudit.Syntax
import D5.S3.ConceptDynamics.InformationEscape.CounterexampleRecord

section
open _root_.D5.S3.ConceptDynamics
open _root_.D5.S3.ConceptDynamics.InformationEscape
set_option autoImplicit false
set_option relaxedAutoImplicit false
open _root_.D5.S3.ConceptDynamics.InformationEscape.CounterexampleRecord
open RegistrationTemplates LeanInformationAudit
universe u
register_information_template counterexampleRealization
end
