import LeanInformationAudit.Syntax
import D5.S3.ConceptDynamics.InformationEscape.HughesIterationDepthNoGapRegistration

section
open _root_.D5.S3.ConceptDynamics
open _root_.D5.S3.ConceptDynamics.InformationEscape
set_option autoImplicit false
set_option relaxedAutoImplicit false
open _root_.D5.S3.ConceptDynamics.InformationEscape.HughesIterationDepthNoGapRegistration
open _root_.D5.S1.Words.HughesIterationDepthNoGap
open LeanInformationAudit
open RegistrationTemplates
register_information_template depthOriginTemplate
end
