import LeanInformationAuditInterface.Syntax
import D5.S3.ConceptDynamics.InformationEscape.ObjectDomainArena
import D5.S3.ConceptDynamics.InformationEscape.TheoremUnit
import D5.S3.ConceptDynamics.RegistrationWitnesses
import D5.S3.ConceptDynamics.InformationEscape.MechanicalDyadicRegistration

open D5.S3.ConceptDynamics.InformationEscape.MechanicalDyadicRegistration

register_information_template mechanicalReadoutRealization
