using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.PrimeGaps;

internal sealed class FragmentMeshTruncationDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Truncating small weighted fragments changes a floor readout only through a large deletion or a retained-mass boundary strip.",
        H("Fragment Truncation Through a Mass Mesh"), Blocks(
            Describe.Lean(DescribeId.Create("retained-fragment-measure"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentMeshTruncation.retainedFragments"), H("Retained fragment measure"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Restrict the actual finite fragment measure to the complement of the positive deletion interval. The entire retained measure remains the state used by the mass readout."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("deleted-fragment-mass"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentMeshTruncation.deletedFragmentMass"), H("Deleted weighted mass"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Read the finite mass in the deletion interval as a real number. Nonnegativity follows from the finite-measure value."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("retained-deleted-partition"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentMeshTruncation.retained_deleted_mass"), H("Retained and deleted masses partition the original mass"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The deletion interval and its complement are a measurable partition. Finite-measure coercions transport the measure identity to real masses."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("deleted-real-mass-tail"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentMeshTruncation.deletedFragmentMass_tail"), H("Tail bound for the real-valued deletion"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The existing small-fragment tail theorem is reused after proving equality of the real threshold event and its extended-nonnegative-real formulation."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("mesh-crossing-alternative"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentMeshTruncation.floor_mesh_crossing_alternative"), H("A crossed mesh boundary yields an explicit alternative"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A nonnegative increment makes the natural floor index monotone. If the index changes, the new mass reaches the next boundary. An increment smaller than the chosen threshold therefore requires the original mass to lie within that threshold of the boundary."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("fragment-mesh-error-probability"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentMeshTruncation.fragment_mesh_change_probability"), H("The actual mesh error splits into a tail and a boundary probability"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Apply the deterministic alternative to the retained and deleted masses, then use event inclusion and the union bound. The boundary-strip probability stays explicitly in the conclusion. No density bound, anti-concentration estimate or numerical integral enclosure is assumed to have been proved."))), DescribeRole.Theorem)
        )));
}
