using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.PrimeGaps;

internal sealed class FragmentLawDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "A provenance-preserving port constructs the actual weighted Poisson fragment law and proves its first moment and small-fragment tail.",
        H("Weighted Poisson Fragment Law"), Blocks(
            Paragraph(Text("The Lean source is adapted from openai/PrimeGaps186, commit 61340d0b74163003b32756bb16e91d9209a5e330, under its Apache-2.0 provenance. The first-moment construction is an upstream proof port. It does not certify any of the original numerical integral cells.")),
            Describe.Lean(DescribeId.Create("weighted-empirical-measure"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.weightedEmpirical"), H("Location-weighted empirical measure"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Each sampled location contributes its nonnegative part as the weight of a Dirac atom."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("finite-poisson-law"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.finitePoissonLaw"), H("Poisson counts and sampled locations"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A Poisson count and independent normalized locations are pushed forward to a finite weighted measure."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("capped-dyadic-intensity"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.cappedDyadicIntensity"), H("Finite dyadic intensity"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Restrict the reciprocal-location density to one dyadic interval and to the positive cutoff interval. Each band has finite intensity."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("finite-fragment-sum"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.finiteFragments"), H("Finite realization of the band sum"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The total measure is used when finite; the definition has a zero fallback. A subsequent theorem proves that fallback is almost surely unused."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("fragment-law"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.fragmentLaw"), H("Law of the complete fragment measure"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Push forward the independent band laws through the finite-fragment map."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("empirical-measure-coercion"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.coe_weightedEmpirical"), H("Underlying measure of the empirical sum"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The finite-measure construction agrees exactly with the corresponding weighted Dirac sum."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("empirical-measurability"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.measurable_weightedEmpirical"), H("Measurability at fixed sample size"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Measurability is proved by evaluating the underlying measure on measurable sets."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("random-size-empirical-measurability"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.measurable_weightedEmpirical_sample"), H("Measurability with random sample size"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The variable-size sample map is measurable on the countable count coordinate and infinite location sequence."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("mass-times-normalization"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.coe_eq_mass_smul_normalize"), H("Recover a measure from its normalization"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The existing finite-measure normalization identity is transported to the underlying measure."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("poisson-mixture-integral"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.lintegral_finitePoissonLaw_normalized"), H("Integrate over count and locations"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A measurable nonnegative observable of the Poisson measure is integrated by first conditioning on the count and then using its finite product law."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("empirical-first-moment"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.lintegral_weightedEmpirical_pi"), H("Fixed-count first moment"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Linearity and identical coordinate marginals give the count times the one-location weighted integral."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("poisson-successor-recurrence"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.poisson_singleton_succ"), H("Poisson mass recurrence"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The successor factorial identity supplies the exact recurrence used to sum the Poisson expectation."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("poisson-count-expectation"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.lintegral_poisson_id"), H("Expected Poisson count"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The nonnegative integral of the count equals its intensity parameter."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weighted-poisson-first-moment"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.lintegral_weighted_finitePoissonLaw"), H("First moment of a finite Poisson band"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Combining normalized sampling with the Poisson expectation recovers the location-weighted intensity integral."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-poisson-probability"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.finitePoissonLaw_isProbabilityMeasure"), H("Each band law is a probability measure"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The measurable pushforward of the product probability law has total mass one."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("band-sum-measurability"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.measurable_fragment_sum"), H("Measurability of the countable measure sum"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Evaluating the sum on a measurable set is a measurable countable sum."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-fragments-measurability"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.measurable_finiteFragments"), H("Measurability of the finite realization"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The finite-measure branch and zero fallback combine over a measurable finiteness predicate."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("dyadic-bands-disjoint"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.dyadic_bands_disjoint"), H("Dyadic bands are pairwise disjoint"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The half-open convention assigns each positive boundary to exactly one band."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("dyadic-bands-cover"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.iUnion_dyadic_bands"), H("Dyadic bands cover the positive line"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Every strictly positive location lies in a dyadic band indexed by an integer."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("recover-capped-intensity"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.sum_cappedDyadicIntensity"), H("Reassemble the original intensity"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The disjoint restrictions sum to the reciprocal-location intensity on the cutoff interval."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("countable-fragment-first-moment"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.lintegral_fragment_sum"), H("First moment before imposing finiteness"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Nonnegative integration exchanges the band sum and expectation. Multiplication by the location cancels the reciprocal-location density."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("almost-sure-finite-fragment-mass"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.ae_isFiniteMeasure_fragment_sum"), H("The total fragment mass is almost surely finite"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The first moment of total mass is finite, so the countable measure sum is finite almost surely. The conclusion is proved before using the finite-measure fallback."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("fragment-law-probability"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.fragmentLaw_isProbabilityMeasure"), H("The fragment law is a probability measure"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The completed measurable pushforward is a probability measure for every real cutoff."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("fragment-law-first-moment"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.lintegral_fragmentLaw"), H("First moment on the actual fragment law"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("For every measurable nonnegative test, the expected fragment integral equals its Lebesgue integral over the cutoff interval."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("small-fragment-mass-tail"), DeclarationHandle.Create("D5/S3/PrimeGaps/FragmentLaw.fragmentLaw_small_seed_tail"), H("Tail probability of deleted small-fragment mass"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("For a positive cutoff and threshold and a nonnegative deletion scale, Markov's inequality bounds the deletion event by the minimum of the two cutoffs divided by the threshold. This leaves discontinuous mesh-boundary effects for the next module."))), DescribeRole.Theorem)
        )));
}
