namespace StrataLint.Lean.Tests;

public sealed class InspectorNativeRecoveryTests(InspectorCompilerFixture compiler) : IClassFixture<InspectorCompilerFixture>
{
    // Invalidation and recovery use a separate, class-owned compiler stage.
    [Theory]
    [InlineData("test_native.NativeTests.test_release_stage_and_verify_preserve_absent_lake")]
    [InlineData("test_native.NativeTests.test_native_no_build_rejects_corruption_without_production")]
    [InlineData("test_native.NativeTests.test_public_module_validates_and_private_job_is_not_a_target")]
    [InlineData("test_native.NativeTests.test_native_invalidation")]
    [InlineData("test_native.NativeTests.test_native_config_options_rebuild_and_fail_closed")]
    [InlineData("test_native.NativeTests.test_reported_module_proof_axioms_invalidate_public_trace")]
    [InlineData("test_native.NativeTests.test_private_transitive_definition_invalidates_utility")]
    [InlineData("test_native.NativeTests.test_exported_transitive_dependency_binding")]
    [InlineData("test_native.NativeTests.test_exported_private_dependency_and_missing_binding")]
    [InlineData("test_native.NativeTests.test_native_fetched_git_sources_bind_and_invalidate")]
    [InlineData("test_native.NativeTests.test_fetched_snapshot_rejects_dirty_git_and_invalid_resolver")]
    [InlineData("test_native.NativeTests.test_fetched_private_transitive_semantics_and_selective_reconstruction")]
    [InlineData("test_native.NativeTests.test_fetched_inventory_paths_ownership_and_publication_race")]
    [InlineData("test_native.NativeTests.test_fetched_package_absence_reuses_only_wholly_unmaterialized_snapshot")]
    [InlineData("test_native.NativeTests.test_fetched_default_only_failure_and_metadata_reuse")]
    [InlineData("test_native.NativeTests.test_fetched_entry_retains_preensure_root_capture")]
    [InlineData("test_native.NativeTests.test_fetched_fixed_judge_and_utility_claim_closures")]
    [InlineData("test_native.NativeTests.test_fetched_git_capture_cannot_mix_commits")]
    [InlineData("test_native.NativeTests.test_fetched_workspace_override_reaches_native_error_and_restores")]
    [InlineData("test_native.NativeTests.test_fetched_package_alias_retarget_is_rejected_on_fresh_and_reused_entry")]
    [InlineData("test_native.NativeTests.test_fetched_optional_json_shapes_reconstruct_through_entry")]
    [InlineData("test_native.NativeTests.test_fetched_missing_descriptor_with_materialization_requires_lake")]
    [InlineData("test_native.NativeTests.test_fetched_missing_descriptor_with_unlisted_checkout_requires_lake")]
    [InlineData("test_native.NativeTests.test_fetched_missing_descriptor_uses_configured_store")]
    [InlineData("test_native.NativeTests.test_fetched_store_absence_and_unlisted_partial_materializations")]
    [InlineData("test_native.NativeTests.test_fetched_store_aliases_and_obstructions_reject_through_entry")]
    [InlineData("test_native.NativeTests.test_fetched_store_descriptor_damage_reconstructs")]
    [InlineData("test_native.NativeTests.test_fetched_modes_aliases_and_owner_evidence_through_entry")]
    [InlineData("test_native.NativeTests.test_native_recovery_and_required_failures")]
    [InlineData("test_native.NativeTests.test_native_recovers_only_row_with_damaged_deflate")]
    [InlineData("test_native.NativeTests.test_native_recovers_only_row_with_damaged_lzma")]
    [InlineData("test_native.NativeTests.test_native_recovers_outer_member_without_lzma")]
    [InlineData("test_native.NativeTests.test_native_recovers_nested_material_without_lzma")]
    [InlineData("test_native.NativeTests.test_native_optional_lzma_and_batch_failure_boundaries")]
    [InlineData("test_native.NativeTests.test_native_recovers_only_row_with_unsupported_compression")]
    [InlineData("test_native.NativeTests.test_native_recovers_only_row_with_encrypted_member")]
    [InlineData("test_native.NativeTests.test_native_recovers_only_row_with_encrypted_material")]
    [InlineData("test_native.NativeTests.test_native_recovers_encrypted_report")]
    public void InspectorArtifactBehavior(string suite) => InspectorNativeTestRunner.Run(compiler, suite);
}
