using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Weil.ZetaBridge;

internal sealed class WeilObserverStructuralKernelsDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S3/Weil/ZetaBridge/WeilObserverStructuralKernels.";
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Selected odd channels give faithful inclusion-reversing equality kernels on actual Weil tests. Localization preserves those readouts, including comparisons across different depths.",
        H("Structural Kernels of Weil Observations"),
        Blocks(
            Describe.Lean(DescribeId.Create("weil-frame-kernel-definition"),
                DeclarationHandle.Create(Prefix + "frameObserverKernel"),
                H("The equality relation of selected channels"),
                StatementSource.FromAuthor(Disp(F.Id("K_S(g,h) iff q_i(g)=q_i(h) for every i in S."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The state space is the original infinite WeilTestFunction type. Only a finite set of readouts is selected."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("weil-frame-kernel-equivalence"),
                DeclarationHandle.Create(Prefix + "frameObserverKernel_equivalence"),
                H("Equivalence relation"),
                StatementSource.FromAuthor(Disp(F.Id("K_S is reflexive, symmetric and transitive."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Each property follows pointwise from equality of the selected readouts."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-frame-kernel-interpolation"),
                DeclarationHandle.Create(Prefix + "frameObserverKernel_synthesis_iff"),
                H("Exact pullback under interpolation"),
                StatementSource.FromAuthor(Disp(F.Id("K_S(synthesis(a),synthesis(b)) iff a_i=b_i for all i in S."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Apply the existing interpolation right-inverse theorem at each channel."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-frame-exclusive-pair"),
                DeclarationHandle.Create(Prefix + "frameObserver_leave_one_out_witness"),
                H("Exclusive test pair for each channel"),
                StatementSource.FromAuthor(Disp(F.Id("There are g,h agreeing at all j distinct from i and differing at i."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Synthesize the Kronecker coefficient vector and the zero coefficient vector. These are actual admissible tests."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-frame-kernel-refinement"),
                DeclarationHandle.Create(Prefix + "frameObserverKernel_refines_iff"),
                H("Exact reversal of channel inclusion"),
                StatementSource.FromAuthor(Disp(F.Id("K_T is contained in K_S iff S is contained in T."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The forward implication uses the exclusive pair of any purported missing channel. The reverse implication restricts the observations."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-frame-kernel-faithfulness"),
                DeclarationHandle.Create(Prefix + "frameObserverKernel_eq_iff"),
                H("Faithfulness of channel subsets"),
                StatementSource.FromAuthor(Disp(F.Id("K_S=K_T iff S=T."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Apply the inclusion theorem in both directions and finite-set antisymmetry."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-frame-kernel-union"),
                DeclarationHandle.Create(Prefix + "frameObserverKernel_union"),
                H("Joint observations"),
                StatementSource.FromAuthor(Disp(F.Id("K_(S union T)(g,h) iff K_S(g,h) and K_T(g,h)."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Membership in the union separates the universal readout constraint into its two components."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-frame-kernel-strict-erasure"),
                DeclarationHandle.Create(Prefix + "frameObserverKernel_strict_leave_one_out"),
                H("Strict enlargement after channel removal"),
                StatementSource.FromAuthor(Disp(F.Id("K_univ is contained in K_(univ erase i), with an explicit pair in the latter only."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The exclusive test pair witnesses strictness. This assertion concerns the specified channel family and does not assert positive gain for every theorem occurrence in a maximal catalog."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-frame-kernel-burnol"),
                DeclarationHandle.Create(Prefix + "frameObserverKernel_burnol_iff"),
                H("Localized pullback"),
                StatementSource.FromAuthor(Disp(F.Id("K_S(f_(N,a),f_(N,b)) iff a_i=b_i for every i in S."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual Burnol readout remains a right inverse at every depth."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-frame-kernel-cross-depth"),
                DeclarationHandle.Create(Prefix + "frameObserverKernel_burnol_depth_invariant"),
                H("Comparisons across distinct localization depths"),
                StatementSource.FromAuthor(Disp(F.Id("For arbitrary N,M, K_S(f_(N,a),f_(M,b)) iff a_i=b_i for every i in S."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The two tests may have different support radii and different analytic errors. Their selected readouts depend only on the original coefficients."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-frame-kernel-localization-interpolation"),
                DeclarationHandle.Create(Prefix + "frameObserverKernel_burnol_eq_interpolation"),
                H("Localization preserves the interpolation kernel"),
                StatementSource.FromAuthor(Disp(F.Id("The same-depth localized pullback equals the original interpolation pullback."))),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Both kernels are exactly coordinate equality on S. No equality of observations outside the frame is asserted."))), DescribeRole.Theorem)), []));
}
