import LeanInformationAudit.SealCommand
import LeanInformationAudit.Tests.Occurrence.ImportClosureProducer
import LeanInformationAudit.Tests.Assessment

test_imported_assessment

open LeanInformationAudit.Tests.ImportClosureProducer

test_assess in expect_information_occurrence importedTheorem
  in objectArena
  from "LeanInformationAudit.Tests.Occurrence.ImportClosureProducer"

test_assess in #seal_information_theory
