using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S1.Digit.Infinite;

internal sealed class ClosedObservationCommonTailWidthModelDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S1/Digit/Infinite/ClosedObservationCommonTailWidthModel.";

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Actual legal addresses, closed observations and the complete endpoint graph.",
        H("The Complete Closed Observation Model"),
        Blocks(
            Node("t", "The reciprocal golden ratio",
                "t is the reciprocal of the golden ratio, equivalently (sqrt(5) - 1)/2."),
            Node("g", "The three-bit contraction",
                "g = t^3 is the contraction magnitude. A source step deletes exactly three individual bits."),
            Node("lambda", "The critical radius",
                "The critical closed observation radius is lambda = t^2/10."),
            Node("stateInterval", "Guard intervals",
                "The incoming guards zero and one have closed scalar intervals I_0 = [-1, 1+t] and I_1 = [-1, t], respectively."),
            Node("stateAddress", "Actual guard restrictions",
                "An address is an infinite Boolean stream without adjacent ones. Incoming guard one requires its first bit to be zero; incoming guard zero imposes no additional restriction."),
            Node("bitShift", "Individual-bit shifts",
                "bitShift(x,n) deletes the lowest n bits of the actual address x and retains the no-adjacent-ones property."),
            Node("originalT", "The source clock",
                "T(x) = bitShift(x,3). Cylinder padding never changes this deletion clock."),
            Node("actualGuard", "The actual subsequent guard",
                "At time zero the guard is the specified incoming guard. At positive window time j it is bit 3j-1 of the original address."),
            Node("Label", "Legal windows",
                "A label is a legal Boolean word of length three, read from low to high, without adjacent ones."),
            Node("window", "Actual window extraction",
                "Window j consists of bits 3j, 3j+1 and 3j+2 of the same actual address."),
            Node("nullLabel", "The null window",
                "The null label is the three-bit word 000."),
            Node("threeLabel", "The label three",
                "The label three is the three-bit word 010."),
            Node("twoLabel", "The label two",
                "The label two is the three-bit word 100."),
            Node("fiveLabel", "The label five",
                "The label five is the three-bit word 001."),
            Node("twoFiveLabel", "The label twenty-five",
                "The label twenty-five is the single three-bit word 101."),
            Node("offset", "Window translations",
                "For bits e_0,e_1,e_2, the translation is e_0 - t e_1 + t^2 e_2. The null, two, three, twenty-five and five labels have translations 0, 1, -t, 2-t and t^2."),
            Node("offsetInteger", "Integral translation coordinates",
                "In the integral basis (1,phi), a window translation has coordinates (e_0+e_1+2e_2, -e_1-e_2), where phi=1+t."),
            Node("kappa", "The literal infinite window series",
                "The scalar of an actual address x is the infinite sum over j of (-g)^j times the translation of its j-th three-bit window. Distinct addresses at scalar contacts remain distinct."),
            Node("outgoing", "Outgoing guard",
                "The outgoing guard of a window is its highest bit."),
            Node("lawful", "The original guard graph",
                "A window from guard s to s-prime is lawful when incoming guard one forces the lowest window bit to be zero, and s-prime is the highest window bit. Thus guard zero admits null, two and three to zero and twenty-five and five to one; guard one admits null and three to zero and five to one."),
            Node("branch", "Closed forward branches",
                "For a legal window l, f_l(y)=Delta_l-g y, on the interval of its outgoing guard."),
            Node("inverseBranch", "Inverse branches",
                "The inverse branch is F_l(x)=(Delta_l-x)/g."),
            Node("finiteTail", "Eventually null addresses",
                "A finite-tail address has all individual bits zero from some index onward, equivalently all sufficiently late windows are null."),
            Node("cuts", "The five instrument cuts",
                "The cuts are a=-t^2-lambda, b=g-3lambda, c=t-5lambda, d=2t-7lambda and e=2t+lambda."),
            Node("cellLower", "Lower color endpoints",
                "The six lower endpoints, in color order zero through five, are -1,a,b,c,d,e."),
            Node("cellUpper", "Upper color endpoints",
                "The six upper endpoints, in color order zero through five, are a,b,c,d,e,1+t."),
            Node("observation", "Complete closed expansions",
                "For budget b_0 and color i, E_i is the interval [max(-1,l_i-b_0), min(1+t,r_i+b_0)]. Whole closed endpoints are retained."),
            Node("instrument", "A fixed color instrument",
                "A fixed function Q assigns every scalar in I_0 to one of six colors and assigns it within that color cell closure [l_i,r_i]. Each cut has one fixed assignment."),
            Node("exactObservation", "Actually attainable observations",
                "The exact closed-budget relation for color i consists of x in I_0 for which a target y in I_0 has Q(y)=i and |x-y|<=b_0. It is distinct from the complete closed expansion."),
            Node("inCoefficientField", "The rational coefficient field",
                "A scalar belongs to Q(t) when it can be written a+b t with rational a and b."),
            Node("endpoints", "The bounded-conjugate endpoint set",
                "For integer q>=1 and radius R, B consists of scalars x in I_0 of the form embedding(z)/q, where z is a golden integer and the absolute value of embedding(conj(z))/q is at most R."),
            Node("seeds", "All construction seeds",
                "The seed set contains -1,1+t,t,-t^2,g,2t and every effective lower and upper endpoint of the six closed expansions."),
            Node("endpointParameters", "Admissible construction parameters",
                "Parameters require q>=1, R>=0, every seed in B, and g times the absolute conjugate translation of every legal window at most (1-g)R. They assume neither graph finiteness nor address realization."),
            Node("basicPiece", "Singletons and adjacent closed intervals",
                "A guard-s basic piece [a,b] has endpoints in B intersect I_s, with a<=b, and either a=b or no point of B strictly between a and b. Entire adjacent closed intervals and all endpoint singletons are included."),
            Node("Vertex", "Typed graph vertices",
                "A vertex is a guard together with the two endpoints of one basic closed piece. Its guard type is retained."),
            Node("piece", "The set carried by a vertex",
                "The piece carried by vertex (s,a,b) is the entire closed interval [a,b]."),
            Node("edge", "Exact all-containment edges",
                "An edge from (s,P) with label l to (s-prime,Q) requires the lawful guard transition, P contained in f_l(I_s-prime), and Q contained in F_l(P). Both conditions concern the entire piece."),
            Node("permits", "Whole-piece color permission",
                "A vertex permits color i exactly when its whole piece is contained in E_i."),
            Node("ClosedPath", "Finite observed paths",
                "A point path reads one color and has an empty source word. A step reads a color at its current vertex, follows one exact all-containment edge and continues an observed path. A path with n colors has n-1 edges, and its terminal color is already read."),
            Node("addressChain", "Joint realization by one address",
                "A finite vertex and label chain is realized by one actual address when its first guard and scalar lie in the first piece, its first window is the first label, and its actual three-bit tail recursively realizes the remainder. A terminal point retains its actual guard and scalar."),
            Node("histories", "All word and terminal-vertex pairs",
                "For a nonempty color history, H contains every distinct terminal vertex and source word of a compatible path starting with guard zero. Path multiplicity is ignored. Before any color is read, every guard-zero vertex is paired with the empty word."),
            Node("globalLCP", "The global longest common prefix",
                "For a nonempty candidate family, select one word and take its longest prefix that is a prefix of every candidate word. The empty candidate family has the empty prefix."),
            Node("residuals", "The complete residual pair family",
                "R is the image of H under deletion of the same global longest common prefix from every candidate word, retaining the terminal vertex.")
        )));

    private static DocumentBlock Node(string declaration, string title, string prose) =>
        Describe.Lean(DescribeId.Create("closed-common-tail-model-" + declaration.ToLowerInvariant()),
            DeclarationHandle.Create(Prefix + declaration), H(title),
            StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
            Blocks(Paragraph(Text(prose))), DescribeRole.Definition);
}
