using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S1.Digit.Infinite;

internal sealed class ResetCodebookTargetDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S1/Digit/Infinite/ResetCodebookTarget.";
    private static readonly LibraryNoteRef Source = LibraryNoteRef.Create("D5/L/Analytic/mathlib2026gelfandandivt");

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Reset codebooks, actual sources and weighted lower-memory graphs.",
        H("Reset codebook: Target"),
        Blocks(
            Node("two_step_row", "two step row", "For the specified parameters, the following hypotheses imply the stated relation: (K n : ℕ) (d : ℝ) (hK : 2 ≤ K) (hKn : K ≤ n) (v : Vertex (Statement.lowerLanguage K n d) n) : 2 ≤ ∑ u, (lowerMatrix K n d 1 ^ 2) v u", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("transfer_scale_le", "transfer scale le", "For the specified parameters, the following hypotheses imply the stated relation: (next : ι → Bool → ι) (allow : ι → Bool → Prop) (x y a : ℝ) (h6 : a*x^6 ≤ y^6) (h20 : a*x^20 ≤ y^20) : ∀ i j, (a • transfer next allow x) i j ≤ transfer next allow y i j", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("transfer_le_scale", "transfer le scale", "For the specified parameters, the following hypotheses imply the stated relation: (next : ι → Bool → ι) (allow : ι → Bool → Prop) (x y a : ℝ) (h6 : y^6 ≤ a*x^6) (h20 : y^20 ≤ a*x^20) : ∀ i j, transfer next allow y i j ≤ (a • transfer next allow x) i j", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("transfer_radius_sandwich", "transfer radius sandwich", "For the specified parameters, the following hypotheses imply the stated relation: (next : ι → Bool → ι) (allow : ι → Bool → Prop) (x y : ℝ) (hx : 0<x) (hy : 0<y) : min ((y/x)^6) ((y/x)^20) * radius (transfer next allow x) ≤ radius (transfer next allow y) ∧ radius (transfer next allow y) ≤ max ((y/x)^6) ((y/x)^20) * radius (transfer next allow x)", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("transfer_radius_continuous_pos", "transfer radius continuous pos", "For the specified parameters, the following hypotheses imply the stated relation: (next : ι → Bool → ι) (allow : ι → Bool → Prop) : ContinuousOn (fun z : ℝ => radius (transfer next allow z)) (Set.Ioi 0)", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("transfer_complex_continuous", "transfer complex continuous", "For the specified parameters, the following hypotheses imply the stated relation: (next : ι → Bool → ι) (allow : ι → Bool → Prop) : Continuous (fun z : ℝ => complexify (transfer next allow z))", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("transfer_radius_zero", "transfer radius zero", "For the specified parameters, the following hypotheses imply the stated relation: (next : ι → Bool → ι) (allow : ι → Bool → Prop) : radius (transfer next allow 0) = 0", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("transfer_radius_continuous_zero", "transfer radius continuous zero", "For the specified parameters, the following hypotheses imply the stated relation: (next : ι → Bool → ι) (allow : ι → Bool → Prop) : ContinuousAt (fun z : ℝ => radius (transfer next allow z)) 0", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("transfer_radius_continuous_Icc", "transfer radius continuous Icc", "For the specified parameters, the following hypotheses imply the stated relation: (next : ι → Bool → ι) (allow : ι → Bool → Prop) : ContinuousOn (fun z : ℝ => radius (transfer next allow z)) (Set.Icc 0 1)", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("lower_radius_pos", "lower radius pos", "For the specified parameters, the following hypotheses imply the stated relation: (K n : ℕ) (d z : ℝ) (hK : 2 ≤ K) (hKn : K ≤ n) (hz : 0<z) : 0 < radius (lowerMatrix K n d z)", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("lower_radius_one_gt", "lower radius one gt", "For the specified parameters, the following hypotheses imply the stated relation: (K n : ℕ) (d : ℝ) (hK : 2 ≤ K) (hKn : K ≤ n) : 1 < radius (lowerMatrix K n d 1)", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("lower_radius_strict", "lower radius strict", "For the specified parameters, the following hypotheses imply the stated relation: (K n : ℕ) (d : ℝ) (hK : 2 ≤ K) (hKn : K ≤ n) : StrictMonoOn (fun z : ℝ => radius (lowerMatrix K n d z)) (Set.Ioi 0)", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("original_root_exists_unique", "original root exists unique", "For every K >= 2, n >= K and real guard threshold d, the original pruned 6/20 matrix has exactly one spectral root z in (0,1). Two low extensions from every retained vertex force its square at z=1 to have row sums at least two. Degree-6/20 comparisons give continuity and strict increase; the intermediate value theorem then gives the root.", DescribeRole.Theorem, AssessedProvenance.FromRepo(Source)),
            Node("coefficient_spectral_bound", "coefficient spectral bound", "For the specified parameters, the following hypotheses imply the stated relation: {ι : Type*} [Fintype ι] [DecidableEq ι] (T : Matrix ι ι ℂ) (c : ℕ → ℕ) (z D : ℝ) (hz : 0<z) (hz1 : z<1) (hD : 0 ≤ D) (hs : spectralRadius ℂ T=1) (hc : ∀ N : ℕ, (c N:ℝ)*z^N ≤ D * ∑ k ∈ Finset.range (N+1), ‖T^k‖) (hb : IsBoundedUnder (· ≤ ·) atTop (fun N : ℕ => Real.log (max 1 (c N):ℝ)/Real.log 2/(N:ℝ))) : limsup (fun N : ℕ => Real.log (max 1 (c N):ℝ)/Real.log 2/(N:ℝ)) atTop ≤ -Real.log z/Real.log 2", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("factor_mass_le_paths", "factor mass le paths", "For the specified parameters, the following hypotheses imply the stated relation: (lang : Set (ℤ → Bool)) (z : ℝ) (hz : 0 ≤ z) (N : ℕ) (ext : ∀ w : Factors lang N, ∃ v : ι, accepts next allow v w.val) : (Statement.factorCount lang N:ℝ)*z^N ≤ ∑ k ∈ Finset.range (N+1), ∑ v, ∑ u, (transfer next allow z ^ k) v u", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("lower_factor_mass_le_paths", "lower factor mass le paths", "For the specified parameters, the following hypotheses imply the stated relation: (K n N : ℕ) (d z : ℝ) (hz : 0≤z) : (Statement.factorCount (Statement.lowerLanguage K n d) N:ℝ)*z^N ≤ ∑ k ∈ Finset.range (N+1), ∑ v, ∑ u, (lowerMatrix K n d z ^ k) v u", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("lowerComplex_pow", "lowerComplex pow", "For the specified parameters, the following hypotheses imply the stated relation: (K n k : ℕ) (d z : ℝ) : lowerComplexMatrix K n d z ^ k = Complex.ofRealHom.mapMatrix (lowerMatrix K n d z ^ k)", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("lower_row_le_norm", "lower row le norm", "For the specified parameters, the following hypotheses imply the stated relation: (K n k : ℕ) (d z : ℝ) (hz : 0≤z) (v : Vertex (Statement.lowerLanguage K n d) n) : (∑ u, (lowerMatrix K n d z ^ k) v u) ≤ ‖lowerComplexMatrix K n d z ^ k‖", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("lower_factor_mass_le_norm_powers", "lower factor mass le norm powers", "For the specified parameters, the following hypotheses imply the stated relation: (K n N : ℕ) (d z : ℝ) (hz : 0≤z) : (Statement.factorCount (Statement.lowerLanguage K n d) N:ℝ)*z^N ≤ (Fintype.card (Vertex (Statement.lowerLanguage K n d) n):ℝ) * ∑ k ∈ Finset.range (N+1), ‖lowerComplexMatrix K n d z ^ k‖", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("lower_language_rate_le_spectral_gamma", "lower language rate le spectral gamma", "For the specified parameters, the following hypotheses imply the stated relation: (K n : ℕ) (d z : ℝ) (hz : SpectralRoot K n d z) : Statement.rate (Statement.lowerLanguage K n d) ≤ gamma z", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("original_language_rate_le_spectral_gamma", "original language rate le spectral gamma", "The explicit factor-count limsup of the strict lower-memory language is at most minus log base two of the original pruned-matrix spectral root. Accepted-word mass, row sums of transition powers and a uniform exponential norm majorant control the same weighted factor count.", DescribeRole.Theorem, AssessedProvenance.FromRepo(Source)),
            Node("codebook_language_realization", "codebook language realization", "For the specified parameters, the following hypotheses imply the stated relation: (anchor : Bool) (K M N : ℕ) (b d : ℝ) (hK : 2 ≤ K) (hM : 1 ≤ M) (hN : 0 < N) (hbudget : lambda-g^2*chi^K*h false < b ∧ b < lambda-g^2*chi^K*(A false/(1-rho*chi^K))) (hd : d=(lambda-b)/(g^2*chi^K)) (hreset : max (max (X false) (Y false)) d < Statement.B M) (hne : (Statement.codebook anchor K N d).Nonempty) : Statement.target6218Language anchor K M N b d hK hM hN hbudget hd hreset hne", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("RootFamily", "RootFamily", "The mathematical data are specified by RootFamily(K : ℕ) (d : ℝ) := ∀ n : ℕ, K≤n → {z : ℝ // D5.S1.Digit.Infinite.ResetCodebook.Transfer.OriginalSpectralRoot K n d z}.", DescribeRole.Definition, AssessedProvenance.FromRepo()),
            Node("target6218", "target6218", "The mathematical data are specified by target6218(anchor : Bool) (K M N : ℕ) (b d : ℝ) (hK : 2 ≤ K) (hM : 1 ≤ M) (hN : 0 < N) (hbudget : lambda-g^2*chi^K*h false < b ∧ b < lambda-g^2*chi^K*(A false/(1-rho*chi^K))) (hd : d=(lambda-b)/(g^2*chi^K)) (hreset : max (max (X false) (Y false)) d < D5.S1.Digit.Infinite.ResetCodebook.Statement.B M) (hne : (D5.S1.Digit.Infinite.ResetCodebook.Statement.codebook anchor K N d).Nonempty) (roots : RootFamily K d) : Prop := .", DescribeRole.Definition, AssessedProvenance.FromRepo()),
            Node("spectral_codebook_realization", "spectral codebook realization", "For the specified parameters, the following hypotheses imply the stated relation: (anchor : Bool) (K M N : ℕ) (b d : ℝ) (hK : 2 ≤ K) (hM : 1 ≤ M) (hN : 0 < N) (hbudget : lambda-g^2*chi^K*h false < b ∧ b < lambda-g^2*chi^K*(A false/(1-rho*chi^K))) (hd : d=(lambda-b)/(g^2*chi^K)) (hreset : max (max (X false) (Y false)) d < D5.S1.Digit.Infinite.ResetCodebook.Statement.B M) (hne : (D5.S1.Digit.Infinite.ResetCodebook.Statement.codebook anchor K N d).Nonempty) (roots : D5.S1.Digit.Infinite.ResetCodebook.Statement.RootFamily K d) : D5.S1.Digit.Infinite.ResetCodebook.Statement.target6218 anchor K M N b d hK hM hN hbudget hd hreset hne roots", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("lowerRoot", "lowerRoot", "The mathematical data are specified by lowerRoot(K n : ℕ) (d : ℝ) (hK : 2 ≤ K) (hKn : K ≤ n) : ℝ := .", DescribeRole.Definition, AssessedProvenance.FromRepo()),
            Node("lowerRoot_spec", "lowerRoot spec", "For the specified parameters, the following hypotheses imply the stated relation: (K n : ℕ) (d : ℝ) (hK : 2 ≤ K) (hKn : K ≤ n) : D5.S1.Digit.Infinite.ResetCodebook.Transfer.OriginalSpectralRoot K n d (lowerRoot K n d hK hKn)", DescribeRole.Theorem, AssessedProvenance.FromRepo()),
            Node("rootFamily", "rootFamily", "The mathematical data are specified by rootFamily(K : ℕ) (d : ℝ) (hK : 2 ≤ K) : Statement.RootFamily K d := .", DescribeRole.Definition, AssessedProvenance.FromRepo()),
            Node("reset_codebook_common_realization", "reset codebook common realization", "Fix either actual initial state, K >= 2, a reset length M >= 1, positive weight N, the strict budget window, the associated guard threshold and a nonempty complete weak codebook. All finite actual reset concatenations share a positive error margin and retain their literal high and low tails and every departure slot. Every bilateral auxiliary concatenation has the common strict high-state margin. One finite depth n >= K places all of them in the original lower graph, whose uniquely defined spectral gamma is at least log2 of the complete codebook cardinality divided by N+20+6M. Auxiliary bilateral sequences are distinct objects from the finite actual sources.", DescribeRole.Theorem, AssessedProvenance.FromRepo(Source))
        )));

    private static DocumentBlock Node(string declaration, string title, string prose,
        DescribeRole role, AssessedProvenance provenance) =>
        Describe.Lean(DescribeId.Create("resetcodebooktarget-" + declaration.ToLowerInvariant()),
            DeclarationHandle.Create(Prefix + declaration), H(title),
            StatementSource.WithoutFormula(), provenance,
            Blocks(Paragraph(Text(prose))), role);
}
