using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.FluidDynamics.Cone;

internal sealed class ConePositivityDocument : IScribeDocumentDefinition
{
    private const string P = "D5/S3/FluidDynamics/Cone/ConePositivity.";

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Above two, the cone condition is equivalent to positive definiteness of a symmetric real matrix with two rows and two columns.",
        H("Cone positivity"), Blocks(
            Describe.Lean(DescribeId.Create("cone-positivity-root-term"),
                DeclarationHandle.Create(P + "rootTerm"), H("Root term"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The root term is the absolute value of J times the square root of the radicand."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("cone-positivity-cone-bound"),
                DeclarationHandle.Create(P + "coneBound"), H("Cone bound"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The cone bound subtracts the root term from P plus one quarter of the square of J."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("cone-positivity-root-nonnegative"),
                DeclarationHandle.Create(P + "rootTerm_nonneg"), H("Nonnegative root term"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The root term is nonnegative for all real parameters."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("cone-positivity-root-square"),
                DeclarationHandle.Create(P + "rootTerm_sq"), H("Square of the root term"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For P greater than two, squaring the root term removes the square root."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("cone-positivity-root-quarter"),
                DeclarationHandle.Create(P + "rootTerm_ge_quarter"), H("Quarter square bound"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For P greater than two, the root term is at least one quarter of the square of J."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("cone-positivity-bound-parameter"),
                DeclarationHandle.Create(P + "coneBound_le_parameter"), H("Bound by the parameter"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For P greater than two, the cone bound is at most P."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("cone-positivity-bound-two"),
                DeclarationHandle.Create(P + "coneBound_gt_two"), H("Bound greater than two"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For P greater than two, the cone bound is strictly greater than two."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("cone-positivity-relaxed-cone"),
                DeclarationHandle.Create(P + "relaxed_cone_of_le_two"), H("Parameters at most two"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("If P is greater than two and v is at most two, v lies strictly below the cone bound."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("cone-positivity-boundary-polynomial"),
                DeclarationHandle.Create(P + "boundary_polynomial"), H("Boundary polynomial"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The cone boundary expression expands as a quadratic polynomial in v."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("cone-positivity-square-difference"),
                DeclarationHandle.Create(P + "square_difference"), H("Difference of squares"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The difference of squares equals half of the cone boundary expression."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("cone-positivity-true-cone"),
                DeclarationHandle.Create(P + "true_cone_iff"), H("Algebraic cone characterization"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Above two, the cone condition is equivalent to v being less than P together with the strict quadratic inequality."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("cone-positivity-matrix"),
                DeclarationHandle.Create(P + "coneMatrix"), H("Cone matrix"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The cone matrix is a symmetric real matrix with two rows and two columns."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("cone-positivity-quadratic-matrix-iff"),
                DeclarationHandle.Create(P + "coneMatrix_posDef_iff"), H("Quadratic positivity bridge"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Above two, positive definiteness of the cone matrix is equivalent to the strict quadratic cone inequalities."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("cone-positivity-matrix-iff"),
                DeclarationHandle.Create(P + "cone_condition_iff_posDef"), H("Cone condition and positive definiteness"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Above two, the cone condition is equivalent to positive definiteness of the cone matrix."))),
                DescribeRole.Theorem))));
}
