using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Observer.Hankel;

internal sealed class BalancedSteinEnergyDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "A diagonal reachability Stein inequality yields inverse-storage input-energy dissipativity.",
        H("Diagonal Stein Energy Duality"),
        Blocks(
            Describe.Lean(DescribeId.Create("energy"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.energy"), H("Energy"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Quadratic form of a diagonal real matrix. Positivity is supplied separately and then used to prove nonnegative storage."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("square-sum"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.squareSum"), H("Square sum"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Euclidean squared size of a finite coordinate vector. This definition does not use the default Pi sup norm."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("matrix-map"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.matrixMap"), H("Matrix map"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Reuses Mathlib matrix multiplication and the finite-dimensional linear-to-continuous-linear equivalence."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("matrix-map-apply"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.matrixMap_apply"), H("Matrix map apply"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The continuous linear adapter acts by the original matrix-vector multiplication."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("matrix-state"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.matrixState"), H("Matrix state"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Reuses the zero-initial forced recurrence already owned by ProjectedRealizationError."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("matrix-response"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.matrixResponse"), H("Matrix response"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Output of the actual matrix recurrence with zero initial state and no direct feedthrough term."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("matrix-state-zero"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.matrixState_zero"), H("Matrix state zero"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The reused state constructor has zero initial state."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("matrix-state-succ"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.matrixState_succ"), H("Matrix state succ"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The reused state constructor advances by the supplied transition and input matrices."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("observability-stein"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.ObservabilityStein"), H("Observability stein"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The standard diagonal observability Stein inequality, quantified over every real state."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("reachability-stein"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.ReachabilityStein"), H("Reachability stein"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The standard diagonal reachability Stein inequality, quantified over every real dual state. An inverse-storage gain bound is not included as a premise."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("balanced-stein"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.BalancedStein"), H("Balanced stein"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A positive common diagonal satisfying both Stein inequalities. These data need not already be identified as the exact Gramians of a stable minimal system."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("energy-zero"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.energy_zero"), H("Energy zero"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The diagonal quadratic form vanishes on the zero state."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("square-sum-zero"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.squareSum_zero"), H("Square sum zero"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Zero coordinates have zero Euclidean squared size."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("energy-nonneg"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.energy_nonneg"), H("Energy nonneg"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Nonnegative diagonal weights give nonnegative energy."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("square-sum-nonneg"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.squareSum_nonneg"), H("Square sum nonneg"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A finite sum of real coordinate squares is nonnegative."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("square-sum-smul"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.squareSum_smul"), H("Square sum smul"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Scalar multiplication rescales Euclidean squared size by the square of the scalar."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("inverse-energy-step"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/BalancedSteinEnergy.inverse_energy_step"), H("Inverse energy step"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Weighted Young inequalities and transposed matrix pairing derive inverse-diagonal dissipativity from the actual reachability Stein inequality. No gain or inverse-energy conclusion is assumed."))), DescribeRole.Theorem)),
        [DocumentEdge.Dependency.Create(GidRef.Create("D5/S3/Observer/Hankel/ProjectedRealizationError"))]));
}
