using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Observer.Hankel;

internal sealed class DiscreteSteinCompressionStabilityDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Positive diagonal discrete Stein dissipation excludes every unit-circle pole after actual principal truncation.",
        H("Discrete Stein Compression Stability"),
        Blocks(
            Describe.Lean(DescribeId.Create("complex-matrix"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.complexMatrix"), H("Complexified matrix"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The real matrix acts on complex states so nonreal poles are included."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("complex-matrix-mul"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.complexMatrix_mul"), H("Complexified products"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Complexification preserves the actual matrix products used in iterated readouts."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("complex-energy"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.complexEnergy"), H("Complex state energy"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Positive diagonal weights measure the sum of squared complex moduli."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("energy-nonnegative"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.complexEnergy_nonneg"), H("Nonnegative energy"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Nonnegative weights give nonnegative complex state energy."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("energy-zero"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.complexEnergy_eq_zero_iff"), H("Definite energy"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Positive weights make zero energy equivalent to a zero complex state."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("energy-positive"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.complexEnergy_pos"), H("Positive nonzero-state energy"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Every nonzero complex eigenvector carries strictly positive energy."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("energy-scaling"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.complexEnergy_smul"), H("Complex scalar scaling"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Complex scalar multiplication rescales energy by the squared scalar modulus."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("complex-stein"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.complex_observability_stein"), H("Complexified Stein inequality"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Adds the real and imaginary parts of the real Stein inequality to derive the complex-state inequality."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("complex-observability"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.observable_complexification"), H("Complexified full observation"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Real joint readout injectivity implies complex joint injectivity by separating real and imaginary parts."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("prefix-lift"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.prefixLift"), H("Zero extension"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Zero-extends retained coordinates by a finite sum, including the empty retained space."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("prefix-projection"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.prefixProjection"), H("Principal projection"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual prefix projection is orthogonal for every positive diagonal metric."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("lift-retained-coordinate"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.prefixLift_at"), H("Retained coordinate recovery"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Zero extension preserves each retained coordinate exactly."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("action-on-lift"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.action_prefixLift"), H("Actual truncated action"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Matrix action on the lifted state is exactly the action of the retained matrix columns."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("projection-energy-split"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.projection_energy_split"), H("Retained and discarded energy"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Splits the exact complex state energy into retained and discarded nonnegative terms."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("strict-eigenvalue-bound"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.principal_truncation_eigenvalue_lt_one"), H("Strict complex eigenvalue bound"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The Stein inequality puts a retained eigenvalue in the closed disk. Equality forces both discarded action and output to vanish, producing an unobservable full-system eigenvector and a contradiction. Neither a singular-value gap nor reduced minimality is assumed."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("strict-spectrum-bound"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/DiscreteSteinCompressionStability.principal_truncation_spectrum_lt_one"), H("Strict internal stability"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Every point of the standard complex spectrum of the actual principal block has modulus below one. This covers nonreal poles, repeated weights and zero-dimensional cuts; no custom stability predicate replaces the conclusion."))), DescribeRole.Theorem)),
        [DocumentEdge.Dependency.Create(GidRef.Create("D5/S3/Observer/Hankel/BalancedTruncationTail"))]));
}
