using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Observer.Hankel;

internal sealed class ExecutableHoKalmanDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Finite noisy Ho-Kalman reconstruction with explicit arithmetic certificates.",
        H("ExecutableHoKalman"),
        Blocks(
            Describe.Lean(DescribeId.Create("tuples"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.tuples"), H("tuples"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Finite Cartesian powers are enumerated as lists, with no noncomputable conversion from a finite set."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("mem-tuples"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.mem_tuples"), H("mem tuples"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Induction proves that every coordinatewise-valid tuple occurs in the enumeration."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("all-pivots"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.allPivots"), H("allPivots"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Every selection of observation rows and reachability columns is listed in a fixed order. This transparent exhaustive algorithm is not claimed to be efficient for large dimensions."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("mem-all-pivots"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.mem_allPivots"), H("mem allPivots"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("No finite candidate pivot is omitted from the search space."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("abs-sum"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.absSum"), H("absSum"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The rational sum of absolute entries gives a conservative and executable upper bound for the induced infinity norm."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("acceptable"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.acceptable"), H("acceptable"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The data-only Boolean test checks a nonzero determinant, nonnegative entrywise uncertainty, and a strict inverse-noise margin."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("scan"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.scan"), H("scan"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A structural recursion returns the first accepted pivot or rejects after exhausting the supplied finite list."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("scan-sound"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.scan_sound"), H("scan sound"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Every successful scan result passes the actual Boolean acceptance test."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("scan-none-iff"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.scan_none_iff"), H("scan none iff"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A rejected scan is equivalent to failure of every acceptance test in its input list."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("choose-pivot"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.choosePivot"), H("choosePivot"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The exhaustive list is passed to the verified scan; the caller provides samples, model order and uncertainty, never an inverse or a success proof."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("choose-pivot-none-iff"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.choosePivot_none_iff"), H("choosePivot none iff"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Global rejection has the precise meaning that every candidate fails the stated conservative test."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("choose-pivot-success"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.choosePivot_success"), H("choosePivot success"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("If some candidate passes the executable test, the search returns a candidate. This is completeness relative to the test, not automatic model-order identification."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("choose-pivot-certificate"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.choosePivot_certificate"), H("choosePivot certificate"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Success exposes the determinant and strict rational margin that will be consumed by the real perturbation theorem."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("result"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.Result"), H("Result"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The output contains a selected pivot and three rational matrices. No correctness or error assertion is hidden in a structure field."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("run"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.run"), H("run"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("An accepted pivot is converted into actual transition, input and output matrices. Singular or insufficiently conditioned data return none."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("run-fields"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.run_fields"), H("run fields"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The output fields are proved to coincide with the finite-data construction at the returned pivot."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("run-exact-recovery"), DeclarationHandle.Create("D5/S3/Observer/Hankel/ExecutableHoKalman.run_exact_recovery"), H("run exact recovery"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The actual output reproduces every Markov parameter of any order-matching reference system consistent with the noiseless input samples. The source also includes scalar reduction examples; their execution status is separate from their presence."))), DescribeRole.Theorem)),
        [DocumentEdge.Dependency.Create(GidRef.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks"))]));
}
