using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Observer.Hankel;

internal sealed class FiniteHoKalmanBlocksDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Finite Markov samples, explicit block inversion, and all-time exact reconstruction.",
        H("Finite Ho-Kalman Data Blocks"),
        Blocks(
            Describe.Lean(DescribeId.Create("samples"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.Samples"), H("Finite sample array"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The input contains exactly 2h Markov matrices. The convention is m(k)=C A^k B; a direct-feedthrough term is outside this array."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("pivot"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.Pivot"), H("Selected observation and reachability indices"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A pivot chooses r time/output rows and r time/input columns. Nonsingularity, when required, excludes repetitions automatically."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("base-block"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.baseBlock"), H("Unshifted Hankel minor"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Every access is an index into the finite input array, with a proved bound."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("shift-block"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.shiftBlock"), H("One-step shifted minor"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The shift uses the same selected rows and columns and one additional time step."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("input-block"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.inputBlock"), H("Input data block"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("All input coordinates are retained at the selected observation rows."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("output-block"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.outputBlock"), H("Output data block"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("All output coordinates are retained at the selected reachability columns."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("adj-inverse"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.adjInverse"), H("Explicit adjugate inverse"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The inverse candidate is computed from the determinant and adjugate. Its correctness requires a nonzero determinant, which the executable search checks."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("adj-inverse-mul"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.adjInverse_mul"), H("Left inverse correctness"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Mathlib's adjugate identity proves that the computed candidate is a left inverse."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("mul-adj-inverse"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.mul_adjInverse"), H("Right inverse correctness"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The second adjugate identity proves the right inverse equation."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("fitted-a"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.fittedA"), H("Computed state transition"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The transition is the computed inverse times the shifted data block."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("fitted-b"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.fittedB"), H("Computed input map"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The input map is the computed inverse times the input data block."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("fitted-c"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.fittedC"), H("Computed output map"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The output data block directly gives the output map in the selected reachable coordinates."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selected-o"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.selectedO"), H("Selected observation matrix"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("This reference-system matrix is used only in the correctness proof. It is not an input to the reconstruction."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("selected-r"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.selectedR"), H("Selected reachability matrix"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Its columns define the recovered state coordinates. The algorithm does not need to know the reference system."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sample-factorizations"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.sample_factorizations"), H("Data semantics imply four factorizations"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The four block equations follow from finite Markov-parameter equality by matrix multiplication and addition of time exponents."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("factorized-exact-recovery"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.factorized_exact_recovery"), H("Finite factors imply all-time reproduction"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A computed inverse supplies two-sided coordinate maps. An induction transports every matrix power, including systems with Jordan blocks."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-samples-exact-recovery"), DeclarationHandle.Create("D5/S3/Observer/Hankel/FiniteHoKalmanBlocks.finite_samples_exact_recovery"), H("Exact finite-sample reconstruction theorem"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Any order-r reference realization matching the finite samples and giving a nonsingular selected minor has exactly the computed all-time behavior. The reference dimension is an explicit model-class hypothesis, not inferred from arbitrary finite data."))), DescribeRole.Theorem)),
        []));
}
