using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Observer.Hankel;

internal sealed class InfiniteHankelGramianDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Actual half-line observation and reachability construct an infinite l2 Hankel operator with the correct Markov blocks.",
        H("InfiniteHankelGramian"),
        Blocks(
            Describe.Lean(DescribeId.Create("signal"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.Signal"), H("Signal"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Square-summable Euclidean-valued signals on the entire nonnegative time axis."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("futureoutput"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.futureOutput"), H("future Output"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Constructs every genuine future output and proves its l2 membership. Finite-dimensional continuity supplies the bounded operator."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("futureoutput-apply"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.futureOutput_apply"), H("future Output apply"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The kth coordinate is exactly C times A to the kth power applied to the original state."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("futureoutput-norm-sq"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.futureOutput_norm_sq"), H("future Output norm sq"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Identifies the norm of the actual infinite output sequence with the constructed Gramian quadratic form."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("futureoutput-inner"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.futureOutput_inner"), H("future Output inner"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Polarization proves the complete Gram bilinear identity, including all cross terms."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("futureoutput-gramian"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.futureOutput_gramian"), H("future Output gramian"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Proves that the infinite observation operator adjoint times itself is exactly the matrix Gramian on Euclidean coordinates."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("pastinput"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.pastInput"), H("past Input"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The adjoint of the actual dual future-output operator is the past-to-state map."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hankel"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.hankel"), H("hankel"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual bounded infinite past-to-future operator, as observation after reachability."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("pastinput-gramian"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.pastInput_gramian"), H("past Input gramian"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Identifies reachability times its adjoint with the actual control Gramian."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("pastinput-single"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.pastInput_single"), H("past Input single"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("One input of age j reaches the genuine state A to the jth power times B applied to that input."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hankel-single"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.hankel_single"), H("hankel single"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Proves every infinite Hankel block is C times A to the power i+j times B. Finite and infinite objects are not conflated."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hankel-hassum"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/InfiniteHankelGramian.hankel_hasSum"), H("hankel has Sum"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("All l2 inputs are norm limits of their single-input sums; the actual bounded operator transports those sums."))), DescribeRole.Theorem)),
        [DocumentEdge.Dependency.Create(GidRef.Create("D5/S3/Observer/Hankel/ExactGramianSeries"))]));
}
