using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Observer.Hankel;

internal sealed class NoisyHoKalmanRecoveryDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Finite noisy Ho-Kalman reconstruction with explicit arithmetic certificates.",
        H("NoisyHoKalmanRecovery"),
        Blocks(
            Describe.Lean(DescribeId.Create("inverse-budget"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.inverseBudget"), H("inverseBudget"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The sum of absolute entries of the computed rational inverse is a directly executable certificate quantity."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("a-error-budget"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.aErrorBudget"), H("aErrorBudget"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The transition error budget uses the observed transition norm bound, the entrywise noise budget, the selected order, and the positive inverse-margin denominator."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("b-error-budget"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.bErrorBudget"), H("bErrorBudget"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The input error budget uses the number of input columns for direct input-block uncertainty and the state order for inverse perturbation."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("c-error-budget"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.cErrorBudget"), H("cErrorBudget"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The output block needs no inverse solve, so its error budget is state order times entrywise uncertainty."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("real-matrix"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.realMatrix"), H("realMatrix"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A semantic bridge interprets rational algorithm outputs as real matrices without changing their coordinates."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("real-matrix-mul"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.realMatrix_mul"), H("realMatrix mul"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Real interpretation preserves finite matrix multiplication, linking the executable arithmetic to the analysis."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("real-matrix-one"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.realMatrix_one"), H("realMatrix one"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Real interpretation preserves the identity matrix, so the computed inverse identity transports to real analysis."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("real-samples"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.realSamples"), H("realSamples"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The finite sample indexing is retained while entries are interpreted in the real field."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("norm-real-matrix-le-abs-sum"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.norm_realMatrix_le_absSum"), H("norm realMatrix le absSum"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A finite-sum comparison proves that the rational absolute-entry sum bounds the real induced infinity operator norm."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("sample-noise-blocks"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.sample_noise_blocks"), H("sample noise blocks"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("One uniform sample-error hypothesis yields all four block-error bounds with the correct MIMO dimension factors."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("run-noisy-recovery"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.run_noisy_recovery"), H("run noisy recovery"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("From actual program success, finite real model semantics and entrywise noise, derive true-block nonsingularity, exact true behavior in selected reachable coordinates, and three explicit bounds for the returned matrices. Neither the reference realization nor its coordinate transform is supplied to the program."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("run-order-lower-bound"), DeclarationHandle.Create("D5/S3/Observer/Hankel/NoisyHoKalmanRecovery.run_order_lower_bound"), H("Noise-compatible model-order lower bound"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A successful rational inverse-margin certificate excludes every real system of dimension below r whose finite Markov parameters lie within the supplied entrywise noise budget. It does not require the comparison system to have order r."))), DescribeRole.Theorem)),
        [DocumentEdge.Dependency.Create(GidRef.Create("D5/S3/Observer/Hankel/ExecutableHoKalman")), DocumentEdge.Dependency.Create(GidRef.Create("D5/S3/Observer/Hankel/HoKalmanPerturbation"))]));
}
