using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Observer.Hankel;

internal sealed class SequenceHankelRealizationDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Finite-rank input-output data constructs its own reachable and observable minimal linear realization, with finite-window rank attainment and an undersized-compression witness.",
        H("Minimal Linear Realization from Sequence Data"),
        Blocks(
            Describe.Lean(
                DescribeId.Create("data-tail"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.dataTail"),
                H("Output tail from data"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For an input direction u and age j, the i-th future coordinate is m(i+j)u. The data sequence is the only input to this definition."))),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("tail-space"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.tailSpace"),
                H("Infinite data Hankel column space"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Take the linear span of all data tails in the full output-sequence space. Finite rank is expressed by FiniteDimensional on this carrier, since natural-valued finrank alone does not detect infinite dimension."))),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("sequence-shift"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.sequenceShift"),
                H("Shift on output sequences"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The left shift advances a sequence by one coordinate. Its restriction is justified by a proved invariance argument on the data-tail generators."))),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("tail-state"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.tailState"),
                H("A history direction as a state"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A single input direction at a specified age gives a canonical element of the data-tail span."))),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("sequence-dynamics"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.sequenceDynamics"),
                H("Dynamics constructed from data"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Restrict the left shift to the invariant data-tail span. The map is constructed here; it is not a field requiring a caller-supplied realization."))),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("sequence-input"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.sequenceInput"),
                H("Canonical input map"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The input map sends a direction to its unshifted output tail."))),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("sequence-output"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.sequenceOutput"),
                H("Canonical output map"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Evaluate a canonical state at its present coordinate."))),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("sequence-dynamics-pow-apply"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.sequenceDynamics_pow_apply"),
                H("Iterated dynamics advances coordinates"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The n-th iterate of the constructed dynamics sends coordinate i to coordinate i+n, for every state in the tail span."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("sequence-dynamics-pow-input"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.sequenceDynamics_pow_input"),
                H("Input iterates are the data tails"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Applying the constructed dynamics n times to an injected input produces precisely the data tail of age n."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("sequence-output-pow"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.sequenceOutput_pow"),
                H("Every future output reads a coordinate"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Future output at time n equals coordinate n of the canonical state. This identity supplies the distinguishing observation in the compression theorem."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("sequence-markov-parameter-eq"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.sequence_markovParameter_eq"),
                H("All Markov parameters match the supplied data"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The canonical realization reproduces every m(n), with no modal, eigenvalue, diagonalizability or stability hypothesis."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("sequence-reachable-eq-top"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.sequence_reachable_eq_top"),
                H("Canonical reachability"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The input iterates span the entire constructed state space. This is proved by transporting the data-tail generators into the existing reachableSubspace owner."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("sequence-eventual-kernel-eq-bot"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.sequence_eventualKernel_eq_bot"),
                H("Canonical observability"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A canonical state with zero output at every future time has all coordinates zero. The result uses the existing eventualKernel definition."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("future-output"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.futureOutput"),
                H("All-future observation of a competing model"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Map a competing state to the sequence of outputs obtained under repeated application of its dynamics."))),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("tail-space-le-future-output-range"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.tailSpace_le_futureOutput_range"),
                H("Every realization contains the data-tail behavior"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For any realization matching the complete data, every data tail is the future observation of a reachable state. Taking linear spans gives the range inclusion needed for the dimension lower bound."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("finite-tail-space-of-realization"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.finite_tailSpace_of_realization"),
                H("Finite models force finite data rank"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The range of a finite-dimensional state model is finite-dimensional. The proved inclusion therefore forces finite dimensionality of the full data-tail span."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("tail-space-finrank-le-state-dimension"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.tailSpace_finrank_le_stateDimension"),
                H("A universal linear-state dimension lower bound"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Every finite-dimensional realization of the complete sequence has state dimension at least the data-tail dimension. This concerns linear state dimension, not general nonlinear memory or DFA state count."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("realization-from-sequence"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.realizationFromSequence"),
                H("A finite realization from finite-rank data"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Under finite dimensionality of the data-tail span, package the constructed dynamics, input and output in the existing FiniteLinearRealization structure. No pre-existing system is assumed."))),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("finite-tail-space-iff-exists-realization"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.finite_tailSpace_iff_exists_realization"),
                H("Finite Hankel rank characterizes finite realizability"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The infinite block Hankel column span is finite-dimensional exactly when there is a finite linear realization of the complete sequence. This is an algebraic realization theorem, not an algorithm for noisy finite samples."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("realization-from-sequence-is-minimal"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.realizationFromSequence_is_minimal"),
                H("The lower bound is attained"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The named data-only construction matches the sequence and has exactly the data-tail dimension. Every competing finite realization has at least this dimension."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("data-hankel"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.dataHankel"),
                H("Finite block Hankel windows from data"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The block at row i and column j is m(i+j). This definition has no hidden dependence on a supplied state model."))),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("data-hankel-rank-eq-tail-space"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.dataHankel_rank_eq_tailSpace"),
                H("Finite windows attain the infinite data rank"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("When both horizons are at least the tail-space dimension, the finite data Hankel range has exactly that dimension. This theorem consumes the existing stable-Hankel theorem after establishing reachability and observability of the newly constructed model."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("smaller-compression-has-future-witness"),
                DeclarationHandle.Create("D5/S3/Observer/Hankel/SequenceHankelRealization.smaller_compression_has_future_witness"),
                H("A witness against undersized linear compression"),
                StatementSource.FromLean(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Any linear compression to a strictly smaller finite-dimensional space kills some canonical state direction whose output is nonzero at a finite future time. States represent finite linear combinations of histories; no collision between two discrete input words is claimed."))),
                DescribeRole.Theorem)),
        [DocumentEdge.Dependency.Create(
            GidRef.Create("D5/S3/Observer/Hankel/HankelMinimalStateDimension"))]));
}
