using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.HardCoreHolomorphic;

internal sealed class AffineChartDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Explicit holomorphic hard-core coordinates and uniform complex neighborhoods.",
        H("AffineChart"),
        Blocks(
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-psi"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.psi"),
                H("psi"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The positive real message is extended as this affine complex polynomial."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-chart"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.chart"),
                H("chart"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A single logarithm suffices. On the positive real interval this is `log (x / (b-a*x)) / b`. The principal branch is used only on the slit plane."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-inverse"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.inverse"),
                H("inverse"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Explicit exponential inverse, valid also when `a=0`."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-center"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.center"),
                H("center"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Real center of the complex neighborhood."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-inverse-has-deriv-at"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.inverse_hasDerivAt"),
                H("inverse hasDerivAt"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The inverse has the actual complex derivative `x*(b-a*x)`."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-chart-has-deriv-at"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.chart_hasDerivAt"),
                H("chart hasDerivAt"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Actual holomorphic chart derivative, with branch and pole assumptions explicit."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-exp-center"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.exp_center"),
                H("exp center"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Exponentiating the real chart identifies the odds exactly."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-inverse-center"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.inverse_center"),
                H("inverse center"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The inverse returns every real interval point exactly."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-center-eq-chart"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.center_eq_chart"),
                H("center eq chart"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Real chart and principal complex chart agree on the positive branch."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-chart-inverse"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.chart_inverse"),
                H("chart inverse"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The inverse is two-sided on the principal branch strip. This is the local coordinate identity needed for genuine conjugation, rather than only recovery of one real anchor."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-inverse-odds"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.inverse_odds"),
                H("inverse odds"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Projective odds are multiplied by the exponential under coordinate translation. This identifies the exact representation that connects additive shifts and multiplication."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-projective"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.projective"),
                H("projective"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The fractional-linear action of the matrix `[[E,0],[k*(E-1),1]]` on its pole-free affine chart."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-projective-mul"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.projective_mul"),
                H("projective mul"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Projective flow obeys the multiplicative composition law on its pole-free chart."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-projective-matrix-defect"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.projective_matrix_defect"),
                H("projective matrix defect"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Distinct type ratios have a genuine noncommutative matrix defect. The matrices are [[E,0],[k*(E-1),1]] and [[F,0],[l*(F-1),1]]."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-affinechart-odds-amplitude-phase"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/AffineChart.odds_amplitude_phase"),
                H("odds amplitude phase"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Real shifts scale the odds modulus; imaginary shifts rotate its phase. No probability-amplitude or quantum-measurement interpretation is assumed."))), DescribeRole.Theorem))));
}
