using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.HardCoreHolomorphic;

internal sealed class NormalizedPartitionLogDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Branch-correct normalized logarithms of actual finite-grid partitions.",
        H("NormalizedPartitionLog"),
        Blocks(
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-ordered-log"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.orderedLog"),
                H("orderedLog"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Sum principal logs of the actual successive deletion ratios. The list may be partial or contain repeated/absent vertices; those cases are not silently discarded."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-ordered-log-perm"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.ordered_log_perm"),
                H("ordered log perm"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Local square flatness proves exact order independence by adjacent swaps. This does not identify the total sum with the principal logarithm of the full partition."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-ordered-log-exp"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.ordered_log_exp"),
                H("ordered log exp"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Exponentiation telescopes to the exact quotient for an arbitrary deletion list. Nonzero denominators are derived from the established common grid tube."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-ordered-log-zero"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.ordered_log_zero"),
                H("ordered log zero"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Ordered logs are normalized to zero at zero activity, without a branch choice based on a floating approximation."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-ordered-log-has-deriv-at"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.ordered_log_hasDerivAt"),
                H("ordered log hasDerivAt"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The complete differential telescopes just like the partition products. This theorem covers arbitrary partial lists and all complex points in the tube."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-normalized-log"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.normalizedLog"),
                H("normalizedLog"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A canonical value chosen using the finite set's existing list enumeration. Its agreement with every complete distinct enumeration is proved below."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-complete-order-eq"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.complete_order_eq"),
                H("complete order eq"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Every complete, repetition-free deletion list gives the same normalized value. Thus the choice of Finset.toList is not mathematical data of the result."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-normalized-log-exp"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.normalized_log_exp"),
                H("normalized log exp"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The normalized logarithm exponentiates to the actual independent-set sum."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-normalized-log-zero"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.normalized_log_zero"),
                H("normalized log zero"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Canonical normalization at the activity-zero endpoint."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-normalized-log-has-deriv-at"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.normalized_log_hasDerivAt"),
                H("normalized log hasDerivAt"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The normalized branch has precisely the actual logarithmic derivative Z'/Z."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-normalized-log-differentiable-on"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.normalized_log_differentiableOn"),
                H("normalized log differentiableOn"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Holomorphy on the original common activity neighborhood, with no new width or graph-dependent analytic-continuation premise."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-normalized-log-re"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.normalized_log_re"),
                H("normalized log re"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual real part equals log of the actual partition modulus. Only the real part, not the full complex value, is identified with the principal log."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-normalized-log-im-bound"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.normalized_log_im_bound"),
                H("normalized log im bound"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A volume-linear imaginary bound for the chosen analytic branch. This allows winding of the total partition while controlling it uniformly per vertex."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-normalized-log-delete"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.normalized_log_delete"),
                H("normalized log delete"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Exact canonical deletion recursion. The complete logarithm may accumulate phase, yet its one-vertex increment is always the local principal logarithm."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-normalizedpartitionlog-normalized-log-volume-bounds"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/NormalizedPartitionLog.normalized_log_volume_bounds"),
                H("normalized log volume bounds"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The normalized finite-volume logarithm is bounded linearly in volume, with constants independent of the domain, its boundary and the deletion order."))), DescribeRole.Theorem))));
}
