using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.HardCoreHolomorphic;

internal sealed class PartitionLogCocycleDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Branch-correct normalized logarithms of actual finite-grid partitions.",
        H("PartitionLogCocycle"),
        Blocks(
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-increment"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.increment"),
                H("increment"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Actual insertion factor, inverse to the marked vacancy when the partitions are nonzero. A missing vertex gives one on the established activity tube."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-grid-partition-differentiable"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.grid_partition_differentiable"),
                H("grid partition differentiable"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual finite independent-configuration sum is an entire function."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-grid-partition-zero"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.grid_partition_zero"),
                H("grid partition zero"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The empty configuration is the only nonzero contribution at activity zero."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-increment-halfplane"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.increment_halfplane"),
                H("increment halfplane"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The origin half-plane estimate transports to every marked vertex, including an absent vertex. No direct bound on the argument of the whole partition is used."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-increment-ne-zero"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.increment_ne_zero"),
                H("increment ne zero"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Each actual insertion factor is nonzero on the common tube."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-increment-log-im"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.increment_log_im"),
                H("increment log im"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Positivity of the real part bounds the imaginary part of the principal log. This bound is what makes two successive log increments branch-compatible."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-increment-square"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.increment_square"),
                H("increment square"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Two ordered deletion steps have the same actual product after swapping vertices. All denominator nonvanishing facts are supplied by the concrete grid theorem."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-increment-log-square"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.increment_log_square"),
                H("increment log square"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Exact additive flatness on every deletion square. The equality is in ℂ, not merely modulo 2*pi*i; the individual right-half-plane bounds prove the branch choice."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-response"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.response"),
                H("response"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The logarithmic derivative of the actual partition. It is finite at z=0 and uses no logarithm branch in its definition."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-increment-log-has-deriv-at"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.increment_log_hasDerivAt"),
                H("increment log hasDerivAt"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Differentiate the actual local principal logarithm. Its derivative is the exact difference of two actual logarithmic derivatives, enabling telescoping."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-log-partitionlogcocycle-grid-partition-norm-upper"),
                DeclarationHandle.Create("D5/S3/HardCoreHolomorphic/PartitionLogCocycle.grid_partition_norm_upper"),
                H("grid partition norm upper"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Direct configuration comparison gives a volume upper bound on the entire complex plane. This does not use the recursion or the zero-free theorem."))), DescribeRole.Theorem))));
}
