<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>StrataLint.Engine</RootNamespace>
    <AssemblyName>StrataLint.Engine</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dunet" />
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Pidgin" />
    <AdditionalFiles Include="../Architecture/BannedSymbols.txt" />
    <AdditionalFiles Include="../Architecture/BannedSymbols.Determinism.txt" />
    <AdditionalFiles Include="../Architecture/BannedSymbols.Guid.txt" />
  </ItemGroup>
</Project>
