using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Quantum.TensorNetworks.BridgeGraph;

internal sealed class ReservoirSchurDocument : IScribeDocumentDefinition
{
    private const string Owner = "D5/S3/Quantum/TensorNetworks/BridgeGraph/ReservoirSchur";
    private static Formula Parenthesized(Formula f) => Seq(Open, f, Close);
    private static Formula Qualified(string owner, string name) =>
        Qualified(F.Id(owner), Dot, F.Id(name));
    private static Formula Call(string name, params Formula[] arguments) =>
        new Formula.Apply(Seq(Operatorname, Grp(F.Id(name))), [.. arguments]);
    private static Formula Qualified(params Formula[] names) => Seq(Operatorname, Grp(names));

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "ReservoirSchur supplies the width-three bridge max-flow proof.",
        H("ReservoirSchur"), Blocks(
            Paragraph(Text("Formulas retain the Lean parameter types and all hypotheses. HDiv.hDiv and HMod.hMod are displayed infix: on natural and integer carriers they mean the respective Lean integer division and remainder operations; on rational carriers division is field division. Coe.coe denotes the coercion determined by the displayed target type. Finite and dependent-pair constructors omit proof fields, which do not change their values. A dash in a match pattern is an anonymous wildcard. CoeFun.coe and CoeSort.coe retain coercions to functions and types. All dimensions use ℕ, all construction coefficients use ℚ, and max-flow uses ℂ.")),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernelembedding"),
                DeclarationHandle.Create(Owner + ".kernelEmbedding"),
                H("kernelEmbedding"), StatementSource.FromAuthor(Disp(Statement0())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("kernelEmbedding places one alternating anti-diagonal vector in each short-long block and is zero on the other blocks; kernel_coordinates shows that these vectors parametrize the entire same-depth width-two kernel."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernelembedding-injective"),
                DeclarationHandle.Create(Owner + ".kernelEmbedding_injective"),
                H("kernelEmbedding_injective"), StatementSource.FromAuthor(Disp(Statement1())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The anti-diagonal kernel coordinates determine their embedded vector uniquely; kernelEmbedding_range combines this injectivity with the kernel dimension to identify the entire kernel."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernel-coordinates"),
                DeclarationHandle.Create(Owner + ".kernel_coordinates"),
                H("kernel_coordinates"), StatementSource.FromAuthor(Disp(Statement2())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Every vector annihilated by the same-depth widthTwoMatrix is an image of kernelEmbedding; LongReservoir.single_update_injective uses this parametrization to reduce the added-slice equation to the kernel coordinates."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-cokernelembedding"),
                DeclarationHandle.Create(Owner + ".cokernelEmbedding"),
                H("cokernelEmbedding"), StatementSource.FromAuthor(Disp(Statement3())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("cokernelEmbedding places transposed alternating anti-diagonal vectors in the long-short output blocks; cokernelMatrix_mul_widthTwo shows that the associated coordinate projection annihilates the width-two matrix."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernelmatrix-mulvec"),
                DeclarationHandle.Create(Owner + ".kernelMatrix_mulVec"),
                H("kernelMatrix_mulVec"), StatementSource.FromAuthor(Disp(Statement4())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Multiplying by the matrix of kernelEmbedding gives the embedded kernel vector; LongReservoir.single_update_injective uses this to apply the kernel sampling identity to its parametrized input."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-cokernelmatrix-mul-widthtwo"),
                DeclarationHandle.Create(Owner + ".cokernelMatrix_mul_widthTwo"),
                H("cokernelMatrix_mul_widthTwo"), StatementSource.FromAuthor(Disp(Statement5())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The transpose of the matrix of cokernelEmbedding annihilates widthTwoMatrix; short_reservoir_injective uses this projection to remove the original width-two term from the augmented flow equation."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernelsample"),
                DeclarationHandle.Create(Owner + ".kernelSample"),
                H("kernelSample"), StatementSource.FromAuthor(Disp(Statement6())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("kernelSample chooses coordinates zero and p in each short-long input block; kernel_sample_identity shows that sampling at these positions recovers the kernel coefficients."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-cokernelsample"),
                DeclarationHandle.Create(Owner + ".cokernelSample"),
                H("cokernelSample"), StatementSource.FromAuthor(Disp(Statement7())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("cokernelSample chooses coordinates p and zero in each long-short output block; cokernel_sample_identity shows that insertion at these positions is a right inverse of the cokernel projection."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernel-sample-identity"),
                DeclarationHandle.Create(Owner + ".kernel_sample_identity"),
                H("kernel_sample_identity"), StatementSource.FromAuthor(Disp(Statement8())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Sampling an embedded anti-diagonal kernel vector returns its coefficient vector; LongReservoir.single_update_injective uses this identity to reduce the added slice to a map on the kernel coefficients."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-cokernel-sample-identity"),
                DeclarationHandle.Create(Owner + ".cokernel_sample_identity"),
                H("cokernel_sample_identity"), StatementSource.FromAuthor(Disp(Statement9())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Inserting a vector at the cokernel sample positions and then applying the cokernel projection returns that vector; LongReservoir.single_update_injective uses this to read the added slice in cokernel coordinates."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-singlecross"),
                DeclarationHandle.Create(Owner + ".singleCross"),
                H("singleCross"), StatementSource.FromAuthor(Disp(Statement10())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("singleCross inserts the Kronecker map BM⊗DM between the kernel sample positions and the cokernel sample positions; LongReservoir.single_update_injective uses this map to remove the width-two kernel."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-inclusion-prod"),
                DeclarationHandle.Create(Owner + ".inclusion_prod"),
                H("inclusion_prod"), StatementSource.FromAuthor(Disp(Statement11())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Coordinate insertion along a product of two maps is the Kronecker product of their insertion matrices; singleCross_kronecker uses this factorization to express the added matrix as one tensor slice."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-shortzerocol"),
                DeclarationHandle.Create(Owner + ".shortZeroCol"),
                H("shortZeroCol"), StatementSource.FromAuthor(Disp(Statement12())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("shortZeroCol selects column zero in each short block; singleThirdLeft uses these columns to read the kernel sample coordinates."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-longlastrow"),
                DeclarationHandle.Create(Owner + ".longLastRow"),
                H("longLastRow"), StatementSource.FromAuthor(Disp(Statement13())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("longLastRow selects row p in each long block; singleThirdLeft uses these rows to insert the transformed coefficients into the cokernel sample positions."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-singlethirdleft"),
                DeclarationHandle.Create(Owner + ".singleThirdLeft"),
                H("singleThirdLeft"), StatementSource.FromAuthor(Disp(Statement16())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("singleThirdLeft applies BM from the zero columns of the short blocks to the final rows of the long blocks; singleCross_kronecker uses it as the left factor of the third tensor slice."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-singlethirdright"),
                DeclarationHandle.Create(Owner + ".singleThirdRight"),
                H("singleThirdRight"), StatementSource.FromAuthor(Disp(Statement17())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("singleThirdRight applies DM from the final rows of the long blocks to the zero columns of the short blocks in the second factor; singleCross_kronecker uses it as the right factor of the third tensor slice."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-singlecross-kronecker"),
                DeclarationHandle.Create(Owner + ".singleCross_kronecker"),
                H("singleCross_kronecker"), StatementSource.FromAuthor(Disp(Statement18())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The update singleCross is the Kronecker product of singleThirdLeft and singleThirdRight; LongReservoir.single_reversal_injective_witness uses this equality to realize the kernel-removing update as a third bond slice."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-localsource"),
                DeclarationHandle.Create(Owner + ".localSource"),
                H("localSource"), StatementSource.FromAuthor(Disp(Statement19())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("localSource restricts the input vector to one pair of shift blocks; widthTwo_mulVec_block uses this restriction to express each block equation as a rectangular pencil equation."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-widthtwo-mulvec-block"),
                DeclarationHandle.Create(Owner + ".widthTwo_mulVec_block"),
                H("widthTwo_mulVec_block"), StatementSource.FromAuthor(Disp(Statement20())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("On any pair of blocks, multiplication by widthTwoMatrix equals pencil multiplication on localSource; sourceSL_kernel_of_updated_zero uses this to isolate the short-long kernel equations."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-sourcesl"),
                DeclarationHandle.Create(Owner + ".sourceSL"),
                H("sourceSL"), StatementSource.FromAuthor(Disp(Statement21())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("sourceSL keeps the short-long input blocks and sets all other blocks to zero; sourceSL_kernelEmbedding shows that this projection fixes every vector in the parametrized kernel."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-slline"),
                DeclarationHandle.Create(Owner + ".slLine"),
                H("slLine"), StatementSource.FromAuthor(Disp(Statement22())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("slLine reads the short-long input blocks at the coordinate pair (p-r,p-t); slLine_kernelEmbedding computes this array for an embedded anti-diagonal vector."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-cokernel-mulvec-formula"),
                DeclarationHandle.Create(Owner + ".cokernel_mulVec_formula"),
                H("cokernel_mulVec_formula"), StatementSource.FromAuthor(Disp(Statement23())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The cokernel projection is the displayed alternating sum along each long-short anti-diagonal; cokernel_reservoir_kernel uses this formula to compute the reservoir contribution in cokernel coordinates."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-slline-kernelembedding"),
                DeclarationHandle.Create(Owner + ".slLine_kernelEmbedding"),
                H("slLine_kernelEmbedding"), StatementSource.FromAuthor(Disp(Statement24())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For an embedded kernel vector, slLine vanishes unless r+t=p and otherwise equals the coefficient vector multiplied by the displayed sign; cokernel_reservoir_kernel uses this to compute the projected added slice."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-sourcesl-kernelembedding"),
                DeclarationHandle.Create(Owner + ".sourceSL_kernelEmbedding"),
                H("sourceSL_kernelEmbedding"), StatementSource.FromAuthor(Disp(Statement25())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The short-long block projection fixes every image of kernelEmbedding; short_reservoir_injective uses this identity to recover the full kernel vector from the vanishing short-long component."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-short-short-witness"),
                DeclarationHandle.Create(Owner + ".short_short_witness"),
                H("short_short_witness"), StatementSource.FromAuthor(Disp(Statement26())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For p > 0, 0 < beta ≤ alpha and 0 < delta ≤ gamma, the short reservoir construction yields rational three-slice matrices attaining the outer cut by eliminating the kernel through its Schur complement. LongReservoir.parameterized_base_witness applies this in the equal-depth case with these multiplicity orderings."))),
                DescribeRole.Theorem))));

    private static Formula Statement0() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("w"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp, Parenthesized(Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("kernelEmbedding")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, F.Id("w"), Sp, F.Id("u"), Sp, Eq, Sp, Parenthesized(Seq(F.Id("match"), Sp, F.Id("u"), Sp,
        Dot, Sp, D(1), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, D(2), Sp, F.Id("with"), Sp, Bar, Sp, Seq(Langle, Sp,
        Seq(Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, F.Id("i"), Sp, Comma, Sp, F.Id("s")), Sp, Rangle), Sp,
        Comma, Sp, Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp, F.Id("h"), Sp, Comma, Sp,
        F.Id("j")), Sp, Rangle), Sp, Mapsto, Sp, F.Id("w"), Sp, Parenthesized(Seq(F.Id("i"), Sp, Comma, Sp,
        F.Id("h"))), Sp, Cdot, Sp, Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("antiDiagonal")), Sp, F.Id("p"), Sp,
        Parenthesized(Seq(F.Id("s"), Sp, Comma, Sp, F.Id("j"))), Sp, Bar, Sp, Minus, Sp, Comma, Sp, Minus, Sp, Mapsto,
        Sp, D(0))));

    private static Formula Statement1() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Qualified(F.Id("Function"), Dot,
        F.Id("Injective")), Sp, Parenthesized(new Formula.Apply(Qualified("CoeFun", "coe"),
        [Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))])));

    private static Formula Statement2() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp,
        Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp,
        Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("Q"))))),
        Sp, Comma, Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("widthTwoMatrix")), Sp,
        F.Id("p"), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp,
        Dot, Sp, F.Id("mulVec"), Sp, F.Id("u"), Sp, Eq, Sp, D(0), Sp, To, Sp, Exists, Sp, Parenthesized(Seq(F.Id("w"),
        Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"), Sp, To, Sp,
        Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Comma, Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("kernelEmbedding")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"))), Sp, F.Id("w"), Sp, Eq, Sp, F.Id("u"));

    private static Formula Statement3() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("w"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("beta"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("gamma"), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp, Parenthesized(Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t")))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1))))))), Sp, Comma, Sp,
        Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelEmbedding")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("w"), Sp, F.Id("u"), Sp, Eq, Sp,
        Parenthesized(Seq(F.Id("match"), Sp, F.Id("u"), Sp, Dot, Sp, D(1), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp,
        D(2), Sp, F.Id("with"), Sp, Bar, Sp, Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp,
        F.Id("k"), Sp, Comma, Sp, F.Id("s")), Sp, Rangle), Sp, Comma, Sp, Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"),
        Dot, F.Id("inl")), Sp, F.Id("j"), Sp, Comma, Sp, F.Id("t")), Sp, Rangle), Sp, Mapsto, Sp, F.Id("w"), Sp,
        Parenthesized(Seq(F.Id("k"), Sp, Comma, Sp, F.Id("j"))), Sp, Cdot, Sp, Qualified(F.Id("ShiftPencilBlocks"),
        Dot, F.Id("antiDiagonal")), Sp, F.Id("p"), Sp, Parenthesized(Seq(Parenthesized(Seq(F.Id("s"), Sp, Comma, Sp,
        F.Id("t"))), Sp, Dot, Sp, D(2), Sp, Comma, Sp, Parenthesized(Seq(F.Id("s"), Sp, Comma, Sp, F.Id("t"))), Sp,
        Dot, Sp, D(1))), Sp, Bar, Sp, Minus, Sp, Comma, Sp, Minus, Sp, Mapsto, Sp, D(0))));

    private static Formula Statement4() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("w"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Comma, Sp, Parenthesized(Seq(Qualified(F.Id("LinearMap"), Dot, F.Id("toMatrix")), Sp,
        Apos, Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp, F.Id("p"),
        Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp, F.Id("mulVec"),
        Sp, F.Id("w"), Sp, Eq, Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")),
        Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, F.Id("w"));

    private static Formula Statement5() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp,
        Parenthesized(Seq(Qualified(F.Id("LinearMap"), Dot, F.Id("toMatrix")), Sp, Apos, Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelEmbedding")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp, F.Id("transpose"), Sp,
        Cdot, Sp, Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("widthTwoMatrix")), Sp, F.Id("p"), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, Eq, Sp, D(0));

    private static Formula Statement6() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("t"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"))), Sp, Comma, Sp,
        Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelSample")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"), Sp, Eq, Sp,
        Parenthesized(Parenthesized(Seq(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, F.Id("t"),
        Sp, Dot, Sp, D(1), Sp, Comma, Sp, Seq(Langle, Sp, D(0), Sp, Rangle)), Sp, Rangle), Sp, Comma, Sp, Seq(Langle,
        Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp, F.Id("t"), Sp, Dot, Sp, D(2), Sp, Comma, Sp, Seq(Langle,
        Sp, F.Id("p"), Sp, Rangle)), Sp, Rangle)))));

    private static Formula Statement7() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("t"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("beta"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Comma, Sp,
        Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelSample")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"), Sp, Eq, Sp,
        Parenthesized(Parenthesized(Seq(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp, F.Id("t"),
        Sp, Dot, Sp, D(1), Sp, Comma, Sp, Seq(Langle, Sp, F.Id("p"), Sp, Rangle)), Sp, Rangle), Sp, Comma, Sp,
        Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, F.Id("t"), Sp, Dot, Sp, D(2), Sp, Comma, Sp,
        Seq(Langle, Sp, D(0), Sp, Rangle)), Sp, Rangle)))));

    private static Formula Statement8() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelSample")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp, F.Id("transpose"), Sp,
        Cdot, Sp, Qualified(F.Id("LinearMap"), Dot, F.Id("toMatrix")), Sp, Apos, Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, Eq, Sp, D(1));

    private static Formula Statement9() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp,
        Parenthesized(Seq(Qualified(F.Id("LinearMap"), Dot, F.Id("toMatrix")), Sp, Apos, Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelEmbedding")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp, F.Id("transpose"), Sp,
        Cdot, Sp, Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelSample")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, Eq, Sp, D(1));

    private static Formula Statement10() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("BM"), Sp, Colon, Sp,
        F.Id("Matrix"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("DM"), Sp, Colon, Sp,
        F.Id("Matrix"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("delta"))), Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("singleCross")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, F.Id("BM"), Sp, F.Id("DM"), Sp, Eq, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelSample")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, Cdot, Sp, Qualified(F.Id("BM"),
        Dot, F.Id("kronecker")), Sp, F.Id("DM"), Sp, Cdot, Sp, Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"),
        Dot, F.Id("inclusion")), Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelSample")),
        Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp,
        F.Id("transpose"))));

    private static Formula Statement11() =>
        Seq(Forall, Sp, Seq(OpenBrace, Seq(F.Id("m"), Sp, Colon, Sp, F.Id("Type")), CloseBrace), Sp, Seq(OpenBrace,
        Seq(F.Id("n"), Sp, Colon, Sp, F.Id("Type")), CloseBrace), Sp, Seq(OpenBrace, Seq(F.Id("r"), Sp, Colon, Sp,
        F.Id("Type")), CloseBrace), Sp, Seq(OpenBrace, Seq(F.Id("s"), Sp, Colon, Sp, F.Id("Type")), CloseBrace), Sp,
        Seq(OpenBracket, Seq(F.Id("DecidableEq"), Sp, F.Id("m")), CloseBracket), Sp, Seq(OpenBracket,
        Seq(F.Id("DecidableEq"), Sp, F.Id("r")), CloseBracket), Sp, Parenthesized(Seq(F.Id("e"), Sp, Colon, Sp,
        F.Id("n"), Sp, To, Sp, F.Id("m"))), Sp, Parenthesized(Seq(F.Id("f"), Sp, Colon, Sp, F.Id("s"), Sp, To, Sp,
        F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        F.Id("fun"), Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp, F.Id("n"), Sp, Times, Sp, F.Id("s"))), Sp,
        Mapsto, Sp, Parenthesized(Seq(F.Id("e"), Sp, F.Id("k"), Sp, Dot, Sp, D(1), Sp, Comma, Sp, F.Id("f"), Sp,
        F.Id("k"), Sp, Dot, Sp, D(2))))), Sp, Eq, Sp, Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot,
        F.Id("inclusion")), Sp, F.Id("e"))), Sp, Dot, Sp, F.Id("kronecker"), Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp, F.Id("f"))));

    private static Formula Statement12() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, Colon, Sp, Seq(Mathbb,
        Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("alpha"))), Sp,
        Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot, F.Id("shortZeroCol")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("i"), Sp, Eq, Sp, Parenthesized(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot,
        F.Id("inl")), Sp, F.Id("i"), Sp, Comma, Sp, Seq(Langle, Sp, D(0), Sp, Rangle)), Sp, Rangle)));

    private static Formula Statement13() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, Colon, Sp, Seq(Mathbb,
        Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("beta"))), Sp, Comma,
        Sp, Qualified(F.Id("ReservoirSchur"), Dot, F.Id("longLastRow")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("k"), Sp, Eq, Sp, Parenthesized(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot,
        F.Id("inr")), Sp, F.Id("k"), Sp, Comma, Sp, Seq(Langle, Sp, F.Id("p"), Sp, Rangle)), Sp, Rangle)));

    private static Formula Statement16() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, Colon, Sp, Seq(Mathbb,
        Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("BM"), Sp, Colon, Sp, F.Id("Matrix"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp,
        Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot, F.Id("singleThirdLeft")),
        Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("BM"), Sp, Eq, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("longLastRow")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"))), Sp, Cdot, Sp, F.Id("BM"), Sp, Cdot, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("shortZeroCol")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"))))), Sp, Dot, Sp, F.Id("transpose"))));

    private static Formula Statement17() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb,
        Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("DM"), Sp, Colon, Sp, F.Id("Matrix"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))),
        Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("singleThirdRight")), Sp, F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("DM"), Sp, Eq, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("shortZeroCol")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"))), Sp, Cdot, Sp, F.Id("DM"), Sp, Cdot, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("longLastRow")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp, F.Id("transpose"))));

    private static Formula Statement18() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("BM"), Sp, Colon, Sp,
        F.Id("Matrix"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("DM"), Sp, Colon, Sp,
        F.Id("Matrix"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("delta"))), Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("singleCross")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, F.Id("BM"), Sp, F.Id("DM"), Sp, Eq, Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"),
        Dot, F.Id("singleThirdLeft")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("BM"))), Sp, Dot,
        Sp, F.Id("kronecker"), Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("singleThirdRight")),
        Sp, F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("DM"))));

    private static Formula Statement19() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("q"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp,
        Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp, Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma,
        Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("q"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp,
        Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, Parenthesized(Seq(F.Id("j"), Sp,
        Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("i"), Sp, Plus, Sp, D(1))), Sp, Times, Sp,
        F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("q"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("j"))))), Sp, Comma, Sp,
        Qualified(F.Id("ReservoirSchur"), Dot, F.Id("localSource")), Sp, F.Id("p"), Sp, F.Id("q"), Sp, F.Id("alpha"),
        Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("u"), Sp, F.Id("i"), Sp, F.Id("j"), Sp,
        F.Id("k"), Sp, Eq, Sp, Parenthesized(Seq(F.Id("u"), Sp, Parenthesized(Seq(Seq(Langle, Sp, Seq(F.Id("i"), Sp,
        Comma, Sp, F.Id("k"), Sp, Dot, Sp, D(1)), Sp, Rangle), Sp, Comma, Sp, Seq(Langle, Sp, Seq(F.Id("j"), Sp,
        Comma, Sp, F.Id("k"), Sp, Dot, Sp, D(2)), Sp, Rangle))))));

    private static Formula Statement20() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("q"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp,
        Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp, Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma,
        Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("q"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp,
        Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, Parenthesized(Seq(F.Id("j"), Sp,
        Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, Parenthesized(Seq(F.Id("s"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("i"))))), Sp, Parenthesized(Seq(F.Id("t"), Sp, Colon,
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("q"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("j"), Sp, Plus, Sp, D(1))))), Sp, Comma, Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("widthTwoMatrix")), Sp, F.Id("p"), Sp,
        F.Id("q"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, Dot, Sp,
        F.Id("mulVec"), Sp, F.Id("u"), Sp, Parenthesized(Seq(Seq(Langle, Sp, Seq(F.Id("i"), Sp, Comma, Sp, F.Id("s")),
        Sp, Rangle), Sp, Comma, Sp, Seq(Langle, Sp, Seq(F.Id("j"), Sp, Comma, Sp, F.Id("t")), Sp, Rangle))), Sp, Eq,
        Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("pencil")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("i"))), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"),
        Dot, F.Id("blockLength")), Sp, F.Id("q"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("j"))))), Sp, Dot,
        Sp, F.Id("mulVec"), Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("localSource")), Sp,
        F.Id("p"), Sp, F.Id("q"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp,
        F.Id("u"), Sp, F.Id("i"), Sp, F.Id("j"))), Sp, Parenthesized(Seq(F.Id("s"), Sp, Comma, Sp, F.Id("t"))));

    private static Formula Statement21() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp,
        Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp,
        Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("Q"))))),
        Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp, Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma,
        Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("sourceSL")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"),
        Sp, F.Id("u"), Sp, F.Id("k"), Sp, Eq, Sp, Parenthesized(Seq(F.Id("match"), Sp, F.Id("k"), Sp, Dot, Sp, D(1),
        Sp, Dot, Sp, F.Id("fst"), Sp, Comma, Sp, F.Id("k"), Sp, Dot, Sp, D(2), Sp, Dot, Sp, F.Id("fst"), Sp,
        F.Id("with"), Sp, Bar, Sp, Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, Minus, Sp, Comma, Sp,
        Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp, Minus, Sp, Mapsto, Sp, F.Id("u"), Sp, F.Id("k"), Sp, Bar, Sp,
        Minus, Sp, Comma, Sp, Minus, Sp, Mapsto, Sp, D(0))));

    private static Formula Statement22() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp,
        Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp,
        Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("Q"))))),
        Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("t"), Sp, Colon, Sp, F.Id("Fin"), Sp, Parenthesized(Seq(F.Id("p"),
        Sp, Plus, Sp, D(1))))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("alpha"), Sp,
        Times, Sp, F.Id("Fin"), Sp, F.Id("delta"))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("slLine")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp,
        F.Id("u"), Sp, F.Id("r"), Sp, F.Id("t"), Sp, F.Id("k"), Sp, Eq, Sp, Parenthesized(Seq(F.Id("u"), Sp,
        Parenthesized(Seq(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, F.Id("k"), Sp, Dot, Sp,
        D(1), Sp, Comma, Sp, Seq(Langle, Sp, Seq(F.Id("p"), Sp, Minus, Sp, Parenthesized(Call("val", F.Id("r")))), Sp, Rangle)), Sp, Rangle), Sp, Comma, Sp, Seq(Langle,
        Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp, F.Id("k"), Sp, Dot, Sp, D(2), Sp, Comma, Sp, Seq(Langle,
        Sp, Seq(F.Id("p"), Sp, Minus, Sp, Parenthesized(Call("val", F.Id("t")))), Sp,
        Rangle)), Sp, Rangle))))));

    private static Formula Statement23() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("z"), Sp, Colon, Sp,
        Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t")))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1))))), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("beta"))), Sp,
        Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Comma, Sp,
        Parenthesized(Seq(Qualified(F.Id("LinearMap"), Dot, F.Id("toMatrix")), Sp, Apos, Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelEmbedding")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp,
        Qualified(F.Id("transpose"), Dot, F.Id("mulVec")), Sp, F.Id("z"), Sp, Parenthesized(Seq(F.Id("k"), Sp, Comma,
        Sp, F.Id("j"))), Sp, Eq, Sp, Seq(new Formula.Subscript(Sum, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(F.Id("p"), Sp, Plus, Sp, D(1))))), Sp, Parenthesized(Seq(new
        Formula.Power(Parenthesized(Seq(Minus, Sp, D(1))), Call("val", F.Id("t"))), Sp, Cdot, Sp, F.Id("z"), Sp, Parenthesized(Seq(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot,
        F.Id("inr")), Sp, F.Id("k"), Sp, Comma, Sp, Seq(Langle, Sp, Seq(F.Id("p"), Sp, Minus, Sp, Parenthesized(Call("val", F.Id("t")))), Sp, Rangle)), Sp, Rangle), Sp, Comma, Sp, Seq(Langle,
        Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, F.Id("j"), Sp, Comma, Sp, F.Id("t")), Sp, Rangle)))))));

    private static Formula Statement24() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("w"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("t"), Sp, Colon, Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(F.Id("p"), Sp, Plus, Sp, D(1))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("slLine")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp,
        Parenthesized(Seq(Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, F.Id("w"))), Sp,
        F.Id("r"), Sp, F.Id("t"), Sp, Eq, Sp, F.Id("if"), Sp, Parenthesized(Call("val", F.Id("r"))), Sp, Plus, Sp, Parenthesized(Call("val", F.Id("t"))), Sp, Eq,
        Sp, F.Id("p"), Sp, F.Id("then"), Sp, new Formula.Power(Parenthesized(Seq(Minus, Sp, D(1))), Seq(F.Id("p"), Sp,
        Minus, Sp, Parenthesized(Call("val", F.Id("r"))))), Sp, Cdot, Sp, F.Id("w"),
        Sp, F.Id("else"), Sp, D(0));

    private static Formula Statement25() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("w"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot, F.Id("sourceSL")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp,
        Parenthesized(Seq(Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, F.Id("w"))), Sp,
        Eq, Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, F.Id("w"));

    private static Formula Statement26() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, D(0), Sp, F.Lt, Sp, F.Id("p"), Sp,
        To, Sp, D(0), Sp, F.Lt, Sp, F.Id("beta"), Sp, To, Sp, F.Id("beta"), Sp, Leq, Sp, F.Id("alpha"), Sp, To, Sp,
        D(0), Sp, F.Lt, Sp, F.Id("delta"), Sp, To, Sp, F.Id("delta"), Sp, Leq, Sp, F.Id("gamma"), Sp, To, Sp,
        Qualified(F.Id("QuantumMaxFlowBound"), Dot, F.Id("RationalWitness")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("leftDim")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"))), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot,
        F.Id("rightDim")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"))), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("leftDim")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"))), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot,
        F.Id("rightDim")), Sp, F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"))));

}
