using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Quantum.TensorNetworks.BridgeGraph;

internal sealed class ReservoirSchurDocument : IScribeDocumentDefinition
{
    private const string Owner = "D5/S3/Quantum/TensorNetworks/BridgeGraph/ReservoirSchur";
    private static Formula Parenthesized(Formula f) => Seq(Open, f, Close);
    private static Formula Qualified(string owner, string name) =>
        Qualified(F.Id(owner), Dot, F.Id(name));
    private static Formula Call(string name, params Formula[] arguments) =>
        new Formula.Apply(Seq(Operatorname, Grp(F.Id(name))), [.. arguments]);
    private static Formula Qualified(params Formula[] names) => Seq(Operatorname, Grp(names));

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "ReservoirSchur supplies the width-three bridge max-flow proof.",
        H("ReservoirSchur"), Blocks(
            Paragraph(Text("Formulas retain the Lean parameter types and all hypotheses. HDiv.hDiv and HMod.hMod are displayed infix: on natural and integer carriers they mean the respective Lean integer division and remainder operations; on rational carriers division is field division. Coe.coe denotes the coercion determined by the displayed target type. Finite and dependent-pair constructors omit proof fields, which do not change their values. A dash in a match pattern is an anonymous wildcard. CoeFun.coe and CoeSort.coe retain coercions to functions and types. All dimensions use ℕ, all construction coefficients use ℚ, and max-flow uses ℂ.")),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernelembedding"),
                DeclarationHandle.Create(Owner + ".kernelEmbedding"),
                H("kernelEmbedding"), StatementSource.FromAuthor(Disp(Statement0())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes kernelEmbedding for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernelembedding-injective"),
                DeclarationHandle.Create(Owner + ".kernelEmbedding_injective"),
                H("kernelEmbedding_injective"), StatementSource.FromAuthor(Disp(Statement1())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("kernelEmbedding_injective is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernel-coordinates"),
                DeclarationHandle.Create(Owner + ".kernel_coordinates"),
                H("kernel_coordinates"), StatementSource.FromAuthor(Disp(Statement2())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("kernel_coordinates is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-cokernelembedding"),
                DeclarationHandle.Create(Owner + ".cokernelEmbedding"),
                H("cokernelEmbedding"), StatementSource.FromAuthor(Disp(Statement3())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes cokernelEmbedding for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernelmatrix-mulvec"),
                DeclarationHandle.Create(Owner + ".kernelMatrix_mulVec"),
                H("kernelMatrix_mulVec"), StatementSource.FromAuthor(Disp(Statement4())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("kernelMatrix_mulVec is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-cokernelmatrix-mul-widthtwo"),
                DeclarationHandle.Create(Owner + ".cokernelMatrix_mul_widthTwo"),
                H("cokernelMatrix_mul_widthTwo"), StatementSource.FromAuthor(Disp(Statement5())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("cokernelMatrix_mul_widthTwo is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernelsample"),
                DeclarationHandle.Create(Owner + ".kernelSample"),
                H("kernelSample"), StatementSource.FromAuthor(Disp(Statement6())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes kernelSample for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-cokernelsample"),
                DeclarationHandle.Create(Owner + ".cokernelSample"),
                H("cokernelSample"), StatementSource.FromAuthor(Disp(Statement7())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes cokernelSample for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-kernel-sample-identity"),
                DeclarationHandle.Create(Owner + ".kernel_sample_identity"),
                H("kernel_sample_identity"), StatementSource.FromAuthor(Disp(Statement8())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("kernel_sample_identity is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-cokernel-sample-identity"),
                DeclarationHandle.Create(Owner + ".cokernel_sample_identity"),
                H("cokernel_sample_identity"), StatementSource.FromAuthor(Disp(Statement9())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("cokernel_sample_identity is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-singlecross"),
                DeclarationHandle.Create(Owner + ".singleCross"),
                H("singleCross"), StatementSource.FromAuthor(Disp(Statement10())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes singleCross for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-inclusion-prod"),
                DeclarationHandle.Create(Owner + ".inclusion_prod"),
                H("inclusion_prod"), StatementSource.FromAuthor(Disp(Statement11())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("inclusion_prod is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-shortzerocol"),
                DeclarationHandle.Create(Owner + ".shortZeroCol"),
                H("shortZeroCol"), StatementSource.FromAuthor(Disp(Statement12())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes shortZeroCol for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-longlastrow"),
                DeclarationHandle.Create(Owner + ".longLastRow"),
                H("longLastRow"), StatementSource.FromAuthor(Disp(Statement13())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes longLastRow for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-singlethirdleft"),
                DeclarationHandle.Create(Owner + ".singleThirdLeft"),
                H("singleThirdLeft"), StatementSource.FromAuthor(Disp(Statement16())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes singleThirdLeft for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-singlethirdright"),
                DeclarationHandle.Create(Owner + ".singleThirdRight"),
                H("singleThirdRight"), StatementSource.FromAuthor(Disp(Statement17())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes singleThirdRight for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-singlecross-kronecker"),
                DeclarationHandle.Create(Owner + ".singleCross_kronecker"),
                H("singleCross_kronecker"), StatementSource.FromAuthor(Disp(Statement18())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("singleCross_kronecker is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-localsource"),
                DeclarationHandle.Create(Owner + ".localSource"),
                H("localSource"), StatementSource.FromAuthor(Disp(Statement19())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes localSource for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-widthtwo-mulvec-block"),
                DeclarationHandle.Create(Owner + ".widthTwo_mulVec_block"),
                H("widthTwo_mulVec_block"), StatementSource.FromAuthor(Disp(Statement20())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("widthTwo_mulVec_block is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-sourcesl"),
                DeclarationHandle.Create(Owner + ".sourceSL"),
                H("sourceSL"), StatementSource.FromAuthor(Disp(Statement21())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes sourceSL for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-slline"),
                DeclarationHandle.Create(Owner + ".slLine"),
                H("slLine"), StatementSource.FromAuthor(Disp(Statement22())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The defining expression fixes slLine for the consumed ReservoirSchur construction."))),
                DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-cokernel-mulvec-formula"),
                DeclarationHandle.Create(Owner + ".cokernel_mulVec_formula"),
                H("cokernel_mulVec_formula"), StatementSource.FromAuthor(Disp(Statement23())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("cokernel_mulVec_formula is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-slline-kernelembedding"),
                DeclarationHandle.Create(Owner + ".slLine_kernelEmbedding"),
                H("slLine_kernelEmbedding"), StatementSource.FromAuthor(Disp(Statement24())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("slLine_kernelEmbedding is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-sourcesl-kernelembedding"),
                DeclarationHandle.Create(Owner + ".sourceSL_kernelEmbedding"),
                H("sourceSL_kernelEmbedding"), StatementSource.FromAuthor(Disp(Statement25())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("sourceSL_kernelEmbedding is used on the live proof path of the width-three bridge construction."))),
                DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("gls-reservoirschur-short-short-witness"),
                DeclarationHandle.Create(Owner + ".short_short_witness"),
                H("short_short_witness"), StatementSource.FromAuthor(Disp(Statement26())),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The short reservoir construction resolves the strict same-depth case with alpha*delta ≤ beta*gamma, using its higher-order Schur complement."))),
                DescribeRole.Theorem))));

    private static Formula Statement0() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("w"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp, Parenthesized(Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("kernelEmbedding")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, F.Id("w"), Sp, F.Id("u"), Sp, Eq, Sp, Parenthesized(Seq(F.Id("match"), Sp, F.Id("u"), Sp,
        Dot, Sp, D(1), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, D(2), Sp, F.Id("with"), Sp, Bar, Sp, Seq(Langle, Sp,
        Seq(Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, F.Id("i"), Sp, Comma, Sp, F.Id("s")), Sp, Rangle), Sp,
        Comma, Sp, Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp, F.Id("h"), Sp, Comma, Sp,
        F.Id("j")), Sp, Rangle), Sp, Mapsto, Sp, F.Id("w"), Sp, Parenthesized(Seq(F.Id("i"), Sp, Comma, Sp,
        F.Id("h"))), Sp, Cdot, Sp, Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("antiDiagonal")), Sp, F.Id("p"), Sp,
        Parenthesized(Seq(F.Id("s"), Sp, Comma, Sp, F.Id("j"))), Sp, Bar, Sp, Minus, Sp, Comma, Sp, Minus, Sp, Mapsto,
        Sp, D(0))));

    private static Formula Statement1() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Qualified(F.Id("Function"), Dot,
        F.Id("Injective")), Sp, Parenthesized(new Formula.Apply(Qualified("CoeFun", "coe"),
        [Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))])));

    private static Formula Statement2() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp,
        Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp,
        Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("Q"))))),
        Sp, Comma, Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("widthTwoMatrix")), Sp,
        F.Id("p"), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp,
        Dot, Sp, F.Id("mulVec"), Sp, F.Id("u"), Sp, Eq, Sp, D(0), Sp, To, Sp, Exists, Sp, Parenthesized(Seq(F.Id("w"),
        Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"), Sp, To, Sp,
        Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Comma, Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("kernelEmbedding")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"))), Sp, F.Id("w"), Sp, Eq, Sp, F.Id("u"));

    private static Formula Statement3() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("w"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("beta"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("gamma"), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp, Parenthesized(Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t")))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1))))))), Sp, Comma, Sp,
        Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelEmbedding")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("w"), Sp, F.Id("u"), Sp, Eq, Sp,
        Parenthesized(Seq(F.Id("match"), Sp, F.Id("u"), Sp, Dot, Sp, D(1), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp,
        D(2), Sp, F.Id("with"), Sp, Bar, Sp, Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp,
        F.Id("k"), Sp, Comma, Sp, F.Id("s")), Sp, Rangle), Sp, Comma, Sp, Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"),
        Dot, F.Id("inl")), Sp, F.Id("j"), Sp, Comma, Sp, F.Id("t")), Sp, Rangle), Sp, Mapsto, Sp, F.Id("w"), Sp,
        Parenthesized(Seq(F.Id("k"), Sp, Comma, Sp, F.Id("j"))), Sp, Cdot, Sp, Qualified(F.Id("ShiftPencilBlocks"),
        Dot, F.Id("antiDiagonal")), Sp, F.Id("p"), Sp, Parenthesized(Seq(Parenthesized(Seq(F.Id("s"), Sp, Comma, Sp,
        F.Id("t"))), Sp, Dot, Sp, D(2), Sp, Comma, Sp, Parenthesized(Seq(F.Id("s"), Sp, Comma, Sp, F.Id("t"))), Sp,
        Dot, Sp, D(1))), Sp, Bar, Sp, Minus, Sp, Comma, Sp, Minus, Sp, Mapsto, Sp, D(0))));

    private static Formula Statement4() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("w"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Comma, Sp, Parenthesized(Seq(Qualified(F.Id("LinearMap"), Dot, F.Id("toMatrix")), Sp,
        Apos, Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp, F.Id("p"),
        Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp, F.Id("mulVec"),
        Sp, F.Id("w"), Sp, Eq, Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")),
        Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, F.Id("w"));

    private static Formula Statement5() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp,
        Parenthesized(Seq(Qualified(F.Id("LinearMap"), Dot, F.Id("toMatrix")), Sp, Apos, Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelEmbedding")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp, F.Id("transpose"), Sp,
        Cdot, Sp, Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("widthTwoMatrix")), Sp, F.Id("p"), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, Eq, Sp, D(0));

    private static Formula Statement6() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("t"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"))), Sp, Comma, Sp,
        Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelSample")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"), Sp, Eq, Sp,
        Parenthesized(Parenthesized(Seq(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, F.Id("t"),
        Sp, Dot, Sp, D(1), Sp, Comma, Sp, Seq(Langle, Sp, D(0), Sp, Rangle)), Sp, Rangle), Sp, Comma, Sp, Seq(Langle,
        Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp, F.Id("t"), Sp, Dot, Sp, D(2), Sp, Comma, Sp, Seq(Langle,
        Sp, F.Id("p"), Sp, Rangle)), Sp, Rangle)))));

    private static Formula Statement7() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("t"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("beta"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Comma, Sp,
        Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelSample")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"), Sp, Eq, Sp,
        Parenthesized(Parenthesized(Seq(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp, F.Id("t"),
        Sp, Dot, Sp, D(1), Sp, Comma, Sp, Seq(Langle, Sp, F.Id("p"), Sp, Rangle)), Sp, Rangle), Sp, Comma, Sp,
        Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, F.Id("t"), Sp, Dot, Sp, D(2), Sp, Comma, Sp,
        Seq(Langle, Sp, D(0), Sp, Rangle)), Sp, Rangle)))));

    private static Formula Statement8() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelSample")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp, F.Id("transpose"), Sp,
        Cdot, Sp, Qualified(F.Id("LinearMap"), Dot, F.Id("toMatrix")), Sp, Apos, Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, Eq, Sp, D(1));

    private static Formula Statement9() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp,
        Parenthesized(Seq(Qualified(F.Id("LinearMap"), Dot, F.Id("toMatrix")), Sp, Apos, Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelEmbedding")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp, F.Id("transpose"), Sp,
        Cdot, Sp, Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelSample")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, Eq, Sp, D(1));

    private static Formula Statement10() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("BM"), Sp, Colon, Sp,
        F.Id("Matrix"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("DM"), Sp, Colon, Sp,
        F.Id("Matrix"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("delta"))), Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("singleCross")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, F.Id("BM"), Sp, F.Id("DM"), Sp, Eq, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelSample")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, Cdot, Sp, Qualified(F.Id("BM"),
        Dot, F.Id("kronecker")), Sp, F.Id("DM"), Sp, Cdot, Sp, Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"),
        Dot, F.Id("inclusion")), Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelSample")),
        Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp,
        F.Id("transpose"))));

    private static Formula Statement11() =>
        Seq(Forall, Sp, Seq(OpenBrace, Seq(F.Id("m"), Sp, Colon, Sp, F.Id("Type")), CloseBrace), Sp, Seq(OpenBrace,
        Seq(F.Id("n"), Sp, Colon, Sp, F.Id("Type")), CloseBrace), Sp, Seq(OpenBrace, Seq(F.Id("r"), Sp, Colon, Sp,
        F.Id("Type")), CloseBrace), Sp, Seq(OpenBrace, Seq(F.Id("s"), Sp, Colon, Sp, F.Id("Type")), CloseBrace), Sp,
        Seq(OpenBracket, Seq(F.Id("DecidableEq"), Sp, F.Id("m")), CloseBracket), Sp, Seq(OpenBracket,
        Seq(F.Id("DecidableEq"), Sp, F.Id("r")), CloseBracket), Sp, Parenthesized(Seq(F.Id("e"), Sp, Colon, Sp,
        F.Id("n"), Sp, To, Sp, F.Id("m"))), Sp, Parenthesized(Seq(F.Id("f"), Sp, Colon, Sp, F.Id("s"), Sp, To, Sp,
        F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        F.Id("fun"), Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp, F.Id("n"), Sp, Times, Sp, F.Id("s"))), Sp,
        Mapsto, Sp, Parenthesized(Seq(F.Id("e"), Sp, F.Id("k"), Sp, Dot, Sp, D(1), Sp, Comma, Sp, F.Id("f"), Sp,
        F.Id("k"), Sp, Dot, Sp, D(2))))), Sp, Eq, Sp, Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot,
        F.Id("inclusion")), Sp, F.Id("e"))), Sp, Dot, Sp, F.Id("kronecker"), Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp, F.Id("f"))));

    private static Formula Statement12() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, Colon, Sp, Seq(Mathbb,
        Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("alpha"))), Sp,
        Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot, F.Id("shortZeroCol")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("i"), Sp, Eq, Sp, Parenthesized(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot,
        F.Id("inl")), Sp, F.Id("i"), Sp, Comma, Sp, Seq(Langle, Sp, D(0), Sp, Rangle)), Sp, Rangle)));

    private static Formula Statement13() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, Colon, Sp, Seq(Mathbb,
        Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("beta"))), Sp, Comma,
        Sp, Qualified(F.Id("ReservoirSchur"), Dot, F.Id("longLastRow")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp,
        F.Id("beta"), Sp, F.Id("k"), Sp, Eq, Sp, Parenthesized(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot,
        F.Id("inr")), Sp, F.Id("k"), Sp, Comma, Sp, Seq(Langle, Sp, F.Id("p"), Sp, Rangle)), Sp, Rangle)));

    private static Formula Statement16() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, Colon, Sp, Seq(Mathbb,
        Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("BM"), Sp, Colon, Sp, F.Id("Matrix"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp,
        Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot, F.Id("singleThirdLeft")),
        Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("BM"), Sp, Eq, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("longLastRow")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"))), Sp, Cdot, Sp, F.Id("BM"), Sp, Cdot, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("shortZeroCol")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"))))), Sp, Dot, Sp, F.Id("transpose"))));

    private static Formula Statement17() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb,
        Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("DM"), Sp, Colon, Sp, F.Id("Matrix"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))),
        Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("singleThirdRight")), Sp, F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("DM"), Sp, Eq, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("shortZeroCol")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"))), Sp, Cdot, Sp, F.Id("DM"), Sp, Cdot, Sp,
        Parenthesized(Seq(Qualified(F.Id("CyclicResolvent"), Dot, F.Id("inclusion")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("longLastRow")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp, F.Id("transpose"))));

    private static Formula Statement18() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("BM"), Sp, Colon, Sp,
        F.Id("Matrix"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("DM"), Sp, Colon, Sp,
        F.Id("Matrix"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("delta"))), Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("singleCross")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, F.Id("BM"), Sp, F.Id("DM"), Sp, Eq, Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"),
        Dot, F.Id("singleThirdLeft")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("BM"))), Sp, Dot,
        Sp, F.Id("kronecker"), Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("singleThirdRight")),
        Sp, F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("DM"))));

    private static Formula Statement19() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("q"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp,
        Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp, Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma,
        Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("q"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp,
        Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, Parenthesized(Seq(F.Id("j"), Sp,
        Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("i"), Sp, Plus, Sp, D(1))), Sp, Times, Sp,
        F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("q"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("j"))))), Sp, Comma, Sp,
        Qualified(F.Id("ReservoirSchur"), Dot, F.Id("localSource")), Sp, F.Id("p"), Sp, F.Id("q"), Sp, F.Id("alpha"),
        Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("u"), Sp, F.Id("i"), Sp, F.Id("j"), Sp,
        F.Id("k"), Sp, Eq, Sp, Parenthesized(Seq(F.Id("u"), Sp, Parenthesized(Seq(Seq(Langle, Sp, Seq(F.Id("i"), Sp,
        Comma, Sp, F.Id("k"), Sp, Dot, Sp, D(1)), Sp, Rangle), Sp, Comma, Sp, Seq(Langle, Sp, Seq(F.Id("j"), Sp,
        Comma, Sp, F.Id("k"), Sp, Dot, Sp, D(2)), Sp, Rangle))))));

    private static Formula Statement20() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("q"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp,
        Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp, Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma,
        Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("q"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("Q"))))), Sp,
        Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, Parenthesized(Seq(F.Id("j"), Sp,
        Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, Parenthesized(Seq(F.Id("s"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("i"))))), Sp, Parenthesized(Seq(F.Id("t"), Sp, Colon,
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("q"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("j"), Sp, Plus, Sp, D(1))))), Sp, Comma, Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("widthTwoMatrix")), Sp, F.Id("p"), Sp,
        F.Id("q"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, Dot, Sp,
        F.Id("mulVec"), Sp, F.Id("u"), Sp, Parenthesized(Seq(Seq(Langle, Sp, Seq(F.Id("i"), Sp, Comma, Sp, F.Id("s")),
        Sp, Rangle), Sp, Comma, Sp, Seq(Langle, Sp, Seq(F.Id("j"), Sp, Comma, Sp, F.Id("t")), Sp, Rangle))), Sp, Eq,
        Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("pencil")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("i"))), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"),
        Dot, F.Id("blockLength")), Sp, F.Id("q"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("j"))))), Sp, Dot,
        Sp, F.Id("mulVec"), Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("localSource")), Sp,
        F.Id("p"), Sp, F.Id("q"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp,
        F.Id("u"), Sp, F.Id("i"), Sp, F.Id("j"))), Sp, Parenthesized(Seq(F.Id("s"), Sp, Comma, Sp, F.Id("t"))));

    private static Formula Statement21() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp,
        Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp,
        Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("Q"))))),
        Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp, Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma,
        Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("sourceSL")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"),
        Sp, F.Id("u"), Sp, F.Id("k"), Sp, Eq, Sp, Parenthesized(Seq(F.Id("match"), Sp, F.Id("k"), Sp, Dot, Sp, D(1),
        Sp, Dot, Sp, F.Id("fst"), Sp, Comma, Sp, F.Id("k"), Sp, Dot, Sp, D(2), Sp, Dot, Sp, F.Id("fst"), Sp,
        F.Id("with"), Sp, Bar, Sp, Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, Minus, Sp, Comma, Sp,
        Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp, Minus, Sp, Mapsto, Sp, F.Id("u"), Sp, F.Id("k"), Sp, Bar, Sp,
        Minus, Sp, Comma, Sp, Minus, Sp, Mapsto, Sp, D(0))));

    private static Formula Statement22() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp,
        Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1)))))), Sp, Times, Sp,
        Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"))))), Sp, To, Sp, Seq(Mathbb, Grp(F.Id("Q"))))),
        Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("t"), Sp, Colon, Sp, F.Id("Fin"), Sp, Parenthesized(Seq(F.Id("p"),
        Sp, Plus, Sp, D(1))))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("alpha"), Sp,
        Times, Sp, F.Id("Fin"), Sp, F.Id("delta"))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("slLine")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp,
        F.Id("u"), Sp, F.Id("r"), Sp, F.Id("t"), Sp, F.Id("k"), Sp, Eq, Sp, Parenthesized(Seq(F.Id("u"), Sp,
        Parenthesized(Seq(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, F.Id("k"), Sp, Dot, Sp,
        D(1), Sp, Comma, Sp, Seq(Langle, Sp, Seq(F.Id("p"), Sp, Minus, Sp, Parenthesized(Call("val", F.Id("r")))), Sp, Rangle)), Sp, Rangle), Sp, Comma, Sp, Seq(Langle,
        Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inr")), Sp, F.Id("k"), Sp, Dot, Sp, D(2), Sp, Comma, Sp, Seq(Langle,
        Sp, Seq(F.Id("p"), Sp, Minus, Sp, Parenthesized(Call("val", F.Id("t")))), Sp,
        Rangle)), Sp, Rangle))))));

    private static Formula Statement23() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("z"), Sp, Colon, Sp,
        Parenthesized(Parenthesized(Seq(new Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp,
        Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("alpha"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("beta"))))),
        Sp, F.Id("Fin"), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("t")))))), Sp, Times, Sp, Parenthesized(Seq(new
        Formula.Subscript(Sigma, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Sum"), Sp, Parenthesized(Seq(F.Id("Fin"), Sp,
        F.Id("gamma"))), Sp, Parenthesized(Seq(F.Id("Fin"), Sp, F.Id("delta"))))), Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("blockLength")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"), Sp, F.Id("t"), Sp, Plus, Sp, D(1))))), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("beta"))), Sp,
        Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, F.Id("Fin"), Sp, F.Id("gamma"))), Sp, Comma, Sp,
        Parenthesized(Seq(Qualified(F.Id("LinearMap"), Dot, F.Id("toMatrix")), Sp, Apos, Sp,
        Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("cokernelEmbedding")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))))), Sp, Dot, Sp,
        Qualified(F.Id("transpose"), Dot, F.Id("mulVec")), Sp, F.Id("z"), Sp, Parenthesized(Seq(F.Id("k"), Sp, Comma,
        Sp, F.Id("j"))), Sp, Eq, Sp, Seq(new Formula.Subscript(Sum, Seq(F.Id("t"), Sp, Colon, Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(F.Id("p"), Sp, Plus, Sp, D(1))))), Sp, Parenthesized(Seq(new
        Formula.Power(Parenthesized(Seq(Minus, Sp, D(1))), Call("val", F.Id("t"))), Sp, Cdot, Sp, F.Id("z"), Sp, Parenthesized(Seq(Seq(Langle, Sp, Seq(Qualified(F.Id("Sum"), Dot,
        F.Id("inr")), Sp, F.Id("k"), Sp, Comma, Sp, Seq(Langle, Sp, Seq(F.Id("p"), Sp, Minus, Sp, Parenthesized(Call("val", F.Id("t")))), Sp, Rangle)), Sp, Rangle), Sp, Comma, Sp, Seq(Langle,
        Sp, Seq(Qualified(F.Id("Sum"), Dot, F.Id("inl")), Sp, F.Id("j"), Sp, Comma, Sp, F.Id("t")), Sp, Rangle)))))));

    private static Formula Statement24() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("w"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("t"), Sp, Colon, Sp, F.Id("Fin"), Sp,
        Parenthesized(Seq(F.Id("p"), Sp, Plus, Sp, D(1))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot,
        F.Id("slLine")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp,
        Parenthesized(Seq(Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, F.Id("w"))), Sp,
        F.Id("r"), Sp, F.Id("t"), Sp, Eq, Sp, F.Id("if"), Sp, Parenthesized(Call("val", F.Id("r"))), Sp, Plus, Sp, Parenthesized(Call("val", F.Id("t"))), Sp, Eq,
        Sp, F.Id("p"), Sp, F.Id("then"), Sp, new Formula.Power(Parenthesized(Seq(Minus, Sp, D(1))), Seq(F.Id("p"), Sp,
        Minus, Sp, Parenthesized(Call("val", F.Id("r"))))), Sp, Cdot, Sp, F.Id("w"),
        Sp, F.Id("else"), Sp, D(0));

    private static Formula Statement25() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(F.Id("w"), Sp, Colon, Sp,
        F.Id("Fin"), Sp, F.Id("alpha"), Sp, Times, Sp, F.Id("Fin"), Sp, F.Id("delta"), Sp, To, Sp, Seq(Mathbb,
        Grp(F.Id("Q"))))), Sp, Comma, Sp, Qualified(F.Id("ReservoirSchur"), Dot, F.Id("sourceSL")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"), Sp,
        Parenthesized(Seq(Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp,
        F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, F.Id("w"))), Sp,
        Eq, Sp, Parenthesized(Seq(Qualified(F.Id("ReservoirSchur"), Dot, F.Id("kernelEmbedding")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp, F.Id("delta"))), Sp, F.Id("w"));

    private static Formula Statement26() =>
        Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"), Sp, F.Id("gamma"), Sp,
        F.Id("delta"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, D(0), Sp, F.Lt, Sp, F.Id("p"), Sp,
        To, Sp, D(0), Sp, F.Lt, Sp, F.Id("beta"), Sp, To, Sp, F.Id("beta"), Sp, Leq, Sp, F.Id("alpha"), Sp, To, Sp,
        D(0), Sp, F.Lt, Sp, F.Id("delta"), Sp, To, Sp, F.Id("delta"), Sp, Leq, Sp, F.Id("gamma"), Sp, To, Sp,
        Qualified(F.Id("QuantumMaxFlowBound"), Dot, F.Id("RationalWitness")), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("leftDim")), Sp, F.Id("p"), Sp,
        F.Id("alpha"), Sp, F.Id("beta"))), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot,
        F.Id("rightDim")), Sp, F.Id("p"), Sp, F.Id("alpha"), Sp, F.Id("beta"))), Sp,
        Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot, F.Id("leftDim")), Sp, F.Id("p"), Sp,
        F.Id("gamma"), Sp, F.Id("delta"))), Sp, Parenthesized(Seq(Qualified(F.Id("ShiftPencilBlocks"), Dot,
        F.Id("rightDim")), Sp, F.Id("p"), Sp, F.Id("gamma"), Sp, F.Id("delta"))));

}
