using static StrataLint.Scribe.DefinitionDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S0.Certificates.Games;

internal sealed class VersionBOddCountUnderdeterminesDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S0/Certificates/Games/VersionBOddCountUnderdetermines.";
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Two in-scope twelve-pile positions have six odd piles and opposite normal-play Version B outcomes.",
        H("Odd-pile count does not determine losing status"),
        Blocks(
            Describe.Lean(DescribeId.Create("underdetermined-version-b-position"),
                DeclarationHandle.Create(Prefix + "Position"), H("Seven pile sizes"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A position records the multiplicities of sizes one through seven. There is no bound on the number of piles."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-pilecount"),
                DeclarationHandle.Create(Prefix + "pileCount"), H("Pile count"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The sum of the seven multiplicities is the number of nonempty piles."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-tokens"),
                DeclarationHandle.Create(Prefix + "tokens"), H("Token count"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Each multiplicity is weighted by its pile size. The resulting total is the termination measure for Losing."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-singlesuccessors"),
                DeclarationHandle.Create(Prefix + "singleSuccessors"), H("Single-pile successors"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For each present size, one pile loses one token. A size-one pile disappears; any larger pile becomes one size smaller."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-allsuccessor"),
                DeclarationHandle.Create(Prefix + "allSuccessor"), H("Simultaneous successor"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("All piles lose one token. Size-one piles disappear and the size-seven multiplicity of the successor is zero."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-singlemove"),
                DeclarationHandle.Create(Prefix + "SingleMove"), H("Single-pile move"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A single-pile move means membership in singleSuccessors."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-allmove"),
                DeclarationHandle.Create(Prefix + "AllMove"), H("All-pile move"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The simultaneous move requires a nonzero pile count and reaches allSuccessor."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-move"),
                DeclarationHandle.Create(Prefix + "Move"), H("Legal move"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A legal move is either SingleMove or AllMove."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-losing"),
                DeclarationHandle.Create(Prefix + "Losing"), H("Normal-play losing status"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Losing is defined by recursion on token count: every legal successor is not losing. This includes the empty position as a loss."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-oddpiles"),
                DeclarationHandle.Create(Prefix + "oddPiles"), H("Odd-pile count"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The multiplicities of sizes one, three, five and seven sum to the number of odd piles."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-everypileexceedsthreshold"),
                DeclarationHandle.Create(Prefix + "EveryPileExceedsThreshold"), H("Strict threshold"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Every present pile strictly exceeds the integer ceiling of one third of the pile count. Absent sizes impose no condition."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-oddcountdetermines"),
                DeclarationHandle.Create(Prefix + "OddCountDetermines"), H("The claim under refutation"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    Id("OddCountDetermines"), F.Sp, F.Leftrightarrow, F.Sp,
                    F.Forall, F.Sp, Id("s"), F.Sp, Id("t"), F.Colon, Id("Position"), F.Comma, F.Sp,
                    Num(3), F.Le, F.Sp, Call("pileCount", Id("s")), F.Sp, F.Rightarrow, F.Sp,
                    Num(3), F.Le, F.Sp, Call("pileCount", Id("t")), F.Sp, F.Rightarrow, F.Sp,
                    Call("EveryPileExceedsThreshold", Id("s")), F.Sp, F.Rightarrow, F.Sp,
                    Call("EveryPileExceedsThreshold", Id("t")), F.Sp, F.Rightarrow, F.Sp,
                    Call("pileCount", Id("s")), F.Eq, F.Sp, Call("pileCount", Id("t")), F.Sp, F.Rightarrow, F.Sp,
                    Call("oddPiles", Id("s")), F.Eq, F.Sp, Call("oddPiles", Id("t")), F.Sp, F.Rightarrow, F.Sp,
                    F.Open, Call("Losing", Id("s")), F.Sp, F.Leftrightarrow, F.Sp,
                    Call("Losing", Id("t")), F.Close))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The closed proposition quantifies over all pairs in the seven-size game. Each position has at least three piles and satisfies the strict threshold. Equal pile counts and equal odd-pile counts are asserted to imply equivalent losing status."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-sixfives-sixsixes"),
                DeclarationHandle.Create(Prefix + "sixFives_sixSixes"), H("Six fives and six sixes"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Write s56 for sixFives_sixSixes. This position has six piles of size five, six of size six, and no other piles."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-sixsixes-sixsevens"),
                DeclarationHandle.Create(Prefix + "sixSixes_sixSevens"), H("Six sixes and six sevens"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Write s67 for sixSixes_sixSevens. This position has six piles of size six, six of size seven, and no other piles."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-sixfives-sixsixes-witness"),
                DeclarationHandle.Create(Prefix + "sixFives_sixSixes_witness"), H("The losing witness"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    Call("pileCount", Id("s56")), F.Eq, F.Sp, Num(12), F.Land, F.Sp,
                    Num(3), F.Le, F.Sp, Call("pileCount", Id("s56")), F.Land, F.Sp,
                    Call("EveryPileExceedsThreshold", Id("s56")), F.Land, F.Sp,
                    Call("oddPiles", Id("s56")), F.Eq, F.Sp, Num(6), F.Land, F.Sp,
                    Call("Losing", Id("s56"))))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Six fives and six sixes satisfy the scope hypotheses, have twelve piles and six odd piles, and are losing. The wider game has its own kernel-checked certificate recurrence on the closed domain of at most twelve piles with no sevens; induction on token count identifies that certificate with Losing."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-sixsixes-sixsevens-all-move"),
                DeclarationHandle.Create(Prefix + "sixSixes_sixSevens_all_move"), H("The winning all-move"),
                StatementSource.FromAuthor(F.Disp(Call("AllMove", Id("s67"), Id("s56")))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Removing one token from every pile of six sixes and six sevens reaches six fives and six sixes. The starting position is nonempty, so this all-move is legal."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-sixsixes-sixsevens-witness"),
                DeclarationHandle.Create(Prefix + "sixSixes_sixSevens_witness"), H("The non-losing witness"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    Call("pileCount", Id("s67")), F.Eq, F.Sp, Num(12), F.Land, F.Sp,
                    Num(3), F.Le, F.Sp, Call("pileCount", Id("s67")), F.Land, F.Sp,
                    Call("EveryPileExceedsThreshold", Id("s67")), F.Land, F.Sp,
                    Call("oddPiles", Id("s67")), F.Eq, F.Sp, Num(6), F.Land, F.Sp,
                    F.Neg, F.Sp, Call("Losing", Id("s67"))))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Six sixes and six sevens satisfy the same scope hypotheses and have the same two counts. Their legal all-move reaches the losing witness, so this position is not losing."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("underdetermined-version-b-odd-count-does-not-determine"),
                DeclarationHandle.Create(Prefix + "odd_count_does_not_determine"), H("Odd-pile count underdetermines the outcome"),
                StatementSource.FromAuthor(F.Disp(F.Seq(F.Neg, F.Sp, Id("OddCountDetermines")))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Applying OddCountDetermines to the two witnesses would make their losing statuses equivalent. The losing first witness and non-losing second witness contradict that equivalence."))), DescribeRole.Theorem)),
        []));
}
