using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Combinatorics.AlternatingSignRectangles;

internal sealed class RowCompleteRecurrenceDocument : IScribeDocumentDefinition
{
    private static readonly LibraryNoteRef Source =
        LibraryNoteRef.Create("D5/L/PermutationPatterns/hongesberg2026asr");

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "RowCompleteRecurrence for extendably 312-avoiding alternating sign rectangles.",
        H("RowCompleteRecurrence"), Blocks(
            Paragraph(Text("The formulas retain Lean function names and typed binders. Natural subtraction is truncated subtraction; slash between natural numbers is Nat.div. Constructor proof fields and certified cast proofs are suppressed; matrix entries and subtype values are explicit.")),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-0"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.zeroColumn"), H("zeroColumn"),
                StatementSource.FromAuthor(Formula0()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-1"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.zeroColumn_zero"), H("zeroColumn_zero"),
                StatementSource.FromAuthor(Formula1()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-2"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.zeroColumn_succ"), H("zeroColumn_succ"),
                StatementSource.FromAuthor(Formula2()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-3"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.zeroColumn_reconstruct"), H("zeroColumn_reconstruct"),
                StatementSource.FromAuthor(Formula3()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-4"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.ZeroColumnFibre"), H("ZeroColumnFibre"),
                StatementSource.FromAuthor(Formula4()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-5"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.extractZeroColumn"), H("extractZeroColumn"),
                StatementSource.FromAuthor(Formula5()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed entries specify removal of the zero first column; subtype proof fields are suppressed."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-6"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.zeroColumnFibreEquiv"), H("zeroColumnFibreEquiv"),
                StatementSource.FromAuthor(Formula6()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted. The two equalities give the toFun and invFun fields; subtype proof fields are suppressed."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-7"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.pivot_before_nonempty_of_deficit"), H("pivot_before_nonempty_of_deficit"),
                StatementSource.FromAuthor(Formula7()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-8"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.positiveFirst_card"), H("positiveFirst_card"),
                StatementSource.FromAuthor(Formula8()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-9"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.rectangle_merge_nat"), H("rectangle_merge_nat"),
                StatementSource.FromAuthor(Formula9()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-10"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.sum_Icc_two"), H("sum_Icc_two"),
                StatementSource.FromAuthor(Formula10()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("row-complete-recurrence-11"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/RowCompleteRecurrence.S_row"), H("S_row"),
                StatementSource.FromAuthor(Formula11()), AssessedProvenance.FromLiterature(Source),
                Blocks(Paragraph(Text("Proposition 4.2 (p. 6), from the first-column decomposition of a rectangle with every row nonempty."))), DescribeRole.Lemma)), []));

    private static Formula Named(string name) => Seq(Operatorname, Grp(F.Id(name)));
    private static Formula Parenthesized(Formula value) => Seq(Open, value, Close);

    private static Formula Formula0() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("B"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("zeroColumn"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("B"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, Parenthesized(Seq(F.Id("k"), Sp, Plus, Sp, D(1))))), Sp, Named("SignType")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("B"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("zeroColumn"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("B"), Sp, Eq, Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("u"), Sp, Mapsto, Sp, Named("Fin"), Sp, Dot, Sp, Named("cons"), Sp, D(0), Sp, Parenthesized(Seq(F.Id("B"), Sp, F.Id("u"))))))]));

    private static Formula Formula1() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("B"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Named("zeroColumn"), Sp, F.Id("B"), Sp, F.Id("u"), Sp, D(0), Sp, Eq, Sp, D(0)));

    private static Formula Formula2() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("B"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("c"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Named("zeroColumn"), Sp, F.Id("B"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Dot, Sp, Named("succ"), Sp, Eq, Sp, F.Id("B"), Sp, F.Id("u"), Sp, F.Id("c")));

    private static Formula Formula3() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, Parenthesized(Seq(F.Id("k"), Sp, Plus, Sp, D(1))))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("u"), Sp, D(0), Sp, Eq, Sp, D(0))), Sp, To, Sp, Named("zeroColumn"), Sp, Parenthesized(Parenthesized(Seq(Named("fun"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Mapsto, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Dot, Sp, Named("succ")))), Sp, Eq, Sp, F.Id("R")));

    private static Formula Formula4() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Named("ZeroColumnFibre"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Named("Type")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Named("ZeroColumnFibre"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Eq, Sp, Parenthesized(new Formula.SetLiteral([Seq(F.Id("R"), Sp, Colon, Sp, Named("Counted"), Sp, F.Id("r"), Sp, Parenthesized(Seq(F.Id("k"), Sp, Plus, Sp, D(1))), Sp, F.Id("d"), Sp, Bar, Sp, Forall, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("R"), Sp, Dot, Sp, Named("val"), Sp, F.Id("u"), Sp, D(0), Sp, Eq, Sp, D(0))])))]));

    private static Formula Formula5() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("ZeroColumnFibre"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"))), Sp, Comma, Sp, Named("extractZeroColumn"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, Parenthesized(Seq(F.Id("d"), Sp, Seq(Colon, Eq), Sp, F.Id("d"))), Sp, F.Id("R"), Sp, Colon, Sp, Named("Counted"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("ZeroColumnFibre"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Parenthesized(Seq(Named("extractZeroColumn"), Sp, F.Id("R"))), Sp, Dot, Sp, Named("val"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Eq, Sp, F.Id("R"), Sp, Dot, Sp, Named("val"), Sp, Dot, Sp, Named("val"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Dot, Sp, Named("succ"))]));

    private static Formula Formula6() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Named("zeroColumnFibreEquiv"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Named("Equiv"), Sp, Parenthesized(Seq(Named("ZeroColumnFibre"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"))), Sp, Parenthesized(Seq(Named("Counted"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d")))), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Parenthesized(Seq(Parenthesized(Seq(Named("zeroColumnFibreEquiv"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"))), Sp, Dot, Sp, Named("toFun"), Sp, Eq, Sp, Named("extractZeroColumn"))), Sp, Land, Sp, Parenthesized(Seq(Parenthesized(Seq(Named("zeroColumnFibreEquiv"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"))), Sp, Dot, Sp, Named("invFun"), Sp, Eq, Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("B"), Sp, Mapsto, Sp, Seq(Langle, Sp, Seq(Langle, Sp, Seq(Named("zeroColumn"), Sp, F.Id("B"), Sp, Dot, Sp, Named("val")), Rangle), Rangle))))))]));

    private static Formula Formula7() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Named("nonemptyRows"), Sp, F.Id("R"), Sp, Lt, Sp, F.Id("k"))), Sp, To, Sp, Forall, Sp, F.Id("v"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("v"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("v"), Sp, F.Id("c"), Sp, Neq, Sp, D(0)));

    private static Formula Formula8() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("d"), Sp, Le, Sp, F.Id("r"))), Sp, To, Sp, Parenthesized(Seq(F.Id("d"), Sp, Le, Sp, F.Id("k"))), Sp, To, Sp, Parenthesized(Seq(F.Id("d"), Sp, Lt, Sp, F.Id("k"), Sp, Lor, Sp, F.Id("d"), Sp, Eq, Sp, F.Id("r"))), Sp, To, Sp, Named("Nat"), Sp, Dot, Sp, Named("card"), Sp, Parenthesized(new Formula.SetLiteral([Seq(F.Id("R"), Sp, Colon, Sp, Named("Counted"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Plus, Sp, D(1))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Plus, Sp, D(1))), Sp, Parenthesized(Seq(F.Id("d"), Sp, Plus, Sp, D(1))), Sp, Bar, Sp, Exists, Sp, F.Id("i"), Sp, Comma, Sp, F.Id("R"), Sp, Dot, Sp, Named("val"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, D(0), Rangle), Sp, Eq, Sp, D(1))])), Sp, Eq, Sp, F.Id("S"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Plus, Sp, new Formula.Subscript(Sum, Seq(F.Id("p"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("d"))), Sp, Named("Nat"), Sp, Dot, Sp, Named("card"), Sp, Parenthesized(Seq(Named("AvoidASM"), Sp, Parenthesized(Seq(F.Id("p"), Sp, Dot, Sp, Named("val"), Sp, Plus, Sp, D(1))))), Sp, Cdot, Sp, Named("Nat"), Sp, Dot, Sp, Named("card"), Sp, Parenthesized(Seq(Named("FirstNonempty"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Minus, Sp, F.Id("p"), Sp, Dot, Sp, Named("val"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Minus, Sp, F.Id("p"), Sp, Dot, Sp, Named("val"))), Sp, Parenthesized(Seq(F.Id("d"), Sp, Minus, Sp, F.Id("p"), Sp, Dot, Sp, Named("val"))), Sp, new Formula.Placeholder()))));

    private static Formula Formula9() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("d"), Sp, Le, Sp, F.Id("r"))), Sp, To, Sp, Parenthesized(Seq(F.Id("d"), Sp, Le, Sp, F.Id("k"))), Sp, To, Sp, Parenthesized(Seq(F.Id("d"), Sp, Lt, Sp, F.Id("k"), Sp, Lor, Sp, F.Id("d"), Sp, Eq, Sp, F.Id("r"))), Sp, To, Sp, F.Id("S"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Plus, Sp, D(1))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Plus, Sp, D(1))), Sp, Parenthesized(Seq(F.Id("d"), Sp, Plus, Sp, D(1))), Sp, Eq, Sp, F.Id("S"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Plus, Sp, D(1))), Sp, F.Id("k"), Sp, Parenthesized(Seq(F.Id("d"), Sp, Plus, Sp, D(1))), Sp, Plus, Sp, F.Id("S"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Plus, Sp, new Formula.Subscript(Sum, Seq(F.Id("p"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("d"))), Sp, Named("Nat"), Sp, Dot, Sp, Named("card"), Sp, Parenthesized(Seq(Named("AvoidASM"), Sp, Parenthesized(Seq(F.Id("p"), Sp, Dot, Sp, Named("val"), Sp, Plus, Sp, D(1))))), Sp, Cdot, Sp, Named("Nat"), Sp, Dot, Sp, Named("card"), Sp, Parenthesized(Seq(Named("FirstNonempty"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Minus, Sp, F.Id("p"), Sp, Dot, Sp, Named("val"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Minus, Sp, F.Id("p"), Sp, Dot, Sp, Named("val"))), Sp, Parenthesized(Seq(F.Id("d"), Sp, Minus, Sp, F.Id("p"), Sp, Dot, Sp, Named("val"))), Sp, new Formula.Placeholder()))));

    private static Formula Formula10() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(Alpha, Sp, Colon, Sp, Named("Type"))), Sp, Comma, Sp, Seq(OpenBracket, Seq(Named("AddCommMonoid"), Sp, Alpha), CloseBracket), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("r"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("f"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))), Sp, To, Sp, Alpha)), Sp, Comma, Sp, Parenthesized(Seq(new Formula.Subscript(Sum, Seq(F.Id("i"), Sp, Colon, Sp, Seq(Named("CoeSort"), Dot, Named("coe")), Sp, Parenthesized(Seq(Named("Icc"), Sp, D(2), Sp, F.Id("r"))))), Sp, F.Id("f"), Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, Eq, Sp, new Formula.Subscript(Sum, Seq(F.Id("p"), Sp, Colon, Sp, Named("Fin"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Minus, Sp, D(1))))), Sp, F.Id("f"), Sp, Parenthesized(Seq(F.Id("p"), Sp, Dot, Sp, Named("val"), Sp, Plus, Sp, D(2)))));

    private static Formula Formula11() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("r"))), Sp, To, Sp, Parenthesized(Seq(F.Id("r"), Sp, Lt, Sp, F.Id("k"))), Sp, To, Sp, Parenthesized(Seq(F.Id("S"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("r"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Eq, Sp, Parenthesized(Seq(F.Id("S"), Sp, F.Id("r"), Sp, Parenthesized(Seq(F.Id("k"), Sp, Minus, Sp, D(1))), Sp, F.Id("r"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Plus, Sp, Parenthesized(Seq(F.Id("S"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Minus, Sp, D(1))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Minus, Sp, D(1))), Sp, Parenthesized(Seq(F.Id("r"), Sp, Minus, Sp, D(1))), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Plus, Sp, new Formula.Subscript(Sum, Seq(F.Id("i"), Sp, Colon, Sp, Seq(Named("CoeSort"), Dot, Named("coe")), Sp, Parenthesized(Seq(Named("Icc"), Sp, D(2), Sp, F.Id("r"))))), Sp, Parenthesized(Seq(Named("Nat"), Sp, Dot, Sp, Named("largeSchroder"), Sp, Parenthesized(Seq(F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Minus, Sp, D(2))), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Cdot, Sp, Parenthesized(Seq(F.Id("S"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Plus, Sp, D(1), Sp, Minus, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Plus, Sp, D(1), Sp, Minus, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, Parenthesized(Seq(F.Id("r"), Sp, Plus, Sp, D(1), Sp, Minus, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z")))))));
}
