using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Combinatorics.AlternatingSignRectangles;

internal sealed class SignLinesDocument : IScribeDocumentDefinition
{
    private static readonly LibraryNoteRef Source =
        LibraryNoteRef.Create("D5/L/PermutationPatterns/hongesberg2026asr");

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "SignLines for extendably 312-avoiding alternating sign rectangles.",
        H("SignLines"), Blocks(
            Paragraph(Text("The formulas retain Lean function names and typed binders. Natural subtraction is truncated subtraction; slash between natural numbers is Nat.div. Constructor proof fields and certified cast proofs are suppressed; matrix entries and subtype values are explicit.")),
            Describe.Lean(DescribeId.Create("sign-lines-transport-0"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.line_embed"), H("line_embed"),
                StatementSource.FromAuthor(TransportFormula0()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-transport-1"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.ends_embed"), H("ends_embed"),
                StatementSource.FromAuthor(TransportFormula1()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-transport-4"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.sum_embed"), H("sum_embed"),
                StatementSource.FromAuthor(TransportFormula4()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-0"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.Alternates"), H("Alternates"),
                StatementSource.FromAuthor(Formula0()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-1"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.StartsOne"), H("StartsOne"),
                StatementSource.FromAuthor(Formula1()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-2"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.EndsOne"), H("EndsOne"),
                StatementSource.FromAuthor(Formula2()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-3"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.IsASR"), H("IsASR"),
                StatementSource.FromAuthor(Formula3()), AssessedProvenance.FromLiterature(Source),
                Blocks(Paragraph(Text("Section 2 (p. 3): “Let r and k be positive integers. An alternating sign rectangle (ASR) of size r × k is an r × k matrix with entries in {−1, 0, 1} such that” “the nonzero entries alternate in each row and column;” “if a row contains a nonzero entry, then its leftmost and rightmost nonzero entries are 1;” “if a column contains a nonzero entry, then its topmost nonzero entry is 1.” Fin indices start at zero; the binding Lean conventions also include zero dimensions."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-4"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.IsASM"), H("IsASM"),
                StatementSource.FromAuthor(Formula4()), AssessedProvenance.FromLiterature(Source),
                Blocks(Paragraph(Text("Section 2 (p. 3): “An ASM is a square ASR whose rows and columns each sum to 1.”"))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-5"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.Contains312"), H("Contains312"),
                StatementSource.FromAuthor(Formula5()), AssessedProvenance.FromLiterature(Source),
                Blocks(Paragraph(Text("Section 2 (p. 3): “We say that M contains a pattern π if there exist 1 ≤ i₁ < · · · < iₙ ≤ m and 1 ≤ j₁ < · · · < jₙ ≤ m such that Mᵢ₁,ⱼπ(1) = · · · = Mᵢₙ,ⱼπ(n) = 1.” The binding convention specializes π to 312 with zero-based Fin indices."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-6"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.ExtAvoids312"), H("ExtAvoids312"),
                StatementSource.FromAuthor(Formula6()), AssessedProvenance.FromLiterature(Source),
                Blocks(Paragraph(Text("The source says: “An ASR is said to extendably avoid a pattern if there exists an extension of the ASR to a square ASM that avoids the pattern.” (p. 3). The extension contains the given matrix as its top-left corner and may have any size."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-7"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.nonemptyRows"), H("nonemptyRows"),
                StatementSource.FromAuthor(Formula7()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-8"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.S"), H("S"),
                StatementSource.FromAuthor(Formula8()), AssessedProvenance.FromLiterature(Source),
                Blocks(Paragraph(Text("The count is Nat.card of the subtype of ASRs with the stated existential extension and exactly d nonempty rows (Section 2, p. 3)."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-9"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.singleton_line"), H("singleton_line"),
                StatementSource.FromAuthor(Formula9()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-10"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.S_zero"), H("S_zero"),
                StatementSource.FromAuthor(Formula10()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-11"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.row_has_one"), H("row_has_one"),
                StatementSource.FromAuthor(Formula11()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-12"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.empty_row_extension_one"), H("empty_row_extension_one"),
                StatementSource.FromAuthor(Formula12()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-13"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.no12_below_empty"), H("no12_below_empty"),
                StatementSource.FromAuthor(Formula13()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-14"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.prefix_line"), H("prefix_line"),
                StatementSource.FromAuthor(Formula14()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-15"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.topRows"), H("topRows"),
                StatementSource.FromAuthor(Formula15()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-16"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.topRows_isASR"), H("topRows_isASR"),
                StatementSource.FromAuthor(Formula16()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-17"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.topRows_extAvoids312"), H("topRows_extAvoids312"),
                StatementSource.FromAuthor(Formula17()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-18"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.LineState"), H("LineState"),
                StatementSource.FromAuthor(Formula18()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-19"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.alternating_line_state"), H("alternating_line_state"),
                StatementSource.FromAuthor(Formula19()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-20"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asr_row_sum"), H("asr_row_sum"),
                StatementSource.FromAuthor(Formula20()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-21"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asr_row_sum_one_iff"), H("asr_row_sum_one_iff"),
                StatementSource.FromAuthor(Formula21()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-22"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.one_before_minus"), H("one_before_minus"),
                StatementSource.FromAuthor(Formula22()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-23"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.one_after_minus_of_ends"), H("one_after_minus_of_ends"),
                StatementSource.FromAuthor(Formula23()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-24"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.line_sum_one_ends_one"), H("line_sum_one_ends_one"),
                StatementSource.FromAuthor(Formula24()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-25"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asm_column_ends_one"), H("asm_column_ends_one"),
                StatementSource.FromAuthor(Formula25()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-26"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asr_row_minus_unique"), H("asr_row_minus_unique"),
                StatementSource.FromAuthor(Formula26()), AssessedProvenance.FromLiterature(Source),
                Blocks(Paragraph(Text("Lemma 4.1 (p. 6): an extendably 312-avoiding ASR has at most one −1 in each row."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-27"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asr_column_minus_unique"), H("asr_column_minus_unique"),
                StatementSource.FromAuthor(Formula27()), AssessedProvenance.FromLiterature(Source),
                Blocks(Paragraph(Text("Lemma 4.1 (p. 6): an extendably 312-avoiding ASR has at most one −1 in each column."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-28"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.minus_between_ones"), H("minus_between_ones"),
                StatementSource.FromAuthor(Formula28()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-29"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asr_first_col_not_minus"), H("asr_first_col_not_minus"),
                StatementSource.FromAuthor(Formula29()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-30"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asr_first_col_one_unique"), H("asr_first_col_one_unique"),
                StatementSource.FromAuthor(Formula30()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-31"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.line_no_minus_singleton"), H("line_no_minus_singleton"),
                StatementSource.FromAuthor(Formula31()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-32"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asr_first_row_not_minus"), H("asr_first_row_not_minus"),
                StatementSource.FromAuthor(Formula32()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-33"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asr_first_row_singleton"), H("asr_first_row_singleton"),
                StatementSource.FromAuthor(Formula33()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-34"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.three_sign_line"), H("three_sign_line"),
                StatementSource.FromAuthor(Formula34()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-35"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.emptyRows"), H("emptyRows"),
                StatementSource.FromAuthor(Formula35()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-36"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.colSum"), H("colSum"),
                StatementSource.FromAuthor(Formula36()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-37"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.deficientColumns"), H("deficientColumns"),
                StatementSource.FromAuthor(Formula37()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("sign-lines-38"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.mem_emptyRows"), H("mem_emptyRows"),
                StatementSource.FromAuthor(Formula38()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-39"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.mem_deficientColumns"), H("mem_deficientColumns"),
                StatementSource.FromAuthor(Formula39()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-40"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asr_col_sum"), H("asr_col_sum"),
                StatementSource.FromAuthor(Formula40()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-41"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.asr_total_sum"), H("asr_total_sum"),
                StatementSource.FromAuthor(Formula41()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-42"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.emptyRows_balance"), H("emptyRows_balance"),
                StatementSource.FromAuthor(Formula42()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-43"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.deficientColumns_balance"), H("deficientColumns_balance"),
                StatementSource.FromAuthor(Formula43()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-44"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.nonemptyRows_le_rows"), H("nonemptyRows_le_rows"),
                StatementSource.FromAuthor(Formula44()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-45"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.nonemptyRows_le_columns"), H("nonemptyRows_le_columns"),
                StatementSource.FromAuthor(Formula45()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-46"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.balanced_column_sum"), H("balanced_column_sum"),
                StatementSource.FromAuthor(Formula46()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-47"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.prefix_sum_as_filter"), H("prefix_sum_as_filter"),
                StatementSource.FromAuthor(Formula47()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-48"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.one_after_zero_prefix"), H("one_after_zero_prefix"),
                StatementSource.FromAuthor(Formula48()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("sign-lines-49"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SignLines.deficient_column_extension_one"), H("deficient_column_extension_one"),
                StatementSource.FromAuthor(Formula49()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma)), []));

    private static Formula Named(string name) => Seq(Operatorname, Grp(F.Id(name)));
    private static Formula Parenthesized(Formula value) => Seq(Open, value, Close);

    private static Formula Formula0() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Named("Alternates"), Sp, Parenthesized(Seq(F.Id("n"), Sp, Seq(Colon, Eq), Sp, F.Id("n"))), Sp, F.Id("a"), Sp, Colon, Sp, Named("Prop")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Named("Alternates"), Sp, Parenthesized(Seq(F.Id("n"), Sp, Seq(Colon, Eq), Sp, F.Id("n"))), Sp, F.Id("a"), Sp, Leftrightarrow, Sp, Parenthesized(Seq(Forall, Sp, F.Id("x"), Sp, F.Id("y"), Sp, Comma, Sp, F.Id("x"), Sp, Lt, Sp, F.Id("y"), Sp, To, Sp, F.Id("a"), Sp, F.Id("x"), Sp, Neq, Sp, D(0), Sp, To, Sp, F.Id("a"), Sp, F.Id("y"), Sp, Neq, Sp, D(0), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("z"), Sp, Comma, Sp, F.Id("x"), Sp, Lt, Sp, F.Id("z"), Sp, To, Sp, F.Id("z"), Sp, Lt, Sp, F.Id("y"), Sp, To, Sp, F.Id("a"), Sp, F.Id("z"), Sp, Eq, Sp, D(0))), Sp, To, Sp, F.Id("a"), Sp, F.Id("x"), Sp, Neq, Sp, F.Id("a"), Sp, F.Id("y"))))]));

    private static Formula Formula1() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Named("StartsOne"), Sp, Parenthesized(Seq(F.Id("n"), Sp, Seq(Colon, Eq), Sp, F.Id("n"))), Sp, F.Id("a"), Sp, Colon, Sp, Named("Prop")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Named("StartsOne"), Sp, Parenthesized(Seq(F.Id("n"), Sp, Seq(Colon, Eq), Sp, F.Id("n"))), Sp, F.Id("a"), Sp, Leftrightarrow, Sp, Parenthesized(Seq(Forall, Sp, F.Id("x"), Sp, Comma, Sp, F.Id("a"), Sp, F.Id("x"), Sp, Neq, Sp, D(0), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("y"), Sp, Comma, Sp, F.Id("y"), Sp, Lt, Sp, F.Id("x"), Sp, To, Sp, F.Id("a"), Sp, F.Id("y"), Sp, Eq, Sp, D(0))), Sp, To, Sp, F.Id("a"), Sp, F.Id("x"), Sp, Eq, Sp, D(1))))]));

    private static Formula Formula2() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Named("EndsOne"), Sp, Parenthesized(Seq(F.Id("n"), Sp, Seq(Colon, Eq), Sp, F.Id("n"))), Sp, F.Id("a"), Sp, Colon, Sp, Named("Prop")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Named("EndsOne"), Sp, Parenthesized(Seq(F.Id("n"), Sp, Seq(Colon, Eq), Sp, F.Id("n"))), Sp, F.Id("a"), Sp, Leftrightarrow, Sp, Parenthesized(Seq(Forall, Sp, F.Id("x"), Sp, Comma, Sp, F.Id("a"), Sp, F.Id("x"), Sp, Neq, Sp, D(0), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("y"), Sp, Comma, Sp, F.Id("x"), Sp, Lt, Sp, F.Id("y"), Sp, To, Sp, F.Id("a"), Sp, F.Id("y"), Sp, Eq, Sp, D(0))), Sp, To, Sp, F.Id("a"), Sp, F.Id("x"), Sp, Eq, Sp, D(1))))]));

    private static Formula Formula3() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("IsASR"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, Colon, Sp, Named("Prop")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("IsASR"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, Leftrightarrow, Sp, Parenthesized(Seq(Parenthesized(Seq(Forall, Sp, F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, Named("Alternates"), Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"))), Sp, Land, Sp, Named("StartsOne"), Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"))), Sp, Land, Sp, Named("EndsOne"), Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"))))), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"), Sp, Comma, Sp, Named("Alternates"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Mapsto, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"))), Sp, Land, Sp, Named("StartsOne"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("i"), Sp, Mapsto, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"))))))))]));

    private static Formula Formula4() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("M"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("IsASM"), Sp, Parenthesized(Seq(F.Id("m"), Sp, Seq(Colon, Eq), Sp, F.Id("m"))), Sp, F.Id("M"), Sp, Colon, Sp, Named("Prop")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("M"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("IsASM"), Sp, Parenthesized(Seq(F.Id("m"), Sp, Seq(Colon, Eq), Sp, F.Id("m"))), Sp, F.Id("M"), Sp, Leftrightarrow, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("M"), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, F.Id("i"), Sp, Comma, Sp, new Formula.Subscript(Sum, F.Id("j")), Sp, Parenthesized(Seq(F.Id("M"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Eq, Sp, D(1))), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, F.Id("j"), Sp, Comma, Sp, new Formula.Subscript(Sum, F.Id("i")), Sp, Parenthesized(Seq(F.Id("M"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Eq, Sp, D(1))))))]));

    private static Formula Formula5() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("M"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("Contains312"), Sp, Parenthesized(Seq(F.Id("m"), Sp, Seq(Colon, Eq), Sp, F.Id("m"))), Sp, F.Id("M"), Sp, Colon, Sp, Named("Prop")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("M"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("Contains312"), Sp, Parenthesized(Seq(F.Id("m"), Sp, Seq(Colon, Eq), Sp, F.Id("m"))), Sp, F.Id("M"), Sp, Leftrightarrow, Sp, Parenthesized(Seq(Exists, Sp, Parenthesized(Seq(new Formula.Subscript(F.Id("i"), D(1)), Sp, new Formula.Subscript(F.Id("i"), D(2)), Sp, new Formula.Subscript(F.Id("i"), D(3)), Sp, new Formula.Subscript(F.Id("j"), D(1)), Sp, new Formula.Subscript(F.Id("j"), D(2)), Sp, new Formula.Subscript(F.Id("j"), D(3)), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("m"))), Sp, Comma, Sp, new Formula.Subscript(F.Id("i"), D(1)), Sp, Lt, Sp, new Formula.Subscript(F.Id("i"), D(2)), Sp, Land, Sp, new Formula.Subscript(F.Id("i"), D(2)), Sp, Lt, Sp, new Formula.Subscript(F.Id("i"), D(3)), Sp, Land, Sp, new Formula.Subscript(F.Id("j"), D(1)), Sp, Lt, Sp, new Formula.Subscript(F.Id("j"), D(2)), Sp, Land, Sp, new Formula.Subscript(F.Id("j"), D(2)), Sp, Lt, Sp, new Formula.Subscript(F.Id("j"), D(3)), Sp, Land, Sp, F.Id("M"), Sp, new Formula.Subscript(F.Id("i"), D(1)), Sp, new Formula.Subscript(F.Id("j"), D(3)), Sp, Eq, Sp, D(1), Sp, Land, Sp, F.Id("M"), Sp, new Formula.Subscript(F.Id("i"), D(2)), Sp, new Formula.Subscript(F.Id("j"), D(1)), Sp, Eq, Sp, D(1), Sp, Land, Sp, F.Id("M"), Sp, new Formula.Subscript(F.Id("i"), D(3)), Sp, new Formula.Subscript(F.Id("j"), D(2)), Sp, Eq, Sp, D(1))))]));

    private static Formula Formula6() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("ExtAvoids312"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, Colon, Sp, Named("Prop")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("ExtAvoids312"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, Leftrightarrow, Sp, Parenthesized(Seq(Exists, Sp, Parenthesized(Seq(F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Parenthesized(Seq(Named("hr"), Sp, Colon, Sp, F.Id("r"), Sp, Le, Sp, F.Id("m"))), Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, F.Id("k"), Sp, Le, Sp, F.Id("m"))), Sp, Parenthesized(Seq(F.Id("M"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("IsASM"), Sp, F.Id("M"), Sp, Land, Sp, Neg, Sp, Named("Contains312"), Sp, F.Id("M"), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, F.Id("i"), Sp, F.Id("j"), Sp, Comma, Sp, F.Id("M"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hr"), Sp, F.Id("i"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hk"), Sp, F.Id("j"))), Sp, Eq, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"))))))]));

    private static Formula Formula7() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("nonemptyRows"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N")))), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("nonemptyRows"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, Eq, Sp, Parenthesized(Seq(Parenthesized(Seq(Named("univ"), Sp, Dot, Sp, Named("filter"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Mapsto, Sp, Exists, Sp, F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Neq, Sp, D(0))))), Sp, Dot, Sp, Named("card"))))]));

    private static Formula Formula8() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, F.Id("S"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N")))), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, F.Id("S"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, F.Id("d"), Sp, Eq, Sp, Parenthesized(Seq(Named("Nat"), Sp, Dot, Sp, Named("card"), Sp, new Formula.SetLiteral([Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"), Sp, Bar, Sp, Named("IsASR"), Sp, F.Id("R"), Sp, Land, Sp, Named("ExtAvoids312"), Sp, F.Id("R"), Sp, Land, Sp, Named("nonemptyRows"), Sp, F.Id("R"), Sp, Eq, Sp, F.Id("d"))]))))]));

    private static Formula Formula9() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"))), Sp, Comma, Sp, Named("Alternates"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("j"), Sp, Mapsto, Sp, Named("if"), Sp, F.Id("p"), Sp, Eq, Sp, F.Id("j"), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0))), Sp, Land, Sp, Named("StartsOne"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("j"), Sp, Mapsto, Sp, Named("if"), Sp, F.Id("p"), Sp, Eq, Sp, F.Id("j"), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0))), Sp, Land, Sp, Named("EndsOne"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("j"), Sp, Mapsto, Sp, Named("if"), Sp, F.Id("p"), Sp, Eq, Sp, F.Id("j"), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0)))));

    private static Formula Formula10() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, F.Id("S"), Sp, F.Id("r"), Sp, F.Id("k"), Sp, D(0), Sp, Eq, Sp, D(1)));

    private static Formula Formula11() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("M"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASM"), Sp, F.Id("M"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("m"))), Sp, Comma, Sp, Exists, Sp, F.Id("j"), Sp, Comma, Sp, F.Id("M"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Eq, Sp, D(1)));

    private static Formula Formula12() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hr"), Sp, Colon, Sp, F.Id("r"), Sp, Le, Sp, F.Id("m"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, F.Id("k"), Sp, Le, Sp, F.Id("m"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("M"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASM"), Sp, F.Id("M"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("i"), Sp, F.Id("j"), Sp, Comma, Sp, F.Id("M"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hr"), Sp, F.Id("i"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hk"), Sp, F.Id("j"))), Sp, Eq, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(new Formula.Subscript(F.Id("i"), D(0)), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(Forall, Sp, F.Id("j"), Sp, Comma, Sp, F.Id("R"), Sp, new Formula.Subscript(F.Id("i"), D(0)), Sp, F.Id("j"), Sp, Eq, Sp, D(0))), Sp, To, Sp, Exists, Sp, F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("m"), Sp, Comma, Sp, F.Id("k"), Sp, Le, Sp, F.Id("j"), Sp, Dot, Sp, Named("val"), Sp, Land, Sp, F.Id("M"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hr"), Sp, new Formula.Subscript(F.Id("i"), D(0)))), Sp, F.Id("j"), Sp, Eq, Sp, D(1)));

    private static Formula Formula13() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(new Formula.Subscript(F.Id("i"), D(0)), Sp, new Formula.Subscript(F.Id("i"), D(1)), Sp, new Formula.Subscript(F.Id("i"), D(2)), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(new Formula.Subscript(F.Id("j"), D(1)), Sp, new Formula.Subscript(F.Id("j"), D(2)), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Parenthesized(Seq(new Formula.Subscript(F.Id("i"), D(0)), Sp, Lt, Sp, new Formula.Subscript(F.Id("i"), D(1)))), Sp, To, Sp, Parenthesized(Seq(new Formula.Subscript(F.Id("i"), D(1)), Sp, Lt, Sp, new Formula.Subscript(F.Id("i"), D(2)))), Sp, To, Sp, Parenthesized(Seq(new Formula.Subscript(F.Id("j"), D(1)), Sp, Lt, Sp, new Formula.Subscript(F.Id("j"), D(2)))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("j"), Sp, Comma, Sp, F.Id("R"), Sp, new Formula.Subscript(F.Id("i"), D(0)), Sp, F.Id("j"), Sp, Eq, Sp, D(0))), Sp, To, Sp, Neg, Sp, Parenthesized(Seq(F.Id("R"), Sp, new Formula.Subscript(F.Id("i"), D(1)), Sp, new Formula.Subscript(F.Id("j"), D(1)), Sp, Eq, Sp, D(1), Sp, Land, Sp, F.Id("R"), Sp, new Formula.Subscript(F.Id("i"), D(2)), Sp, new Formula.Subscript(F.Id("j"), D(2)), Sp, Eq, Sp, D(1)))));

    private static Formula Formula14() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, F.Id("p"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("p"), Sp, Le, Sp, F.Id("n"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("Alternates"), Sp, F.Id("a"))), Sp, To, Sp, Parenthesized(Seq(Named("StartsOne"), Sp, F.Id("a"))), Sp, To, Sp, Named("Alternates"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("p"), Sp, Mapsto, Sp, F.Id("a"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hp"), Sp, F.Id("i"))))), Sp, Land, Sp, Named("StartsOne"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("p"), Sp, Mapsto, Sp, F.Id("a"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hp"), Sp, F.Id("i")))))));

    private static Formula Formula15() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("p"), Sp, Le, Sp, F.Id("r"))), Sp, Comma, Sp, Named("topRows"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, Parenthesized(Seq(F.Id("p"), Sp, Seq(Colon, Eq), Sp, F.Id("p"))), Sp, F.Id("R"), Sp, Named("hp"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("p"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("p"), Sp, Le, Sp, F.Id("r"))), Sp, Comma, Sp, Named("topRows"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, Parenthesized(Seq(F.Id("p"), Sp, Seq(Colon, Eq), Sp, F.Id("p"))), Sp, F.Id("R"), Sp, Named("hp"), Sp, Eq, Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Mapsto, Sp, F.Id("R"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hp"), Sp, F.Id("i"))), Sp, F.Id("j"))))]));

    private static Formula Formula16() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("p"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("p"), Sp, Le, Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Named("IsASR"), Sp, Parenthesized(Seq(Named("topRows"), Sp, F.Id("R"), Sp, Named("hp")))));

    private static Formula Formula17() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("p"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("p"), Sp, Le, Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Named("ExtAvoids312"), Sp, Parenthesized(Seq(Named("topRows"), Sp, F.Id("R"), Sp, Named("hp")))));

    private static Formula Formula18() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Named("LineState"), Sp, Parenthesized(Seq(F.Id("n"), Sp, Seq(Colon, Eq), Sp, F.Id("n"))), Sp, F.Id("a"), Sp, Colon, Sp, Named("Prop")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Named("LineState"), Sp, Parenthesized(Seq(F.Id("n"), Sp, Seq(Colon, Eq), Sp, F.Id("n"))), Sp, F.Id("a"), Sp, Leftrightarrow, Sp, Parenthesized(Seq(Parenthesized(Seq(Parenthesized(Seq(Forall, Sp, F.Id("i"), Sp, Comma, Sp, F.Id("a"), Sp, F.Id("i"), Sp, Eq, Sp, D(0))), Sp, Land, Sp, Parenthesized(Seq(new Formula.Subscript(Sum, F.Id("i")), Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("i"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, D(0))), Sp, Lor, Sp, Exists, Sp, F.Id("x"), Sp, Comma, Sp, F.Id("a"), Sp, F.Id("x"), Sp, Neq, Sp, D(0), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, F.Id("y"), Sp, Comma, Sp, F.Id("x"), Sp, Lt, Sp, F.Id("y"), Sp, To, Sp, F.Id("a"), Sp, F.Id("y"), Sp, Eq, Sp, D(0))), Sp, Land, Sp, Parenthesized(Seq(new Formula.Subscript(Sum, F.Id("i")), Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("i"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, Named("if"), Sp, F.Id("a"), Sp, F.Id("x"), Sp, Eq, Sp, D(1), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0))))]));

    private static Formula Formula19() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("Alternates"), Sp, F.Id("a"))), Sp, To, Sp, Parenthesized(Seq(Named("StartsOne"), Sp, F.Id("a"))), Sp, To, Sp, Named("LineState"), Sp, F.Id("a")));

    private static Formula Formula20() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(new Formula.Subscript(Sum, F.Id("j")), Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, Named("if"), Sp, Exists, Sp, F.Id("j"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Neq, Sp, D(0), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0)));

    private static Formula Formula21() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(new Formula.Subscript(Sum, F.Id("j")), Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, D(1), Sp, Leftrightarrow, Sp, Exists, Sp, F.Id("j"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Neq, Sp, D(0)));

    private static Formula Formula22() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("StartsOne"), Sp, F.Id("a"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("x"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("x"), Sp, Eq, Sp, Minus, Sp, D(1))), Sp, To, Sp, Exists, Sp, F.Id("y"), Sp, Comma, Sp, F.Id("y"), Sp, Lt, Sp, F.Id("x"), Sp, Land, Sp, F.Id("a"), Sp, F.Id("y"), Sp, Eq, Sp, D(1)));

    private static Formula Formula23() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("EndsOne"), Sp, F.Id("a"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("x"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("x"), Sp, Eq, Sp, Minus, Sp, D(1))), Sp, To, Sp, Exists, Sp, F.Id("y"), Sp, Comma, Sp, F.Id("x"), Sp, Lt, Sp, F.Id("y"), Sp, Land, Sp, F.Id("a"), Sp, F.Id("y"), Sp, Eq, Sp, D(1)));

    private static Formula Formula24() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("Alternates"), Sp, F.Id("a"))), Sp, To, Sp, Parenthesized(Seq(Named("StartsOne"), Sp, F.Id("a"))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(new Formula.Subscript(Sum, F.Id("i")), Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("i"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, D(1))), Sp, To, Sp, Named("EndsOne"), Sp, F.Id("a")));

    private static Formula Formula25() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("M"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASM"), Sp, F.Id("M"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("m"))), Sp, Comma, Sp, Named("EndsOne"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("i"), Sp, Mapsto, Sp, F.Id("M"), Sp, F.Id("i"), Sp, F.Id("j")))));

    private static Formula Formula26() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(new Formula.Subscript(F.Id("j"), D(1)), Sp, new Formula.Subscript(F.Id("j"), D(2)), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, new Formula.Subscript(F.Id("j"), D(1)), Sp, Eq, Sp, Minus, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, new Formula.Subscript(F.Id("j"), D(2)), Sp, Eq, Sp, Minus, Sp, D(1))), Sp, To, Sp, new Formula.Subscript(F.Id("j"), D(1)), Sp, Eq, Sp, new Formula.Subscript(F.Id("j"), D(2))));

    private static Formula Formula27() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(new Formula.Subscript(F.Id("i"), D(1)), Sp, new Formula.Subscript(F.Id("i"), D(2)), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, new Formula.Subscript(F.Id("i"), D(1)), Sp, F.Id("j"), Sp, Eq, Sp, Minus, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(F.Id("R"), Sp, new Formula.Subscript(F.Id("i"), D(2)), Sp, F.Id("j"), Sp, Eq, Sp, Minus, Sp, D(1))), Sp, To, Sp, new Formula.Subscript(F.Id("i"), D(1)), Sp, Eq, Sp, new Formula.Subscript(F.Id("i"), D(2))));

    private static Formula Formula28() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("Alternates"), Sp, F.Id("a"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("x"), Sp, F.Id("y"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("x"), Sp, Lt, Sp, F.Id("y"))), Sp, To, Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("x"), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("y"), Sp, Eq, Sp, D(1))), Sp, To, Sp, Exists, Sp, F.Id("z"), Sp, Comma, Sp, F.Id("x"), Sp, Lt, Sp, F.Id("z"), Sp, Land, Sp, F.Id("z"), Sp, Lt, Sp, F.Id("y"), Sp, Land, Sp, F.Id("a"), Sp, F.Id("z"), Sp, Eq, Sp, Minus, Sp, D(1)));

    private static Formula Formula29() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("k"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, D(0), Rangle), Sp, Neq, Sp, Minus, Sp, D(1)));

    private static Formula Formula30() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("b"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("a"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("b"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, F.Id("a"), Sp, Eq, Sp, F.Id("b")));

    private static Formula Formula31() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("Alternates"), Sp, F.Id("a"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("x"), Sp, Comma, Sp, F.Id("a"), Sp, F.Id("x"), Sp, Neq, Sp, Minus, Sp, D(1))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("p"), Sp, Eq, Sp, D(1))), Sp, To, Sp, Forall, Sp, F.Id("x"), Sp, Comma, Sp, F.Id("a"), Sp, F.Id("x"), Sp, Eq, Sp, Named("if"), Sp, F.Id("x"), Sp, Eq, Sp, F.Id("p"), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0)));

    private static Formula Formula32() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("r"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("c"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, F.Id("R"), Sp, Seq(Langle, Sp, D(0), Rangle), Sp, F.Id("c"), Sp, Neq, Sp, Minus, Sp, D(1)));

    private static Formula Formula33() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hr"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hr")), Rangle), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, Exists, Sp, F.Id("p"), Sp, Comma, Sp, Forall, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, Seq(Langle, Sp, D(0), Rangle), Sp, F.Id("c"), Sp, Eq, Sp, Named("if"), Sp, F.Id("c"), Sp, Eq, Sp, F.Id("p"), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0)));

    private static Formula Formula34() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("x"), Sp, F.Id("z"), Sp, F.Id("y"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("x"), Sp, Lt, Sp, F.Id("z"))), Sp, To, Sp, Parenthesized(Seq(F.Id("z"), Sp, Lt, Sp, F.Id("y"))), Sp, To, Sp, Named("let"), Sp, F.Id("a"), Sp, Seq(Colon, Eq), Sp, Named("fun"), Sp, F.Id("w"), Sp, Mapsto, Sp, Named("if"), Sp, F.Id("w"), Sp, Eq, Sp, F.Id("x"), Sp, Named("then"), Sp, Parenthesized(Seq(D(1), Sp, Colon, Sp, Named("SignType"))), Sp, Named("else"), Sp, Named("if"), Sp, F.Id("w"), Sp, Eq, Sp, F.Id("z"), Sp, Named("then"), Sp, Minus, Sp, D(1), Sp, Named("else"), Sp, Named("if"), Sp, F.Id("w"), Sp, Eq, Sp, F.Id("y"), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0), Sp, Semi, Sp, Named("Alternates"), Sp, F.Id("a"), Sp, Land, Sp, Named("StartsOne"), Sp, F.Id("a"), Sp, Land, Sp, Named("EndsOne"), Sp, F.Id("a")));

    private static Formula Formula35() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("emptyRows"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, Colon, Sp, Named("Finset"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r")))), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("emptyRows"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, Eq, Sp, Parenthesized(Seq(Named("univ"), Sp, Dot, Sp, Named("filter"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Mapsto, Sp, Forall, Sp, F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Eq, Sp, D(0))))))]));

    private static Formula Formula36() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Named("colSum"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, F.Id("j"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z")))), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Named("colSum"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, F.Id("j"), Sp, Eq, Sp, Parenthesized(Seq(new Formula.Subscript(Sum, F.Id("i")), Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))))]));

    private static Formula Formula37() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("deficientColumns"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, Colon, Sp, Named("Finset"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k")))), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("deficientColumns"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, Eq, Sp, Parenthesized(Seq(Named("univ"), Sp, Dot, Sp, Named("filter"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"), Sp, Mapsto, Sp, Named("colSum"), Sp, F.Id("R"), Sp, F.Id("j"), Sp, Eq, Sp, D(0))))))]));

    private static Formula Formula38() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, F.Id("i"), Sp, InMacro, Sp, Named("emptyRows"), Sp, F.Id("R"), Sp, Leftrightarrow, Sp, Forall, Sp, F.Id("j"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Eq, Sp, D(0)));

    private static Formula Formula39() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, F.Id("j"), Sp, InMacro, Sp, Named("deficientColumns"), Sp, F.Id("R"), Sp, Leftrightarrow, Sp, Named("colSum"), Sp, F.Id("R"), Sp, F.Id("j"), Sp, Eq, Sp, D(0)));

    private static Formula Formula40() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Named("colSum"), Sp, F.Id("R"), Sp, F.Id("j"), Sp, Eq, Sp, D(0), Sp, Lor, Sp, Named("colSum"), Sp, F.Id("R"), Sp, F.Id("j"), Sp, Eq, Sp, D(1)));

    private static Formula Formula41() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(new Formula.Subscript(Sum, F.Id("i")), Sp, new Formula.Subscript(Sum, F.Id("j")), Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, Named("nonemptyRows"), Sp, F.Id("R")));

    private static Formula Formula42() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("emptyRows"), Sp, F.Id("R"))), Sp, Dot, Sp, Named("card"), Sp, Plus, Sp, Named("nonemptyRows"), Sp, F.Id("R"), Sp, Eq, Sp, F.Id("r")));

    private static Formula Formula43() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("deficientColumns"), Sp, F.Id("R"))), Sp, Dot, Sp, Named("card"), Sp, Plus, Sp, Named("nonemptyRows"), Sp, F.Id("R"), Sp, Eq, Sp, F.Id("k")));

    private static Formula Formula44() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Named("nonemptyRows"), Sp, F.Id("R"), Sp, Le, Sp, F.Id("r")));

    private static Formula Formula45() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Named("nonemptyRows"), Sp, F.Id("R"), Sp, Le, Sp, F.Id("k")));

    private static Formula Formula46() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("nonemptyRows"), Sp, F.Id("R"), Sp, Eq, Sp, F.Id("k"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Named("colSum"), Sp, F.Id("R"), Sp, F.Id("j"), Sp, Eq, Sp, D(1)));

    private static Formula Formula47() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, F.Id("p"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("p"), Sp, Le, Sp, F.Id("n"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(new Formula.Subscript(Sum, Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("p"))), Sp, Parenthesized(Seq(F.Id("a"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hp"), Sp, F.Id("i"))), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, new Formula.Subscript(Sum, Seq(F.Id("i"), Sp, InMacro, Sp, Named("univ"), Sp, Dot, Sp, Named("filter"), Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, Mapsto, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("p"))))), Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("i"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z")))))));

    private static Formula Formula48() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, F.Id("p"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("p"), Sp, Le, Sp, F.Id("n"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Parenthesized(Seq(new Formula.Subscript(Sum, F.Id("i")), Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("i"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Parenthesized(Seq(new Formula.Subscript(Sum, Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("p"))), Sp, Parenthesized(Seq(F.Id("a"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hp"), Sp, F.Id("i"))), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, D(0))), Sp, To, Sp, Exists, Sp, F.Id("i"), Sp, Comma, Sp, F.Id("p"), Sp, Le, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Land, Sp, F.Id("a"), Sp, F.Id("i"), Sp, Eq, Sp, D(1)));

    private static Formula Formula49() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hr"), Sp, Colon, Sp, F.Id("r"), Sp, Le, Sp, F.Id("m"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, F.Id("k"), Sp, Le, Sp, F.Id("m"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("M"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("m"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASM"), Sp, F.Id("M"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("i"), Sp, F.Id("j"), Sp, Comma, Sp, F.Id("M"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hr"), Sp, F.Id("i"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hk"), Sp, F.Id("j"))), Sp, Eq, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("j"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Parenthesized(Seq(Parenthesized(Seq(new Formula.Subscript(Sum, F.Id("i")), Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, F.Id("j"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, D(0))), Sp, To, Sp, Exists, Sp, F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("m"), Sp, Comma, Sp, F.Id("r"), Sp, Le, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Land, Sp, F.Id("M"), Sp, F.Id("i"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, Named("hk"), Sp, F.Id("j"))), Sp, Eq, Sp, D(1)));
    private static Formula TransportFormula0() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("b"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("m"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("f"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("Fin"), Sp, F.Id("m"))), Sp, Comma, Sp, Parenthesized(Seq(Named("StrictMono"), Sp, F.Id("f"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("b"), Sp, Parenthesized(Seq(F.Id("f"), Sp, F.Id("u"))), Sp, Eq, Sp, F.Id("a"), Sp, F.Id("u"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("x"), Sp, Comma, Sp, Parenthesized(Seq(Neg, Sp, Exists, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("f"), Sp, F.Id("u"), Sp, Eq, Sp, F.Id("x"))), Sp, To, Sp, F.Id("b"), Sp, F.Id("x"), Sp, Eq, Sp, D(0))), Sp, To, Sp, Parenthesized(Seq(Named("Alternates"), Sp, F.Id("a"))), Sp, To, Sp, Parenthesized(Seq(Named("StartsOne"), Sp, F.Id("a"))), Sp, To, Sp, Named("Alternates"), Sp, F.Id("b"), Sp, Land, Sp, Named("StartsOne"), Sp, F.Id("b")));

    private static Formula TransportFormula1() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("b"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("m"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("f"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("Fin"), Sp, F.Id("m"))), Sp, Comma, Sp, Parenthesized(Seq(Named("StrictMono"), Sp, F.Id("f"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("b"), Sp, Parenthesized(Seq(F.Id("f"), Sp, F.Id("u"))), Sp, Eq, Sp, F.Id("a"), Sp, F.Id("u"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("x"), Sp, Comma, Sp, Parenthesized(Seq(Neg, Sp, Exists, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("f"), Sp, F.Id("u"), Sp, Eq, Sp, F.Id("x"))), Sp, To, Sp, F.Id("b"), Sp, F.Id("x"), Sp, Eq, Sp, D(0))), Sp, To, Sp, Parenthesized(Seq(Named("EndsOne"), Sp, F.Id("a"))), Sp, To, Sp, Named("EndsOne"), Sp, F.Id("b")));

    private static Formula TransportFormula4() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("b"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("m"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("f"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("Fin"), Sp, F.Id("m"))), Sp, Comma, Sp, Parenthesized(Seq(Named("StrictMono"), Sp, F.Id("f"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("b"), Sp, Parenthesized(Seq(F.Id("f"), Sp, F.Id("u"))), Sp, Eq, Sp, F.Id("a"), Sp, F.Id("u"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("x"), Sp, Comma, Sp, Parenthesized(Seq(Neg, Sp, Exists, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("f"), Sp, F.Id("u"), Sp, Eq, Sp, F.Id("x"))), Sp, To, Sp, F.Id("b"), Sp, F.Id("x"), Sp, Eq, Sp, D(0))), Sp, To, Sp, Parenthesized(Seq(new Formula.Subscript(Sum, F.Id("u")), Sp, Parenthesized(Seq(F.Id("a"), Sp, F.Id("u"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))))), Sp, Eq, Sp, new Formula.Subscript(Sum, F.Id("x")), Sp, Parenthesized(Seq(F.Id("b"), Sp, F.Id("x"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z")))))));
}
