using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Combinatorics.AlternatingSignRectangles;

internal sealed class SquarePrefixGeometryDocument : IScribeDocumentDefinition
{
    private static readonly LibraryNoteRef Source =
        LibraryNoteRef.Create("D5/L/PermutationPatterns/hongesberg2026asr");

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "SquarePrefixGeometry for extendably 312-avoiding alternating sign rectangles.",
        H("SquarePrefixGeometry"), Blocks(
            Paragraph(Text("The formulas retain Lean function names and typed binders. Natural subtraction is truncated subtraction; slash between natural numbers is Nat.div. Constructor proof fields and certified cast proofs are suppressed; matrix entries and subtype values are explicit.")),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-2"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.line_restrict"), H("line_restrict"),
                StatementSource.FromAuthor(Formula2()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-3"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.ends_restrict"), H("ends_restrict"),
                StatementSource.FromAuthor(Formula3()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-5"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.shiftCol"), H("shiftCol"),
                StatementSource.FromAuthor(Formula5()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-6"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.prefix_first_column_zero"), H("prefix_first_column_zero"),
                StatementSource.FromAuthor(Formula6()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-7"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.prefix_outside_zero"), H("prefix_outside_zero"),
                StatementSource.FromAuthor(Formula7()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-8"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.prefix_width"), H("prefix_width"),
                StatementSource.FromAuthor(Formula8()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-9"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.prefix_shift_column_sum"), H("prefix_shift_column_sum"),
                StatementSource.FromAuthor(Formula9()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-10"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.prefixSquare"), H("prefixSquare"),
                StatementSource.FromAuthor(Formula10()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The displayed equality gives the defining mathematical data; Prop-valued constructor fields are omitted."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-11"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.prefixSquare_isASM"), H("prefixSquare_isASM"),
                StatementSource.FromAuthor(Formula11()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-12"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.prefixSquare_avoids"), H("prefixSquare_avoids"),
                StatementSource.FromAuthor(Formula12()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-13"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.below_prefix_interior_zero"), H("below_prefix_interior_zero"),
                StatementSource.FromAuthor(Formula13()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-14"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.pivot_not_one_at_prefix_end"), H("pivot_not_one_at_prefix_end"),
                StatementSource.FromAuthor(Formula14()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-15"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.pivot_no_minus_after_prefix"), H("pivot_no_minus_after_prefix"),
                StatementSource.FromAuthor(Formula15()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-16"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.first_column_zero_except_pivot"), H("first_column_zero_except_pivot"),
                StatementSource.FromAuthor(Formula16()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-17"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.below_pivot_end_not_minus"), H("below_pivot_end_not_minus"),
                StatementSource.FromAuthor(Formula17()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-18"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.pivot_row_singleton_if_no_minus"), H("pivot_row_singleton_if_no_minus"),
                StatementSource.FromAuthor(Formula18()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma),
            Describe.Lean(DescribeId.Create("square-prefix-geometry-19"),
                DeclarationHandle.Create("D5/S3/Combinatorics/AlternatingSignRectangles/SquarePrefixGeometry.pivot_row_right_singleton"), H("pivot_row_right_singleton"),
                StatementSource.FromAuthor(Formula19()), AssessedProvenance.FromRepo(Source),
                Blocks(Paragraph(Text("The implication holds for every parameter and sign matrix in the stated domains."))), DescribeRole.Lemma)), []));

    private static Formula Named(string name) => Seq(Operatorname, Grp(F.Id(name)));
    private static Formula Parenthesized(Formula value) => Seq(Open, value, Close);





    private static Formula Formula2() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("b"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("m"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("f"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("Fin"), Sp, F.Id("m"))), Sp, Comma, Sp, Parenthesized(Seq(Named("StrictMono"), Sp, F.Id("f"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("b"), Sp, Parenthesized(Seq(F.Id("f"), Sp, F.Id("u"))), Sp, Eq, Sp, F.Id("a"), Sp, F.Id("u"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("x"), Sp, Comma, Sp, Parenthesized(Seq(Neg, Sp, Exists, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("f"), Sp, F.Id("u"), Sp, Eq, Sp, F.Id("x"))), Sp, To, Sp, F.Id("b"), Sp, F.Id("x"), Sp, Eq, Sp, D(0))), Sp, To, Sp, Parenthesized(Seq(Named("Alternates"), Sp, F.Id("b"))), Sp, To, Sp, Parenthesized(Seq(Named("StartsOne"), Sp, F.Id("b"))), Sp, To, Sp, Named("Alternates"), Sp, F.Id("a"), Sp, Land, Sp, Named("StartsOne"), Sp, F.Id("a")));

    private static Formula Formula3() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, F.Id("m"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("a"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("b"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("m"), Sp, To, Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("f"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("n"), Sp, To, Sp, Named("Fin"), Sp, F.Id("m"))), Sp, Comma, Sp, Parenthesized(Seq(Named("StrictMono"), Sp, F.Id("f"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("b"), Sp, Parenthesized(Seq(F.Id("f"), Sp, F.Id("u"))), Sp, Eq, Sp, F.Id("a"), Sp, F.Id("u"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("x"), Sp, Comma, Sp, Parenthesized(Seq(Neg, Sp, Exists, Sp, F.Id("u"), Sp, Comma, Sp, F.Id("f"), Sp, F.Id("u"), Sp, Eq, Sp, F.Id("x"))), Sp, To, Sp, F.Id("b"), Sp, F.Id("x"), Sp, Eq, Sp, D(0))), Sp, To, Sp, Parenthesized(Seq(Named("EndsOne"), Sp, F.Id("b"))), Sp, To, Sp, Named("EndsOne"), Sp, F.Id("a")));



    private static Formula Formula5() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("p"), Sp, Plus, Sp, D(1), Sp, Le, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("x"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("p"))), Sp, Comma, Sp, Named("shiftCol"), Sp, Parenthesized(Seq(F.Id("p"), Sp, Seq(Colon, Eq), Sp, F.Id("p"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, Named("hp"), Sp, F.Id("x"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("p"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("p"), Sp, Plus, Sp, D(1), Sp, Le, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("x"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("p"))), Sp, Comma, Sp, Named("shiftCol"), Sp, Parenthesized(Seq(F.Id("p"), Sp, Seq(Colon, Eq), Sp, F.Id("p"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, Named("hp"), Sp, F.Id("x"), Sp, Eq, Sp, Parenthesized(Seq(Langle, Sp, Seq(F.Id("x"), Sp, Dot, Sp, Named("val"), Sp, Plus, Sp, D(1)), Rangle)))]));

    private static Formula Formula6() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("u"), Sp, Lt, Sp, F.Id("i"))), Sp, To, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, F.Id("R"), Sp, F.Id("u"), Sp, Seq(Langle, Sp, D(0), Rangle), Sp, Eq, Sp, D(0)));

    private static Formula Formula7() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("b"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("u"), Sp, Lt, Sp, F.Id("i"))), Sp, To, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("b"), Sp, Dot, Sp, Named("val"))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("v"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("v"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("v"), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("b"), Sp, Eq, Sp, D(0)));

    private static Formula Formula8() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Plus, Sp, D(1), Sp, Le, Sp, F.Id("k")));

    private static Formula Formula9() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("k"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, D(0), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("x"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, Comma, Sp, Named("colSum"), Sp, Parenthesized(Seq(Named("topRows"), Sp, Parenthesized(Seq(F.Id("p"), Sp, Seq(Colon, Eq), Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, F.Id("R"), Sp, new Formula.Placeholder())), Sp, Parenthesized(Seq(Named("shiftCol"), Sp, new Formula.Placeholder(), Sp, F.Id("x"))), Sp, Eq, Sp, D(1)));

    private static Formula Formula10() =>
        Disp(new Formula.Aligned([Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Plus, Sp, D(1), Sp, Le, Sp, F.Id("k"))), Sp, Comma, Sp, Named("prefixSquare"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, F.Id("i"), Sp, Named("hp"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, Named("SignType")), Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(Named("hp"), Sp, Colon, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Plus, Sp, D(1), Sp, Le, Sp, F.Id("k"))), Sp, Comma, Sp, Named("prefixSquare"), Sp, Parenthesized(Seq(F.Id("r"), Sp, Seq(Colon, Eq), Sp, F.Id("r"))), Sp, Parenthesized(Seq(F.Id("k"), Sp, Seq(Colon, Eq), Sp, F.Id("k"))), Sp, F.Id("R"), Sp, F.Id("i"), Sp, Named("hp"), Sp, Eq, Sp, Parenthesized(Seq(Named("fun"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Mapsto, Sp, F.Id("R"), Sp, Parenthesized(Seq(Named("Fin"), Sp, Dot, Sp, Named("castLE"), Sp, new Formula.Placeholder(), Sp, F.Id("u"))), Sp, Parenthesized(Seq(Named("shiftCol"), Sp, new Formula.Placeholder(), Sp, F.Id("c"))))))]));

    private static Formula Formula11() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("k"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, D(0), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, Named("IsASM"), Sp, Parenthesized(Seq(Named("prefixSquare"), Sp, F.Id("R"), Sp, F.Id("i"), Sp, new Formula.Placeholder()))));

    private static Formula Formula12() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Plus, Sp, D(1), Sp, Le, Sp, F.Id("k"))), Sp, To, Sp, Neg, Sp, Named("Contains312"), Sp, Parenthesized(Seq(Named("prefixSquare"), Sp, F.Id("R"), Sp, F.Id("i"), Sp, new Formula.Placeholder()))));

    private static Formula Formula13() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, F.Id("v"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, Parenthesized(Seq(F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Le, Sp, F.Id("v"), Sp, Dot, Sp, Named("val"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("c"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("c"), Sp, Dot, Sp, Named("val"))), Sp, To, Sp, Parenthesized(Seq(F.Id("c"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, To, Sp, F.Id("R"), Sp, F.Id("v"), Sp, F.Id("c"), Sp, Eq, Sp, D(0)));

    private static Formula Formula14() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, To, Sp, F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(F.Id("i"), Sp, Dot, Sp, Named("val")), Rangle), Sp, Neq, Sp, D(1)));

    private static Formula Formula15() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("c"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("c"), Sp, Dot, Sp, Named("val"))), Sp, To, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("c"), Sp, Neq, Sp, Minus, Sp, D(1)));

    private static Formula Formula16() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Forall, Sp, F.Id("v"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("v"), Sp, Seq(Langle, Sp, D(0), Rangle), Sp, Eq, Sp, Named("if"), Sp, F.Id("v"), Sp, Eq, Sp, F.Id("i"), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0)));

    private static Formula Formula17() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(Named("hk"), Sp, Colon, Sp, D(0), Sp, Lt, Sp, F.Id("k"))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, F.Id("v"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(D(0), Sp, Comma, Sp, Named("hk")), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"))), Sp, To, Sp, Parenthesized(Seq(F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("v"), Sp, Dot, Sp, Named("val"))), Sp, To, Sp, F.Id("R"), Sp, F.Id("v"), Sp, Seq(Langle, Sp, Seq(F.Id("i"), Sp, Dot, Sp, Named("val")), Rangle), Sp, Neq, Sp, Minus, Sp, D(1)));

    private static Formula Formula18() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("k"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, D(0), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Comma, Sp, new Formula.Placeholder()), Rangle), Sp, Neq, Sp, Minus, Sp, D(1))), Sp, To, Sp, Forall, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("c"), Sp, Eq, Sp, Named("if"), Sp, F.Id("c"), Sp, Dot, Sp, Named("val"), Sp, Eq, Sp, D(0), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0)));

    private static Formula Formula19() =>
        Disp(Seq(Forall, Sp, Parenthesized(Seq(F.Id("r"), Sp, F.Id("k"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("R"), Sp, Colon, Sp, Named("Matrix"), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("r"))), Sp, Parenthesized(Seq(Named("Fin"), Sp, F.Id("k"))), Sp, Named("SignType"))), Sp, Comma, Sp, Parenthesized(Seq(Named("IsASR"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(Named("ExtAvoids312"), Sp, F.Id("R"))), Sp, To, Sp, Parenthesized(Seq(D(0), Sp, Lt, Sp, F.Id("k"))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("i"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"))), Sp, Comma, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, D(0), Rangle), Sp, Eq, Sp, D(1))), Sp, To, Sp, Parenthesized(Seq(Forall, Sp, F.Id("u"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("r"), Sp, Comma, Sp, F.Id("u"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, Exists, Sp, F.Id("c"), Sp, Comma, Sp, F.Id("R"), Sp, F.Id("u"), Sp, F.Id("c"), Sp, Neq, Sp, D(0))), Sp, To, Sp, Parenthesized(Seq(F.Id("R"), Sp, F.Id("i"), Sp, Seq(Langle, Sp, Seq(F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Comma, Sp, new Formula.Placeholder()), Rangle), Sp, Eq, Sp, Minus, Sp, D(1))), Sp, To, Sp, Exists, Sp, F.Id("q"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"), Sp, Comma, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("q"), Sp, Dot, Sp, Named("val"), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, F.Id("c"), Sp, Colon, Sp, Named("Fin"), Sp, F.Id("k"), Sp, Comma, Sp, F.Id("i"), Sp, Dot, Sp, Named("val"), Sp, Lt, Sp, F.Id("c"), Sp, Dot, Sp, Named("val"), Sp, To, Sp, F.Id("R"), Sp, F.Id("i"), Sp, F.Id("c"), Sp, Eq, Sp, Named("if"), Sp, F.Id("c"), Sp, Eq, Sp, F.Id("q"), Sp, Named("then"), Sp, D(1), Sp, Named("else"), Sp, D(0)))));
}
