<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>StrataLint.Cli</RootNamespace>
    <AssemblyName>StrataLint</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../StrataLint.Engine/StrataLint.Engine.csproj" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>
