using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Weil.Probability;

internal sealed class GeometricLiNegativeTypeDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S3/Weil/Probability/GeometricLiNegativeType.";

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "The original Li geometric energy as an exact integrated Gram distance on every integer sample.",
        H("GeometricLiNegativeType"), Blocks(
            Describe.Lean(DescribeId.Create("integergeometric"),
                DeclarationHandle.Create(Prefix + "integerGeometric"), H("Integer continuation on the whole circle"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The original finite geometric polynomial is continued to negative indices with its removable identity value n."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("integergeometric-zero"),
                DeclarationHandle.Create(Prefix + "integerGeometric_zero"), H("The zero index has zero value"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The cocycle origin agrees on and off the identity."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("integergeometric-nat"),
                DeclarationHandle.Create(Prefix + "integerGeometric_nat"), H("Retain the original polynomial"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Natural indices agree exactly with the existing geometricPolynomial definition."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("integergeometric-add"),
                DeclarationHandle.Create(Prefix + "integerGeometric_add"), H("One integer cocycle"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The same formula obeys b(m+n)=b(m)+z^m b(n), including negative indices and the identity."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("integergeometric-neg"),
                DeclarationHandle.Create(Prefix + "integerGeometric_neg"), H("Negative indices retain the energy"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The negative branch is a unit-modulus factor times the negative positive branch."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("integergeometric-continuous"),
                DeclarationHandle.Create(Prefix + "integerGeometric_continuous"), H("Continuity through the removable point"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The natural polynomial and negative-index identity prove continuity everywhere."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("integergeometric-energy"),
                DeclarationHandle.Create(Prefix + "integerGeometric_energy"), H("The original absolute-index energy"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Both integer branches have exactly the old geometric energy at the absolute index."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("integergeometric-distance"),
                DeclarationHandle.Create(Prefix + "integerGeometric_distance"), H("Exact cocycle distance"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A difference of two cocycle values has the original geometric energy at their integer difference."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("geometricligram"),
                DeclarationHandle.Create(Prefix + "geometricLiGram"), H("Construct the original integrated Gram matrix"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The matrix integrates real inner products of the same integer geometric functions under the original finite measure."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("geometricligram-quadratic"),
                DeclarationHandle.Create(Prefix + "geometricLiGram_quadratic"), H("A concrete squared-integral identity"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Every real Gram quadratic form is the original nonnegative-scale integral of the squared coefficient sum."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("geometricligram-possemidef"),
                DeclarationHandle.Create(Prefix + "geometricLiGram_posSemidef"), H("The constructed Gram matrix is positive"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Positivity follows from the explicit integral, without a supplied embedding or positivity field."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("geometricligram-distance"),
                DeclarationHandle.Create(Prefix + "geometricLiGram_distance"), H("Gram distance equals the original Li value"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The matrix distance is exactly reconstructedLi at the absolute integer difference."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("reconstructed-li-zero-sum-identity"),
                DeclarationHandle.Create(Prefix + "reconstructed_li_zero_sum_identity"), H("Exact negative-type identity"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every zero-sum real vector the Li form is minus twice the same scaled squared integral."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("reconstructed-li-conditionally-negative"),
                DeclarationHandle.Create(Prefix + "reconstructed_li_conditionally_negative"), H("Conditional negative type on all integer samples"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The full arbitrary finite integer sample is allowed, with repeated indices, empty samples and the identity atom."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("reconstructed-li-exponential-possemidef"),
                DeclarationHandle.Create(Prefix + "reconstructed_li_exponential_posSemidef"), H("Derive the actual exponential positivity"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The finite Gram Schoenberg theorem proves complex-coefficient positivity for all nonnegative times without an exponential-positivity premise."))), DescribeRole.Theorem))));
}
