import LeanInformationAudit.Tests.Occurrence.RootCatalog.Snapshot

open D5.S3.ConceptDynamics.Interventions.ObservationInterventionSeparation
open D5.S3.ConceptDynamics.Interventions.InterventionCounterfactualSeparation
open D5.S3.ConceptDynamics.InformationEscapeRealizations.UnifiedCausalAlignment

instance : DecidableEq IC.Model :=
  D5.S3.ConceptDynamics.InformationEscapeArenas.FourthFifthArenas.modelDecidableEq

register_information_theorem observation_strictly_weaker_than_intervention
  in observationInterventionLawArena
  object_arena unifiedArena catalog fixtureCausal
  primitives observationInterventionUnifiedRealization.toPrimitiveBundle
  realization observation_intervention_unified_realization

register_information_theorem intervention_strictly_weaker_than_counterfactual
  in interventionCounterfactualLawArena
  object_arena unifiedArena catalog fixtureCausal
  primitives interventionCounterfactualUnifiedRealization.toPrimitiveBundle
  realization intervention_counterfactual_unified_realization
