using static StrataLint.Scribe.DefinitionDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S0.Certificates.Combinatorics;

internal sealed class UnitIntervalParkingFoataDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S0/Certificates/Combinatorics/UnitIntervalParkingFoata.";
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Parking-process specifications, Foata commutation for distinct-letter and nondecreasing words, and a recursive characterisation of unit-interval parking. Conjecture 6.3 remains unproved.",
        H("Unit-interval parking and Foata transformation"),
        Blocks(
            Describe.Lean(DescribeId.Create("park-step"),
                DeclarationHandle.Create(Prefix + "parkStep"), H("parkStep"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Given occupied spots and a preference, the structural search advances to the first vacant spot at or above that preference."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("park-from"),
                DeclarationHandle.Create(Prefix + "parkFrom"), H("parkFrom"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The cars in the remaining word park in list order, adding each chosen spot to the occupied list."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("spots"),
                DeclarationHandle.Create(Prefix + "spots"), H("spots"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Parking starts with no occupied spots and returns the final spots in car order."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("is-parking-function"),
                DeclarationHandle.Create(Prefix + "IsParkingFunction"), H("IsParkingFunction"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Every preference and final spot must be between one and the length of the preference word."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("is-unit-interval"),
                DeclarationHandle.Create(Prefix + "IsUnitInterval"), H("IsUnitInterval"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A parking function is unit interval when each final spot is at most one greater than its corresponding preference."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("rotate-blocks"),
                DeclarationHandle.Create(Prefix + "rotateBlocks"), H("rotateBlocks"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The pending list records an unfinished block. A cut moves its closing letter to the front; the recursion then begins the next block."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("foata-step"),
                DeclarationHandle.Create(Prefix + "foataStep"), H("foataStep"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("If the previous last letter is at most the new letter, cuts follow letters at most the new letter. Otherwise cuts follow greater letters. Each block is rotated and the new letter is appended."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("foata"),
                DeclarationHandle.Create(Prefix + "foata"), H("foata"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Folding the insertion step from the empty word defines the transformation."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("park-step-of-not-mem"),
                DeclarationHandle.Create(Prefix + "parkStep_of_not_mem"), H("parkStep_of_not_mem"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("O"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Esc, F.Sp, F.Forall, F.Sp, F.Id("p"), F.InMacro, F.Sp, F.Mathbb,
                    F.Grp(F.Id("N")), F.Comma, F.Quad, F.Sp, F.Neg, F.Sp, F.Open, F.Id("p"), F.InMacro, F.Sp, F.Id("O"), F.Close,
                    F.Rightarrow, F.Sp, F.Operatorname, F.Grp(F.Id("parkStep")), F.Open, F.Id("O"), F.Comma, F.Id("p"),
                    F.Close, F.Eq, F.Id("p")))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every occupied list and preference absent from that list, the chosen spot equals the preference."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("le-park-step"),
                DeclarationHandle.Create(Prefix + "le_parkStep"), H("le_parkStep"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("O"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Esc, F.Sp, F.Forall, F.Sp, F.Id("p"), F.InMacro, F.Sp, F.Mathbb,
                    F.Grp(F.Id("N")), F.Comma, F.Quad, F.Sp, F.Id("p"), F.Le, F.Sp, F.Operatorname, F.Grp(F.Id("parkStep")), F.Open,
                    F.Id("O"), F.Comma, F.Id("p"), F.Close))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every occupied list and preference, the chosen spot is at least the preference."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("park-step-spec"),
                DeclarationHandle.Create(Prefix + "parkStep_spec"), H("parkStep_spec"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("O"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Esc, F.Sp, F.Forall, F.Sp, F.Id("p"), F.InMacro, F.Sp, F.Mathbb,
                    F.Grp(F.Id("N")), F.Comma, F.Quad, F.Sp, F.Neg, F.Sp, F.Open, F.Operatorname, F.Grp(F.Id("parkStep")), F.Open,
                    F.Id("O"), F.Comma, F.Id("p"), F.Close, F.InMacro, F.Sp, F.Id("O"), F.Close, F.Land, F.Sp, F.Open, F.Forall, F.Sp,
                    F.Id("q"), F.InMacro, F.Sp, F.Mathbb, F.Grp(F.Id("N")), F.Comma, F.Esc, F.Sp, F.Id("p"), F.Le, F.Sp, F.Id("q"),
                    F.Rightarrow, F.Sp, F.Id("q"), F.Lt, F.Operatorname, F.Grp(F.Id("parkStep")), F.Open, F.Id("O"), F.Comma,
                    F.Id("p"), F.Close, F.Rightarrow, F.Sp, F.Id("q"), F.InMacro, F.Sp, F.Id("O"), F.Close))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every occupied list and preference, the chosen spot is absent from the occupied list. Every spot at least the preference and strictly below the chosen spot belongs to the occupied list."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("park-step-le-add-one-iff"),
                DeclarationHandle.Create(Prefix + "parkStep_le_add_one_iff"), H("parkStep_le_add_one_iff"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("O"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Esc, F.Sp, F.Forall, F.Sp, F.Id("p"), F.InMacro, F.Sp, F.Mathbb,
                    F.Grp(F.Id("N")), F.Comma, F.Quad, F.Sp, F.Operatorname, F.Grp(F.Id("parkStep")), F.Open, F.Id("O"),
                    F.Comma, F.Id("p"), F.Close, F.Le, F.Sp, F.Id("p"), F.Plus, F.D(1), F.Iff, F.Sp, F.Neg, F.Sp, F.Open, F.Id("p"),
                    F.InMacro, F.Sp, F.Id("O"), F.Close, F.Lor, F.Sp, F.Neg, F.Sp, F.Open, F.Id("p"), F.Plus, F.D(1), F.InMacro, F.Sp, F.Id("O"),
                    F.Close))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every occupied list and preference, displacement is at most one if and only if the preference or its successor is absent from the occupied list."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("spots-length"),
                DeclarationHandle.Create(Prefix + "spots_length"), H("spots_length"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("a"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Quad, F.Sp, F.Bar, F.Operatorname, F.Grp(F.Id("spots")), F.Open,
                    F.Id("a"), F.Close, F.Bar, F.Eq, F.Bar, F.Id("a"), F.Bar))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every preference word, its spot word has the same length."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("foata-perm"),
                DeclarationHandle.Create(Prefix + "foata_perm"), H("foata_perm"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("a"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Quad, F.Sp, F.Operatorname, F.Grp(F.Id("Perm")), F.Open,
                    F.Operatorname, F.Grp(F.Id("foata")), F.Open, F.Id("a"), F.Close, F.Comma, F.Id("a"), F.Close))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every word, its transformed word is a permutation of the original word."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("foata-append-singleton"),
                DeclarationHandle.Create(Prefix + "foata_append_singleton"), H("foata_append_singleton"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("a"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Quad, F.Sp, F.Forall, F.Sp, F.Id("x"), F.InMacro, F.Sp, F.Mathbb,
                    F.Grp(F.Id("N")), F.Comma, F.Quad, F.Sp, F.Operatorname, F.Grp(F.Id("foata")), F.Open, F.Id("a"), F.Plus,
                    F.Plus, F.OpenBracket, F.Id("x"), F.CloseBracket, F.Close, F.Eq, F.Operatorname,
                    F.Grp(F.Id("foataStep")), F.Open, F.Operatorname, F.Grp(F.Id("foata")), F.Open, F.Id("a"), F.Close,
                    F.Comma, F.Id("x"), F.Close))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every word and new letter, transforming their concatenation equals inserting the new letter into the transformed word."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("spots-eq-of-nodup"),
                DeclarationHandle.Create(Prefix + "spots_eq_of_nodup"), H("spots_eq_of_nodup"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("a"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Quad, F.Sp, F.Operatorname, F.Grp(F.Id("Nodup")), F.Open, F.Id("a"),
                    F.Close, F.Rightarrow, F.Sp, F.Operatorname, F.Grp(F.Id("spots")), F.Open, F.Id("a"), F.Close, F.Eq,
                    F.Id("a")))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every word with no duplicate letters, the spot word equals the preference word."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("spot-foata-comm"),
                DeclarationHandle.Create(Prefix + "spot_foata_comm"), H("spot_foata_comm"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("a"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Quad, F.Sp, F.Operatorname, F.Grp(F.Id("Nodup")), F.Open, F.Id("a"),
                    F.Close, F.Rightarrow, F.Sp, F.Operatorname, F.Grp(F.Id("spots")), F.Open, F.Operatorname,
                    F.Grp(F.Id("foata")), F.Open, F.Id("a"), F.Close, F.Close, F.Eq, F.Operatorname,
                    F.Grp(F.Id("foata")), F.Open, F.Operatorname, F.Grp(F.Id("spots")), F.Open, F.Id("a"), F.Close,
                    F.Close))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every word with no duplicate letters, parking after transformation equals transformation after parking. This theorem requires distinct letters."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("park-step-mono"),
                DeclarationHandle.Create(Prefix + "parkStep_mono"), H("parkStep_mono"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("O"), F.Comma, F.Id("Oprime"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open,
                    F.Mathbb, F.Grp(F.Id("N")), F.Close, F.Comma, F.Esc, F.Sp, F.Forall, F.Sp, F.Id("p"), F.Comma, F.Id("r"),
                    F.InMacro, F.Sp, F.Mathbb, F.Grp(F.Id("N")), F.Comma, F.Quad, F.Sp, F.Id("O"), F.Subseteq, F.Sp, F.Id("Oprime"),
                    F.Rightarrow, F.Sp, F.Id("p"), F.Le, F.Sp, F.Id("r"), F.Rightarrow, F.Sp, F.Operatorname, F.Grp(F.Id("parkStep")),
                    F.Open, F.Id("O"), F.Comma, F.Id("p"), F.Close, F.Le, F.Sp, F.Operatorname, F.Grp(F.Id("parkStep")),
                    F.Open, F.Id("Oprime"), F.Comma, F.Id("r"), F.Close))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For occupied lists with the first contained in the second and preferences with the first at most the second, the first selected spot is at most the second selected spot."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("spots-pairwise"),
                DeclarationHandle.Create(Prefix + "spots_pairwise"), H("spots_pairwise"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("a"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Quad, F.Sp, F.Operatorname, F.Grp(F.Id("Pairwise")), F.Underscore,
                    F.Grp(F.Le), F.Open, F.Id("a"), F.Close, F.Rightarrow, F.Sp, F.Operatorname, F.Grp(F.Id("Pairwise")),
                    F.Underscore, F.Grp(F.Le), F.Open, F.Operatorname, F.Grp(F.Id("spots")), F.Open, F.Id("a"), F.Close,
                    F.Close))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every nondecreasing preference word, its spot word is nondecreasing."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("foata-eq-of-pairwise"),
                DeclarationHandle.Create(Prefix + "foata_eq_of_pairwise"), H("foata_eq_of_pairwise"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("a"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Quad, F.Sp, F.Operatorname, F.Grp(F.Id("Pairwise")), F.Underscore,
                    F.Grp(F.Le), F.Open, F.Id("a"), F.Close, F.Rightarrow, F.Sp, F.Operatorname, F.Grp(F.Id("foata")), F.Open,
                    F.Id("a"), F.Close, F.Eq, F.Id("a")))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every nondecreasing word, its Foata transformation equals the word itself."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("spot-foata-comm-of-pairwise"),
                DeclarationHandle.Create(Prefix + "spot_foata_comm_of_pairwise"), H("spot_foata_comm_of_pairwise"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("a"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Quad, F.Sp, F.Operatorname, F.Grp(F.Id("Pairwise")), F.Underscore,
                    F.Grp(F.Le), F.Open, F.Id("a"), F.Close, F.Rightarrow, F.Sp, F.Operatorname, F.Grp(F.Id("spots")), F.Open,
                    F.Operatorname, F.Grp(F.Id("foata")), F.Open, F.Id("a"), F.Close, F.Close, F.Eq, F.Operatorname,
                    F.Grp(F.Id("foata")), F.Open, F.Operatorname, F.Grp(F.Id("spots")), F.Open, F.Id("a"), F.Close,
                    F.Close))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every nondecreasing word, parking after transformation equals transformation after parking. Repeated letters are permitted."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("unit-run"),
                DeclarationHandle.Create(Prefix + "unitRun"), H("unitRun"),
                StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The recursive unit-interval condition requires each preference to belong to the finite street, each chosen spot to stay within its upper bound, and each displacement to be at most one. It recurses over the remaining cars."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("is-unit-interval-iff-unit-run"),
                DeclarationHandle.Create(Prefix + "isUnitInterval_iff_unitRun"), H("isUnitInterval_iff_unitRun"),
                StatementSource.FromAuthor(F.Disp(F.Seq(
                    F.Forall, F.Sp, F.Id("a"), F.InMacro, F.Sp, F.Operatorname, F.Grp(F.Id("List")), F.Open, F.Mathbb,
                    F.Grp(F.Id("N")), F.Close, F.Comma, F.Quad, F.Sp, F.Operatorname, F.Grp(F.Id("IsUnitInterval")), F.Open,
                    F.Id("a"), F.Close, F.Iff, F.Sp, F.Operatorname, F.Grp(F.Id("unitRun")), F.Open, F.Bar, F.Id("a"), F.Bar,
                    F.Comma, F.OpenBracket, F.CloseBracket, F.Comma, F.Id("a"), F.Close, F.Eq, F.Operatorname,
                    F.Grp(F.Id("true"))))), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For every preference word, being a unit-interval parking function is equivalent to the recursive unit-interval condition evaluating to true from an empty street whose size is the word length."))), DescribeRole.Theorem)),
        []));
}
