using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.VertexAlgebra;

internal sealed class LatticePositivePairingDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Positive Hermitian pairing and actual current adjoints",
        H("Positive Hermitian pairing and actual current adjoints"),
        Blocks(
            Paragraph(Text("Let D be the ordinary LatticeData with arbitrary natural rank, integral symmetric Gram matrix G and even diagonal. Rank zero is included. The carrier consists of finite charge-supported oscillator polynomials over Complex. The pairing is conjugate-linear in the first argument and linear in the second.")),
            Paragraph(Text("The only additional geometric hypothesis is Matrix.PosDef(realGram D). A real spectral factor R satisfies transpose(R)*R=G. Substitution by R is injective on the original oscillator polynomial ring; it changes the form while retaining the original charges, cocycle, fields and current operators. No positive-rank, determinant-unit, unimodularity, chosen-factor or desired-adjoint premise is assumed.")),
            Paragraph(Text("The finite coefficient form weights a monomial exponent e by the product of (r+1)^e(i,r) e(i,r)! over its support. Pullback along R defines oscillatorPair. Orthogonal summation over charge sectors defines latticePair. Every nonzero actual finite state has strictly positive real self-pairing and zero imaginary self-pairing. The actual vacuum has norm one.")),
            Paragraph(Text("The factorial successor identity gives the creation and partial-derivative adjoint relation. Differentiating the real matrix substitution and contracting transpose(R)*R recovers the original Gram-weighted derivative, including off-diagonal coefficients. For every integer n and actual states u,v, latticePair(a_i(n)u,v)=latticePair(u,a_i(-n)v). At n=0 the charge scalar is real.")),
            Paragraph(Text("AdjPair is an algebraic relation between two actual linear endomorphisms on the finite carrier. It asserts no globally defined operator star, analytic boundedness or Hilbert-space domain theorem. Ordinary field mode [[n]] has Laurent power -n-1.")),
            Paragraph(Text("Dong and Lin, Unitary vertex operator algebras, arXiv:1308.2361v1, Definition 2.2 and Theorem 4.12 give the ordinary lattice Hermitian context; their argument convention is reversed here. Carpi, Kawahigashi, Longo and Weiner, From vertex operator algebras to conformal nets and back, arXiv:1503.01260v4, section 5.1 gives the second-linear convention. These references supply context; the finite coefficient construction and original-basis proofs here are repo-derived. Matrix spectral results use mathlib under Apache 2.0.")),
            Paragraph(Text("The subsequent mathematical questions concern labelled Wick contractions, charged and Sugawara adjoints, explicit L1 descent and local nilpotence, and concrete antilinear PCT covariance. The full all-state opposite-adjoint invariant requires finite opposite iterate and residue identities with distinguished expansions and proven coefficient supports. No complete unitary VOA, conformal net, twisted sector, Monster, fusion, anomaly, CFT, string theory or AdS/CFT bridge is asserted.")),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-realgram"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.realGram"),
                H("realGram"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-rootfactor"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.rootFactor"),
                H("rootFactor"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-rootfactor-gram"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.rootFactor_gram"),
                H("rootFactor gram"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-rootfactor-isunit"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.rootFactor_isUnit"),
                H("rootFactor isUnit"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-gramsubstitution"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.gramSubstitution"),
                H("gramSubstitution"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-gramsubstitution-c"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.gramSubstitution_C"),
                H("gramSubstitution C"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-gramsubstitution-x"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.gramSubstitution_X"),
                H("gramSubstitution X"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-gramsubstitution-smul"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.gramSubstitution_smul"),
                H("gramSubstitution smul"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-gramsubstitution-one"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.gramSubstitution_one"),
                H("gramSubstitution one"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-gramsubstitution-comp"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.gramSubstitution_comp"),
                H("gramSubstitution comp"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-gramsubstitution-injective"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.gramSubstitution_injective"),
                H("gramSubstitution injective"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-focktransform"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.fockTransform"),
                H("fockTransform"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-focktransform-injective"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.fockTransform_injective"),
                H("fockTransform injective"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-factorialweight"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.factorialWeight"),
                H("factorialWeight"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-factorialweight-pos"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.factorialWeight_pos"),
                H("factorialWeight pos"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-factorialweight-zero"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.factorialWeight_zero"),
                H("factorialWeight zero"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair"),
                H("standardPair"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-sum"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_sum"),
                H("standardPair sum"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-zero-left"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_zero_left"),
                H("standardPair zero left"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-zero-right"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_zero_right"),
                H("standardPair zero right"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-add-left"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_add_left"),
                H("standardPair add left"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-add-right"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_add_right"),
                H("standardPair add right"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-smul-right"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_smul_right"),
                H("standardPair smul right"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-smul-left"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_smul_left"),
                H("standardPair smul left"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-on-finset"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_on_finset"),
                H("standardPair on finset"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-hermitian"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_hermitian"),
                H("standardPair hermitian"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-self-re"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_self_re"),
                H("standardPair self re"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-self-nonneg"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_self_nonneg"),
                H("standardPair self nonneg"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-self-pos"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_self_pos"),
                H("standardPair self pos"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-monomial-left"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_monomial_left"),
                H("standardPair monomial left"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-one"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_one"),
                H("standardPair one"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-factorialweight-successor"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.factorialWeight_successor"),
                H("factorialWeight successor"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-standardpair-x-mul"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.standardPair_X_mul"),
                H("standardPair X mul"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair"),
                H("oscillatorPair"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-zero-left"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_zero_left"),
                H("oscillatorPair zero left"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-zero-right"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_zero_right"),
                H("oscillatorPair zero right"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-add-left"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_add_left"),
                H("oscillatorPair add left"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-add-right"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_add_right"),
                H("oscillatorPair add right"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-smul-left"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_smul_left"),
                H("oscillatorPair smul left"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-smul-right"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_smul_right"),
                H("oscillatorPair smul right"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-hermitian"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_hermitian"),
                H("oscillatorPair hermitian"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-self-nonneg"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_self_nonneg"),
                H("oscillatorPair self nonneg"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-self-pos"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_self_pos"),
                H("oscillatorPair self pos"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-one"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_one"),
                H("oscillatorPair one"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair"),
                H("latticePair"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-zero-left"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_zero_left"),
                H("latticePair zero left"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-zero-right"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_zero_right"),
                H("latticePair zero right"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-add-left"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_add_left"),
                H("latticePair add left"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-add-right"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_add_right"),
                H("latticePair add right"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-on-finset"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_on_finset"),
                H("latticePair on finset"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-hermitian"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_hermitian"),
                H("latticePair hermitian"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-self-im"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_self_im"),
                H("latticePair self im"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-self-pos"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_self_pos"),
                H("latticePair self pos"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-single-left"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_single_left"),
                H("latticePair single left"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-single-single"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_single_single"),
                H("latticePair single single"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-latticepair-vacuum"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.latticePair_vacuum"),
                H("latticePair vacuum"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-adjpair"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.AdjPair"),
                H("AdjPair"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Definition),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-gramsubstitution-pderiv"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.gramSubstitution_pderiv"),
                H("gramSubstitution pderiv"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-root-contraction"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.root_contraction"),
                H("root contraction"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-focktransform-weightedpartial"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.fockTransform_weightedPartial"),
                H("fockTransform weightedPartial"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-x-mul"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_X_mul"),
                H("oscillatorPair X mul"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-oscillatorpair-current"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.oscillatorPair_current"),
                H("oscillatorPair current"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("latticepositivepairing-actual-current-adjoint"),
                DeclarationHandle.Create("D5/S3/VertexAlgebra/LatticePositivePairing.actual_current_adjoint"),
                H("actual current adjoint"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(),
                DescribeRole.Theorem)))));
}
