import LeanInformationAuditInterface.Contract.Catalog

namespace Reg.Catalogs.MapInjectiveRegistrations.SealedCatalog
open LeanInformationAudit

noncomputable def state_0 : Fin (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) (nat_lit 0)
    (@Nat.le_of_lt (nat_lit 1) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
      (@Nat.le_of_lt (nat_lit 2) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
        (@Nat.le_of_lt (nat_lit 3) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
          (@Nat.le_of_lt (nat_lit 4) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
            (@Nat.le_of_lt (nat_lit 5) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
              (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                  (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                    (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                      (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                        (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                          (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))))))))))))))

noncomputable def state_1 : Fin (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) (nat_lit 1)
    (@Nat.le_of_lt (nat_lit 2) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
      (@Nat.le_of_lt (nat_lit 3) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
        (@Nat.le_of_lt (nat_lit 4) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
          (@Nat.le_of_lt (nat_lit 5) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
            (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
              (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                  (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                    (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                      (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                        (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))))))))))))))

noncomputable def state_2 : Fin (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) (nat_lit 2)
    (@Nat.le_of_lt (nat_lit 3) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
      (@Nat.le_of_lt (nat_lit 4) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
        (@Nat.le_of_lt (nat_lit 5) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
          (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
            (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
              (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                  (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                    (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                      (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))))))))))))

noncomputable def state_3 : Fin (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) (nat_lit 3)
    (@Nat.le_of_lt (nat_lit 4) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
      (@Nat.le_of_lt (nat_lit 5) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
        (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
          (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
            (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
              (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                  (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                    (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))))))))))))

noncomputable def state_4 : Fin (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) (nat_lit 4)
    (@Nat.le_of_lt (nat_lit 5) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
      (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
        (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
          (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
            (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
              (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                  (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))))))))))

noncomputable def state_5 : Fin (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) (nat_lit 5)
    (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
      (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
        (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
          (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
            (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
              (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
                (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))))))))))

noncomputable def state_6 : Fin (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) (nat_lit 6)
    (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
      (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
        (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
          (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
            (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
              (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))))))))

noncomputable def state_7 : Fin (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) (nat_lit 7)
    (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
      (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
        (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
          (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
            (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))))))))

noncomputable def state_8 : Fin (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) (nat_lit 8)
    (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
      (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
        (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
          (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))))))

noncomputable def state_9 : Fin (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))) (nat_lit 9)
    (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
      (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12)))
        (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 12) (instOfNatNat (nat_lit 12))))))

noncomputable def state_10 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 0)
    (@Nat.le_of_lt (nat_lit 1) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 2) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 3) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 4) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 5) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                    (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                      (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                        (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                          (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                            (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                              (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                                (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                                  (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                                    (@Nat.le_of_lt (nat_lit 17)
                                      (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                                      (Nat.le_refl
                                        (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))))))))))))))))))))

noncomputable def state_11 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 1)
    (@Nat.le_of_lt (nat_lit 2) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 3) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 4) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 5) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                    (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                      (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                        (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                          (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                            (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                              (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                                (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                                  (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                                    (Nat.le_refl
                                      (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))))))))))))))))))))

noncomputable def state_12 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 2)
    (@Nat.le_of_lt (nat_lit 3) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 4) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 5) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                    (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                      (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                        (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                          (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                            (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                              (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                                (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                                  (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))))))))))))))))))

noncomputable def state_13 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 3)
    (@Nat.le_of_lt (nat_lit 4) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 5) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                    (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                      (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                        (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                          (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                            (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                              (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                                (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))))))))))))))))))

noncomputable def state_14 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 4)
    (@Nat.le_of_lt (nat_lit 5) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                    (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                      (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                        (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                          (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                            (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                              (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))))))))))))))))

noncomputable def state_15 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 5)
    (@Nat.le_of_lt (nat_lit 6) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                    (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                      (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                        (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                          (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                            (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))))))))))))))))

noncomputable def state_16 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 6)
    (@Nat.le_of_lt (nat_lit 7) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                    (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                      (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                        (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                          (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))))))))))))))

noncomputable def state_17 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 7)
    (@Nat.le_of_lt (nat_lit 8) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                    (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                      (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                        (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))))))))))))))

noncomputable def state_18 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 8)
    (@Nat.le_of_lt (nat_lit 9) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                    (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                      (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))))))))))))

noncomputable def state_19 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 9)
    (@Nat.le_of_lt (nat_lit 10) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                    (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))))))))))))

noncomputable def state_20 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 10)
    (@Nat.le_of_lt (nat_lit 11) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                  (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))))))))))

noncomputable def state_21 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 11)
    (@Nat.le_of_lt (nat_lit 12) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
                (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))))))))))

noncomputable def state_22 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 12)
    (@Nat.le_of_lt (nat_lit 13) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
              (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))))))))

noncomputable def state_23 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 13)
    (@Nat.le_of_lt (nat_lit 14) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
            (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))))))))

noncomputable def state_24 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 14)
    (@Nat.le_of_lt (nat_lit 15) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
          (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))))))

noncomputable def state_25 : Fin (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) :=
  @Fin.mk (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))) (nat_lit 15)
    (@Nat.le_of_lt (nat_lit 16) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
      (@Nat.le_of_lt (nat_lit 17) (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18)))
        (Nat.le_refl (@OfNat.ofNat Nat (nat_lit 18) (instOfNatNat (nat_lit 18))))))

end Reg.Catalogs.MapInjectiveRegistrations.SealedCatalog
