using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.ConceptDynamics.PartialIdentification;

internal sealed class FiniteMomentSupportReductionDocument : IScribeDocumentDefinition
{
    private const string Prefix =
        "D5/S3/ConceptDynamics/PartialIdentification/FiniteMomentSupportReduction.";

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Finite rational causal laws can be compressed relative to the linear information actually retained. The global joint feature profile exposes indistinguishable states and affine redundancy, while Caratheodory supplies a positive law-specific latent witness controlled by profile rank rather than the full response-table cardinality.",
        H("Finite moment support reduction for causal response laws"),
        Blocks(
            Describe.Lean(DescribeId.Create("law-moment-vector"), DeclarationHandle.Create(Prefix + "lawMomentVector"), H("Retained moment vector"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Collect a finite family of rational atom features into their expectation vector under one normalized response law."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("profile-affine-rank"), DeclarationHandle.Create(Prefix + "profileAffineRank"), H("Affine rank of joint atom profiles"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Measure the affine dimension of the range of the retained feature map. Duplicate profiles and affine dependencies do not increase this rank."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("law-moment-vector-convex-hull"), DeclarationHandle.Create(Prefix + "lawMomentVector_mem_convexHull"), H("Moments lie in the atom-profile convex hull"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Normalization and nonnegativity express the retained moment vector as a convex combination of original atom profiles."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("moment-compression"), DeclarationHandle.Create(Prefix + "MomentCompression"), H("Positive sparse moment witness"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A compression stores original feature profiles, positive normalized weights, exact moment equality, affine independence, and a finite cardinality bound."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("exists-moment-compression"), DeclarationHandle.Create(Prefix + "exists_momentCompression"), H("Every finite law has a small exact moment witness"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Mathlib Caratheodory reduction selects an affinely independent positive atomic representation of the exact moment vector."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("card-le-profile-affine-rank"), DeclarationHandle.Create(Prefix + "MomentCompression.card_le_profileAffineRank"), H("Profile rank controls sparse support"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The retained atom count is at most one plus the affine rank of the full joint feature-profile family, sharpening the ambient coordinate count when rows are redundant."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("source-atom"), DeclarationHandle.Create(Prefix + "MomentCompression.sourceAtom"), H("Choose an original atom for each profile"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Each retained profile is certified to occur among the original atoms, so one source atom is chosen for every latent profile."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("source-atom-feature"), DeclarationHandle.Create(Prefix + "MomentCompression.sourceAtom_feature"), H("Chosen atoms realize their profiles"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The selected atom evaluates to exactly the feature profile naming its latent state."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("source-atom-injective"), DeclarationHandle.Create(Prefix + "MomentCompression.sourceAtom_injective"), H("Selected atoms are distinct"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Distinct profiles cannot select the same original atom, giving a genuine sparse subset representation."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("latent-law"), DeclarationHandle.Create(Prefix + "MomentCompression.latentLaw"), H("Normalized law on the sparse carrier"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The positive Caratheodory weights form a normalized rational law on the selected profile subtype."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("latent-source-moment-eq"), DeclarationHandle.Create(Prefix + "MomentCompression.latent_source_moment_eq"), H("Sparse source realization preserves the full moment vector"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Evaluating the selected original atoms under the sparse latent law reproduces every retained moment simultaneously."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("coordinate-eq"), DeclarationHandle.Create(Prefix + "MomentCompression.coordinate_eq"), H("Coordinatewise moment preservation"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Each retained scalar feature has exactly the same expectation before and after sparse realization."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("linear-row-query-feature"), DeclarationHandle.Create(Prefix + "linearRowQueryFeature"), H("Join LP rows and one query"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Constraint rows occupy some coordinates of an Option index and the none coordinate stores the objective."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("linear-problem-profile-rank"), DeclarationHandle.Create(Prefix + "linearProblemProfileRank"), H("Constraint-aware LP profile rank"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Take the affine rank of the joint vector consisting of every LP row coefficient and the objective coefficient on each original atom."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("linear-problem-profile-rank-le"), DeclarationHandle.Create(Prefix + "linearProblemProfileRank_le"), H("Profile rank is bounded by the raw row count"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The joint LP profile rank is at most the number of constraint rows plus the one objective coordinate."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("linear-row-query-profile-rank-card-le"), DeclarationHandle.Create(Prefix + "MomentCompression.linearRowQuery_profileRank_card_le"), H("Exact rank-aware LP support bound"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A compressed attaining law uses at most profile rank plus one latent atoms, automatically benefiting from duplicate or affinely redundant constraint profiles."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("linear-row-query-card-le"), DeclarationHandle.Create(Prefix + "MomentCompression.linearRowQuery_card_le"), H("Rows plus query need at most m plus two atoms"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Combining the rank-aware bound with the ambient dimension gives the coarser universal bound of the row count plus two."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("latent-linear-feasible"), DeclarationHandle.Create(Prefix + "MomentCompression.latentLinearFeasible"), H("Feasibility survives sparse realization"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Exact preservation of every row expectation transports the original rational inequality system to the selected latent carrier."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("latent-linear-objective-eq"), DeclarationHandle.Create(Prefix + "MomentCompression.latentLinearObjective_eq"), H("The exact query value survives"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The nominated linear objective has exactly the same value under the sparse latent witness."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-linear-problem-small-latent-witness"), DeclarationHandle.Create(Prefix + "finite_linear_problem_small_latent_witness"), H("Every feasible query point has a small attaining latent model"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Every feasible finite linear causal law admits an attaining positive latent realization with at most the row count plus two states."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("response-table-cell-query-feature"), DeclarationHandle.Create(Prefix + "responseTableCellQueryFeature"), H("All response-cell marginals plus one query"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("For k Boolean response-pair strata, retain all four one-stratum response-cell indicators and one scalar query."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("exists-response-table-cell-query-compression"), DeclarationHandle.Create(Prefix + "exists_responseTableCellQueryCompression"), H("Linear-size witness inside the four-to-the-k table space"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Although the unrestricted response-table carrier has four to the k atoms, all one-stratum four-cell marginals and one query have a positive witness using at most four k plus two atoms."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("response-table-cell-moment-eq"), DeclarationHandle.Create(Prefix + "MomentCompression.responseTableCellMoment_eq"), H("Every one-stratum cell probability is preserved"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Each response-cell indicator has exactly the same expectation under the full table law and the sparse latent table witness."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("response-table-query-moment-eq"), DeclarationHandle.Create(Prefix + "MomentCompression.responseTableQueryMoment_eq"), H("The table query is preserved with the marginals"), StatementSource.FromLean(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The same sparse witness retains the nominated scalar query together with every one-stratum response-cell marginal."))), DescribeRole.Theorem))));
}
