using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;
namespace StrataLint.Scribe.Blueprint.D5.S3.ConceptDynamics.ResidualCoverage;
internal sealed class ResidualSeparationAdapterDocument : IScribeDocumentDefinition
{
 public DocumentDefinition Create()=>DocumentDefinition.Create(ScribeNode.Create("Finite defect snapshots are covered exactly when no chosen-package pair stays blind.",H("Residual Separation Adapter"),Blocks(Describe.Lean(DescribeId.Create("exact-cover-is-no-blind-pair"),DeclarationHandle.Create("D5/S3/ConceptDynamics/ResidualCoverage/ResidualSeparationAdapter.exactCover_iff_no_blind_pair"),H("Exact cover is equivalent to absence of blind residual pairs"),StatementSource.FromAuthor(Formula()),AssessedProvenance.FromRepo(),Blocks(Paragraph(Text("The snapshot lists defectRelation pairs; Boolean separation by the chosen package is translated through the canonical joint kernel.")),Paragraph(Text("The coveredBy bridge gives the exact-cover biconditional pair by pair."))),DescribeRole.Theorem),Describe.Lean(DescribeId.Create("zero-uncovered-weight-is-no-blind-pair"),DeclarationHandle.Create("D5/S3/ConceptDynamics/ResidualCoverage/ResidualSeparationAdapter.uncoveredWeight_zero_iff_no_blind_pair"),H("Positive residual weights make zero uncovered weight equivalent to no blind pair"),StatementSource.FromAuthor(ZeroWeight()),AssessedProvenance.FromRepo(),Blocks(Paragraph(Text("The same defect snapshot is assigned a strictly positive natural weight at every residual pair.")),Paragraph(Text("Consequently, uncoveredWeight is zero exactly when every snapshot pair is covered, hence exactly when no chosen-package pair remains blind."))),DescribeRole.Theorem))));
 private static Formula Snapshot()=>Seq(Forall,Sp,F.Id("pair"),Sp,InMacro,Sp,F.Id("residuals"),Comma,Sp,F.Id("pair"),Sp,InMacro,Sp,Call("defectRelation",F.Id("q"),F.Id("target")));
 private static Formula Positive()=>Seq(Forall,Sp,F.Id("pair"),Sp,InMacro,Sp,F.Id("residuals"),Comma,Sp,F.Id("zero"),Sp,Lt,Sp,Call("weight",F.Id("pair")));
 private static Formula NoBlind()=>Seq(Forall,Sp,F.Id("pair"),Sp,InMacro,Sp,F.Id("residuals"),Comma,Sp,Neg,Sp,Call("InBlindResidual",F.Id("pair"),F.Id("chosen"),F.Id("q"),F.Id("target")));
 private static Formula Formula()=>Disp(Seq(OpenBracket,Call("DecidableEq",F.Id("Output")),CloseBracket,Sp,OpenBracket,Call("DecidableEq",Call("Concept",F.Id("X"),F.Id("Output"))),CloseBracket,Sp,Snapshot(),Sp,Rightarrow,Sp,Open,Call("ExactCover",F.Id("residuals"),F.Id("separatesPair"),F.Id("chosen")),Sp,Iff,Sp,NoBlind(),Close,Dot));
 private static Formula ZeroWeight()=>Disp(Seq(OpenBracket,Call("DecidableEq",F.Id("Output")),CloseBracket,Sp,OpenBracket,Call("DecidableEq",Call("Concept",F.Id("X"),F.Id("Output"))),CloseBracket,Sp,Snapshot(),Sp,Land,Sp,Positive(),Sp,Rightarrow,Sp,Open,Call("UncoveredWeight",F.Id("residuals"),F.Id("weight"),F.Id("separatesPair"),F.Id("chosen")),Sp,Eq,Sp,F.Id("zero"),Sp,Iff,Sp,NoBlind(),Close,Dot));
}
