using StrataLint.Engine;

namespace StrataLint.ArchitectureTests;

public sealed class EnginePublicSurfaceTests
{
    private static readonly string[] ExpectedPublicTypes =
    [
        "StrataLint.Engine.AcceptedLeanClosure",
        "StrataLint.Engine.AdmissionCertificate",
        "StrataLint.Engine.AdmissionEffect",
        "StrataLint.Engine.AdmissionOutcome",
        "StrataLint.Engine.AdmissionOutcome+Admitted",
        "StrataLint.Engine.AdmissionOutcome+InfrastructureFailure",
        "StrataLint.Engine.AdmissionOutcome+ProtectedSurfaceChange",
        "StrataLint.Engine.AdmissionOutcome+ProtectedSurfaceVerificationRequired",
        "StrataLint.Engine.AdmissionOutcome+RuleRejected",
        "StrataLint.Engine.AdmissionOutcome0MatchExtensions",
        "StrataLint.Engine.AdmissionPipeline",
        "StrataLint.Engine.Anchor",
        "StrataLint.Engine.AnchorParseResult",
        "StrataLint.Engine.AnchorParseResult+Invalid",
        "StrataLint.Engine.AnchorParseResult+Parsed",
        "StrataLint.Engine.AnchorScheme",
        "StrataLint.Engine.ArtifactClass",
        "StrataLint.Engine.ArtifactCoverage",
        "StrataLint.Engine.ArtifactKindId",
        "StrataLint.Engine.ArtifactKindSyntax",
        "StrataLint.Engine.ArtifactPolicy",
        "StrataLint.Engine.BibKey",
        "StrataLint.Engine.BootstrapGate",
        "StrataLint.Engine.BootstrapOutcome",
        "StrataLint.Engine.BootstrapOutcome+Clear",
        "StrataLint.Engine.BootstrapOutcome+InfrastructureFailure",
        "StrataLint.Engine.BootstrapOutcome+ProtectedSurfaceVerificationRequired",
        "StrataLint.Engine.BootstrapOutcome0MatchExtensions",
        "StrataLint.Engine.CanonicalFixedPoint",
        "StrataLint.Engine.CanonicalizationOutcome",
        "StrataLint.Engine.CanonicalizationOutcome+Accepted",
        "StrataLint.Engine.CanonicalizationOutcome+InfrastructureFailure",
        "StrataLint.Engine.CanonicalizationOutcome0MatchExtensions",
        "StrataLint.Engine.CaseId",
        "StrataLint.Engine.CompletedRuleSet",
        "StrataLint.Engine.CoverageAnalyzer",
        "StrataLint.Engine.CoverageCanonicalWriter",
        "StrataLint.Engine.CoverageLedgerIndex",
        "StrataLint.Engine.CoverageLedgerState",
        "StrataLint.Engine.CoverageMatrixRow",
        "StrataLint.Engine.CoverageMechanisms",
        "StrataLint.Engine.CoverageReport",
        "StrataLint.Engine.DagLedgerFileEvent",
        "StrataLint.Engine.DagLedgerFilesLoadOutcome",
        "StrataLint.Engine.DagLedgerFilesLoadOutcome+Invalid",
        "StrataLint.Engine.DagLedgerFilesLoadOutcome+Loaded",
        "StrataLint.Engine.DeferredRule",
        "StrataLint.Engine.Diagnostic",
        "StrataLint.Engine.DisplaySeverity",
        "StrataLint.Engine.Doi",
        "StrataLint.Engine.DomainId",
        "StrataLint.Engine.DomainSyntax",
        "StrataLint.Engine.FrozenAcceptedEventLoader",
        "StrataLint.Engine.FrozenContentAddress",
        "StrataLint.Engine.FrozenCoverageLedger",
        "StrataLint.Engine.FrozenCoverageLoadOutcome",
        "StrataLint.Engine.FrozenCoverageLoadOutcome+Invalid",
        "StrataLint.Engine.FrozenCoverageLoadOutcome+Loaded",
        "StrataLint.Engine.FrozenCoverageLoadOutcome0MatchExtensions",
        "StrataLint.Engine.FrozenDeclarationStatement",
        "StrataLint.Engine.FrozenFreezePayload",
        "StrataLint.Engine.FrozenLedger",
        "StrataLint.Engine.FrozenLedgerChangeClassifier",
        "StrataLint.Engine.FrozenLedgerConsistent",
        "StrataLint.Engine.FrozenLedgerValidationOutcome",
        "StrataLint.Engine.FrozenLedgerValidationOutcome+Accepted",
        "StrataLint.Engine.FrozenLedgerValidationOutcome+Rejected",
        "StrataLint.Engine.FrozenLedgerValidationOutcome0MatchExtensions",
        "StrataLint.Engine.FrozenMaterialCatalog",
        "StrataLint.Engine.FrozenMaterialOutcome",
        "StrataLint.Engine.FrozenMaterialOutcome+Accepted",
        "StrataLint.Engine.FrozenMaterialOutcome+Rejected",
        "StrataLint.Engine.FrozenMaterialOutcome0MatchExtensions",
        "StrataLint.Engine.FrozenNodeId",
        "StrataLint.Engine.FrozenNodeMaterial",
        "StrataLint.Engine.Generality",
        "StrataLint.Engine.Gid",
        "StrataLint.Engine.LakeModuleAnchor",
        "StrataLint.Engine.LeanAxiomFacts",
        "StrataLint.Engine.LeanAxiomReport",
        "StrataLint.Engine.LeanClosureValidator",
        "StrataLint.Engine.LeanCompiledArtifactReports",
        "StrataLint.Engine.LeanDeclaration",
        "StrataLint.Engine.LeanFileReport",
        "StrataLint.Engine.LeanQualifiedName",
        "StrataLint.Engine.LeanTruthStates",
        "StrataLint.Engine.LeanValidationOutcome",
        "StrataLint.Engine.LeanValidationOutcome+Accepted",
        "StrataLint.Engine.LeanValidationOutcome+InfrastructureFailure",
        "StrataLint.Engine.LeanValidationOutcome0MatchExtensions",
        "StrataLint.Engine.LiteratureAnchor",
        "StrataLint.Engine.ManifestLoadOutcome",
        "StrataLint.Engine.ManifestLoadOutcome+InfrastructureFailure",
        "StrataLint.Engine.ManifestLoadOutcome+Loaded",
        "StrataLint.Engine.ManifestLoadOutcome0MatchExtensions",
        "StrataLint.Engine.ManifestLoader",
        "StrataLint.Engine.ManifestSyntax",
        "StrataLint.Engine.MathlibAnchor",
        "StrataLint.Engine.MathlibTargetKind",
        "StrataLint.Engine.MetaChangeSet",
        "StrataLint.Engine.MetaClear",
        "StrataLint.Engine.Plane",
        "StrataLint.Engine.RawChange",
        "StrataLint.Engine.RawChangeKind",
        "StrataLint.Engine.RawChangeSet",
        "StrataLint.Engine.RawRepositoryEntry",
        "StrataLint.Engine.RawRepositorySnapshot",
        "StrataLint.Engine.RegistryLoadOutcome",
        "StrataLint.Engine.RegistryLoadOutcome+Accepted",
        "StrataLint.Engine.RegistryLoadOutcome+InfrastructureFailure",
        "StrataLint.Engine.RegistryLoadOutcome0MatchExtensions",
        "StrataLint.Engine.RegistryLoader",
        "StrataLint.Engine.RegistryPolicyCompiler",
        "StrataLint.Engine.RegistrySyntax",
        "StrataLint.Engine.RepoPath",
        "StrataLint.Engine.RepositoryCanonicalizer",
        "StrataLint.Engine.RepositoryFile",
        "StrataLint.Engine.RepositorySnapshot",
        "StrataLint.Engine.RevocationEvidence",
        "StrataLint.Engine.RevocationEvidence+AllowedAxiomRetired",
        "StrataLint.Engine.RevocationEvidence+ContentAddressMismatch",
        "StrataLint.Engine.RevocationEvidence+FormalContradictionCertificate",
        "StrataLint.Engine.RevocationEvidence+KernelWitnessFailure",
        "StrataLint.Engine.RevocationEvidence0MatchExtensions",
        "StrataLint.Engine.RevocationEvidenceValidationOutcome",
        "StrataLint.Engine.RevocationEvidenceValidationOutcome+Accepted",
        "StrataLint.Engine.RevocationEvidenceValidationOutcome+Rejected",
        "StrataLint.Engine.RevocationEvidenceValidationOutcome0MatchExtensions",
        "StrataLint.Engine.RevocationEvidenceValidator",
        "StrataLint.Engine.RevocationPlan",
        "StrataLint.Engine.RevocationPlanOutcome",
        "StrataLint.Engine.RevocationPlanOutcome+Accepted",
        "StrataLint.Engine.RevocationPlanOutcome+Rejected",
        "StrataLint.Engine.RevocationPlanOutcome0MatchExtensions",
        "StrataLint.Engine.RevocationPlanner",
        "StrataLint.Engine.RevocationReceiptStoreOutcome",
        "StrataLint.Engine.RevocationReceiptStoreOutcome+Accepted",
        "StrataLint.Engine.RevocationReceiptStoreOutcome+Rejected",
        "StrataLint.Engine.RevocationReceiptStoreOutcome0MatchExtensions",
        "StrataLint.Engine.RevocationReceiptWriter",
        "StrataLint.Engine.RouteEngine",
        "StrataLint.Engine.RouteOutcome",
        "StrataLint.Engine.RouteOutcome+Rejected",
        "StrataLint.Engine.RouteOutcome+Routed",
        "StrataLint.Engine.RouteOutcome0MatchExtensions",
        "StrataLint.Engine.RouteResult",
        "StrataLint.Engine.RuleCatalog",
        "StrataLint.Engine.RuleDescriptor",
        "StrataLint.Engine.RuleExecutionOutcome",
        "StrataLint.Engine.RuleExecutionOutcome+Completed",
        "StrataLint.Engine.RuleExecutionOutcome+InfrastructureFailure",
        "StrataLint.Engine.RuleExecutionOutcome0MatchExtensions",
        "StrataLint.Engine.RuleId",
        "StrataLint.Engine.RuleLifecycle",
        "StrataLint.Engine.SnapshotDecodeOutcome",
        "StrataLint.Engine.SnapshotDecodeOutcome+Decoded",
        "StrataLint.Engine.SnapshotDecodeOutcome+InfrastructureFailure",
        "StrataLint.Engine.SnapshotDecodeOutcome0MatchExtensions",
        "StrataLint.Engine.SnapshotDecoder",
        "StrataLint.Engine.StatementId",
        "StrataLint.Engine.Stratum",
        "StrataLint.Engine.TowerBootstrapSyntax",
        "StrataLint.Engine.TowerCheck",
        "StrataLint.Engine.TowerComponentSyntax",
        "StrataLint.Engine.TowerFinding",
        "StrataLint.Engine.TowerManifestParseOutcome",
        "StrataLint.Engine.TowerManifestParseOutcome+Invalid",
        "StrataLint.Engine.TowerManifestParseOutcome+Loaded",
        "StrataLint.Engine.TowerManifestParseOutcome0MatchExtensions",
        "StrataLint.Engine.TowerManifestParser",
        "StrataLint.Engine.TowerManifestSyntax",
        "StrataLint.Engine.TowerManifestValidator",
        "StrataLint.Engine.TowerValidationOutcome",
        "StrataLint.Engine.TowerValidationOutcome+Accepted",
        "StrataLint.Engine.TowerValidationOutcome+Rejected",
        "StrataLint.Engine.TowerValidationOutcome0MatchExtensions",
        "StrataLint.Engine.TrustedRevocationReceiptStore",
        "StrataLint.Engine.TruthState",
        "StrataLint.Engine.ValidatedManifest",
        "StrataLint.Engine.ValidatedPolicy",
        "StrataLint.Engine.ValidatedRevocationEvidence",
        "StrataLint.Engine.ValidatedTowerManifest",
        "StrataLint.Engine.ValidationProfile",
        "StrataLint.Engine.ValidationProfile+LeanModule",
        "StrataLint.Engine.ValidationProfile+OpaqueText",
        "StrataLint.Engine.ValidationProfile+StructuredJson",
        "StrataLint.Engine.ValidationProfile+StructuredYaml",
        "StrataLint.Engine.ValidationProfile0MatchExtensions",
    ];

    [Fact]
    public void EnginePublicTypesMatchTheExplicitAllowlist()
    {
        var actual = typeof(AdmissionPipeline).Assembly.GetExportedTypes()
            .Select(static type => type.FullName
                ?? throw new InvalidOperationException("Exported Engine type has no full name."))
            .Order(StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            ExpectedPublicTypes.SequenceEqual(actual, StringComparer.Ordinal),
            "Engine public surface drifted. Actual sorted allowlist:\n"
            + string.Join("\n", actual));
    }

    [Fact]
    public void UnexpectedPublicTypeIsRejectedByTheRedFixture()
    {
        var actual = ExpectedPublicTypes.Append(typeof(PublicSurfaceLeak).FullName!).ToArray();

        Assert.False(ExpectedPublicTypes.SequenceEqual(actual, StringComparer.Ordinal));
    }

    public sealed class PublicSurfaceLeak;
}
