using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;
namespace StrataLint.Scribe.Blueprint.D5.S3.Quantum.Entanglement;
internal sealed class SymmetricBellPolytopeNotCrossPolytopeDocument : IScribeDocumentDefinition
{
    private static readonly LibraryNoteRef Source = LibraryNoteRef.Create("D5/L/QuantumBounds/designolle2023symmetricbell");
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "At three parties and seventeen inputs, single-frequency strategies remain exposed while a mixed strategy lies outside their convex hull; at least nineteen extreme points exclude a nine-dimensional cross-polytope.", H("The symmetric Bell polytope need not be a cross-polytope"),
        Blocks(
            Describe.Lean(DescribeId.Create("dvp-main-tensor"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.Tensor"),
                H("Correlation tensors"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),Eqn(Call("Tensor" ,F.Id("N"),F.Id("m")),Call("EuclideanSpace" ,RealType(),new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("The real Euclidean tensor carrier has one coordinate for each input tuple. Inputs are numbered from zero."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-normidx"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.normIdx"),
                H("Antiperiodic index reduction"), StatementSource.FromAuthor(Disp(All("m",NatType(),All("v",IntType(),Eqn(Call("normIdx" ,F.Id("m"),F.Id("v")),Parenthesized(Seq(new Formula.Power(Parenthesized(Seq(new Formula.Negate(new Formula.Number(1)),Colon,RealType())),Call("Int.ediv" ,F.Id("v"),Parenthesized(Seq(F.Id("m"),Colon,IntType())))),Comma,Sp,Call("Int.toNat" ,Call("Int.emod" ,F.Id("v"),Parenthesized(Seq(F.Id("m"),Colon,IntType()))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("The antiperiodic rule is e(x+m) = -e(x). Int.ediv is floor division; Int.emod is the nonnegative remainder for positive m. The exponent uses integer powers."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-reduceidx"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.reduceIdx"),
                H("Reduction into the finite input carrier"), StatementSource.FromAuthor(Disp(All("m",NatType(),All("x",Call("Fin" ,F.Id("m")),All("v",IntType(),Eqn(Call("reduceIdx" ,F.Id("x"),F.Id("v")),Parenthesized(Seq(Call("Prod.fst" ,Call("normIdx" ,F.Id("m"),F.Id("v"))),Comma,Sp,Call("Fin.mk" ,Call("Prod.snd" ,Call("normIdx" ,F.Id("m"),F.Id("v")))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("reduceIdx uses normIdx and packages its residue in Fin(m). The bound proof follows from the existence of x : Fin(m); the displayed Fin.mk suppresses only this proof."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-gen1"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.gen1"),
                H("Swap the first two parties"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),All("x",new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))),Eqn(Call("gen1" ,F.Id("x")),Parenthesized(Seq(new Formula.Number(1),Comma,Sp,Lam("n",Call("Fin" ,F.Id("N")),Call("ite" ,Ltq(new Formula.Number(1),F.Id("N")),App(F.Id("x") ,App(Call("Equiv.swap" ,Call("Fin.mk" ,new Formula.Number(0)),Call("Fin.mk" ,new Formula.Number(1))) ,F.Id("n"))),App(F.Id("x") ,F.Id("n")))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("Equation (23): g1 swaps the first two parties. For N <= 1 the total Lean definition is the identity. Fin.mk suppresses the index-bound proofs supplied by 1 < N."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-gen2"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.gen2"),
                H("Cycle the parties"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),All("x",new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))),Eqn(Call("gen2" ,F.Id("x")),Parenthesized(Seq(new Formula.Number(1),Comma,Sp,Lam("n",Call("Fin" ,F.Id("N")),App(F.Id("x") ,Call("Fin.mk" ,Call("Nat.mod" ,Sub(Add(Call("val" ,F.Id("n")),F.Id("N")),new Formula.Number(1)),F.Id("N"))))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("Equation (23): g2 cycles the parties. Subtraction in this index is natural subtraction; the index-bound proof is suppressed."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-shiftparty"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.shiftParty"),
                H("Opposite shifts of the first two inputs"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),All("x",new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))),All("n",Call("Fin" ,F.Id("N")),Eqn(Call("shiftParty" ,F.Id("x"),F.Id("n")),Call("reduceIdx" ,App(F.Id("x") ,F.Id("n")),Add(Parenthesized(Seq(App(F.Id("x") ,F.Id("n")),Colon,IntType())),Call("ite" ,Eqn(Call("val" ,F.Id("n")),new Formula.Number(0)),new Formula.Number(1),Call("ite" ,Eqn(Call("val" ,F.Id("n")),new Formula.Number(1)),new Formula.Negate(new Formula.Number(1)),new Formula.Number(0)))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("Equation (23): g3 shifts party zero by +1 and party one by -1, leaving all other inputs fixed. Reduction applies the antiperiodic sign."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-gen3"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.gen3"),
                H("The opposite-shift generator"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),All("x",new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))),Eqn(Call("gen3" ,F.Id("x")),Parenthesized(Seq(ProdOver("n",Call("Fin" ,F.Id("N")),Call("Prod.fst" ,Call("shiftParty" ,F.Id("x"),F.Id("n")))),Comma,Sp,Lam("n",Call("Fin" ,F.Id("N")),Call("Prod.snd" ,Call("shiftParty" ,F.Id("x"),F.Id("n")))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("Equation (23): the product collects the local antiperiodic signs of the opposite shifts."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-gen4"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.gen4"),
                H("The reflection generator"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),All("x",new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))),Eqn(Call("gen4" ,F.Id("x")),Parenthesized(Seq(ProdOver("n",Call("Fin" ,F.Id("N")),new Formula.Negate(Call("Prod.fst" ,Call("reduceIdx" ,App(F.Id("x") ,F.Id("n")),Sub(Parenthesized(Seq(F.Id("m"),Colon,IntType())),Parenthesized(Seq(App(F.Id("x") ,F.Id("n")),Colon,IntType()))))))),Comma,Sp,Lam("n",Call("Fin" ,F.Id("N")),Call("Prod.snd" ,Call("reduceIdx" ,App(F.Id("x") ,F.Id("n")),Sub(Parenthesized(Seq(F.Id("m"),Colon,IntType())),Parenthesized(Seq(App(F.Id("x") ,F.Id("n")),Colon,IntType())))))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("Equation (23): reflection sends each input to m-x, with one additional minus sign per party, followed by antiperiodic reduction."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-gen"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.gen"),
                H("The four generators"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),All("i",Call("Fin" ,new Formula.Number(4)),All("x",new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))),Eqn(App(Call("gen" ,F.Id("i")) ,F.Id("x")),App(App(Seq(Bang,OpenBracket,Call("gen1"),Comma,Call("gen2"),Comma,Call("gen3"),Comma,Call("gen4"),CloseBracket) ,F.Id("i")) ,F.Id("x"))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("The finite vector is ordered as gen1, gen2, gen3, gen4. All four actions have the same tensor carrier."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-act"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.act"),
                H("Action on tensor coordinates"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),All("g",new Formula.TypeArrow(new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))),Seq(RealType(),Times,Parenthesized(new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m")))))),All("p",Call("Tensor" ,F.Id("N"),F.Id("m")),Eqn(Call("act" ,F.Id("g"),F.Id("p")),Call("WithLp.toLp" ,new Formula.Number(2),Lam("y",new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))),SumOver("x",new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))),Call("ite" ,Eqn(Call("Prod.snd" ,App(F.Id("g") ,F.Id("x"))),F.Id("y")),Mul(Call("Prod.fst" ,App(F.Id("g") ,F.Id("x"))),App(F.Id("p") ,F.Id("x"))),new Formula.Number(0)))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("This is the literal signed basis action, wrapped by WithLp.toLp to obtain the Euclidean tensor carrier."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-symsub"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.symSub"),
                H("The common fixed subspace"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),All("p",Call("Tensor" ,F.Id("N"),F.Id("m")),IffTo(Mem(F.Id("p"),Call("symSub" ,F.Id("N"),F.Id("m"))),All("i",Call("Fin" ,new Formula.Number(4)),Eqn(Call("act" ,Call("gen" ,F.Id("i")),F.Id("p")),F.Id("p"))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("The defining carrier consists of tensors fixed by every generator in Eq. (23). Linearity makes this carrier a real submodule."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-gamma"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.Gamma"),
                H("Orthogonal projection onto symmetric tensors"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),Eqn(Call("Gamma" ,F.Id("N"),F.Id("m")),Call("Submodule.starProjection" ,Call("symSub" ,F.Id("N"),F.Id("m")))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("Equation (27) defines the Reynolds average over the generated group. Gamma uses the permitted orthogonal-projection convention for the same common fixed subspace. Equality with the literal finite-group average is not a separately kernel-checked statement here. Equation (28) gives the signed total-residue coordinates."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-localpolytope"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.localPolytope"),
                H("The full local deterministic polytope"), StatementSource.FromAuthor(Disp(All("N",NatType(),All("m",NatType(),Eqn(Call("localPolytope" ,F.Id("N"),F.Id("m")),Call("convexHull" ,RealType(),SetOf("d",Call("Tensor" ,F.Id("N"),F.Id("m")),ExistsIn("a",new Formula.TypeArrow(Call("Fin" ,F.Id("N")),new Formula.TypeArrow(Call("Fin" ,F.Id("m")),RealType())),And(All("n",Call("Fin" ,F.Id("N")),All("x",Call("Fin" ,F.Id("m")),Or(Eqn(App(F.Id("a") ,F.Id("n"),F.Id("x")),new Formula.Number(1)),Eqn(App(F.Id("a") ,F.Id("n"),F.Id("x")),new Formula.Negate(new Formula.Number(1)))))),All("x",new Formula.TypeArrow(Call("Fin" ,F.Id("N")),Call("Fin" ,F.Id("m"))),Eqn(App(F.Id("d") ,F.Id("x")),ProdOver("n",Call("Fin" ,F.Id("N")),App(F.Id("a") ,F.Id("n"),App(F.Id("x") ,F.Id("n"))))))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("Equations (1)-(2) define d(x1,...,xN) as the product of the local signs and the local polytope as the convex hull of all deterministic strategies. The formula ranges over every real sign strategy, with no frequency restriction."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-crosspolytope"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.crossPolytope"),
                H("The cross-polytope"), StatementSource.FromAuthor(Disp(All("k",NatType(),Eqn(Call("crossPolytope" ,F.Id("k")),Call("convexHull" ,RealType(),Seq(Call("Set.range" ,Lam("i",Call("Fin" ,F.Id("k")),Call("EuclideanSpace.single" ,F.Id("i"),new Formula.Number(1)))),Cup,Call("Set.range" ,Lam("i",Call("Fin" ,F.Id("k")),new Formula.Negate(Call("EuclideanSpace.single" ,F.Id("i"),new Formula.Number(1))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(Paragraph(Text("The cross-polytope is the convex hull of all positive and negative standard unit vectors in real dimension k."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-claim"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.claim"),
                H("The cross-polytope conjecture"), StatementSource.FromAuthor(Disp(IffTo(Call("claim"),All("N",NatType(),All("m",NatType(),Imp(Leq(new Formula.Number(3),F.Id("N")),Imp(Leq(new Formula.Number(2),F.Id("m")),ExistsIn("f",Seq(Call("Tensor" ,F.Id("N"),F.Id("m")),Sp,To,Caret,Grp(F.Id("a")),OpenBracket,RealType(),CloseBracket,Call("EuclideanSpace" ,RealType(),Call("Fin" ,Call("Nat.div" ,Add(F.Id("m"),new Formula.Number(1)),new Formula.Number(2))))),And(Call("Set.InjOn" ,F.Id("f"),Call("Set.image" ,Call("Gamma" ,F.Id("N"),F.Id("m")),Call("localPolytope" ,F.Id("N"),F.Id("m")))),Eqn(Call("Set.image" ,F.Id("f"),Call("Set.image" ,Call("Gamma" ,F.Id("N"),F.Id("m")),Call("localPolytope" ,F.Id("N"),F.Id("m")))),Call("crossPolytope" ,Call("Nat.div" ,Add(F.Id("m"),new Formula.Number(1)),new Formula.Number(2))))))))))))),
                AssessedProvenance.FromLiterature(Source), Blocks(SourceQuotation()), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("dvp-main-result"), DeclarationHandle.Create("D5/S3/Quantum/Entanglement/SymmetricBellPolytopeNotCrossPolytope.result"),
                H("A counterexample with seventeen inputs"), StatementSource.FromAuthor(Disp(new Formula.Not(Parenthesized(Call("claim"))))),
                AssessedProvenance.FromRepo(Source), Blocks(Paragraph(Text("At N = 3 and m = 17 the nine single-frequency strategies and their negatives are uniquely exposed vertices. Writing q_r = 289 (Γ 3 17 d)_[r,0,0], a mixed strategy has scaled projected coordinates (-141,133,-109,69,-13,-43,91,-123,139). In these scaled coordinates the functional (-15,27,-21,8,59,24,-5,-6,10) takes value 8421 there and at most 8417 on the eighteen frequency vertices. A finite convex hull therefore has an additional extreme point. Nineteen extreme points cannot inject into the extreme points of a nine-dimensional cross-polytope. The coordinate scaling by 17 squared preserves this obstruction."))), DescribeRole.Theorem, new OpenProblemResolutionClaim(ProblemSlugRef.Create("designolle-vertesi-pokutta-2023-symmetric-bell-cross-polytope"), ResolutionKind.Refuted))), []));
    private static Formula Parenthesized(Formula x) => Seq(Open, x, Close);
    private static Formula Q(string name) => Seq(Operatorname, Grp(Seq([.. System.Linq.Enumerable.SelectMany(name.Split('.'), (part, i) => i == 0 ? new[] { F.Id(part) } : new[] { Dot, F.Id(part) })])));
    private static Formula Call(string name, params Formula[] args) => args.Length == 0 ? Q(name) : new Formula.Apply(Q(name), [.. args]);
    private static Formula App(Formula f, params Formula[] args) => new Formula.Apply(f, [.. args]);
    private static Formula All(string name, Formula type, Formula body) => new Formula.Bind(FormulaQuantifier.ForAll, FormulaIdentifier.Create(name), type, body);
    private static Formula ExistsIn(string name, Formula type, Formula body) => new Formula.Bind(FormulaQuantifier.Exists, FormulaIdentifier.Create(name), type, body);
    private static Formula Eqn(Formula a, Formula b) => new Formula.Relation(a, FormulaRelationOperator.Equal, b);
    private static Formula Leq(Formula a, Formula b) => new Formula.Relation(a, FormulaRelationOperator.LessThanOrEqual, b);
    private static Formula Ltq(Formula a, Formula b) => new Formula.Relation(a, FormulaRelationOperator.LessThan, b);
    private static Formula Mem(Formula a, Formula b) => new Formula.Relation(a, FormulaRelationOperator.MemberOf, b);
    private static Formula And(Formula a, Formula b) => new Formula.Logic(Parenthesized(a), FormulaLogicOperator.And, Parenthesized(b));
    private static Formula Or(Formula a, Formula b) => new Formula.Logic(Parenthesized(a), FormulaLogicOperator.Or, Parenthesized(b));
    private static Formula Imp(Formula a, Formula b) => new Formula.Logic(Parenthesized(a), FormulaLogicOperator.Implies, b);
    private static Formula IffTo(Formula a, Formula b) => new Formula.Logic(a, FormulaLogicOperator.Iff, Parenthesized(b));
    private static Formula Mul(Formula a, Formula b) => new Formula.Binary(a, FormulaBinaryOperator.Multiply, b);
    private static Formula Add(Formula a, Formula b) => new Formula.Binary(a, FormulaBinaryOperator.Add, b);
    private static Formula Sub(Formula a, Formula b) => new Formula.Binary(a, FormulaBinaryOperator.Subtract, b);
    private static Formula Lam(string name, Formula type, Formula body) => Seq(LambdaLower, Sp, Parenthesized(Seq(F.Id(name), Colon, type)), Sp, Mapsto, Sp, body);
    private static Formula SetOf(string name, Formula type, Formula body) => Seq(OpenBrace, F.Id(name), Colon, type, Mid, body, CloseBrace);
    private static Formula SumOver(string name, Formula type, Formula body) => Seq(new Formula.Subscript(Sum, Seq(F.Id(name), Colon, type)), Sp, body);
    private static Formula ProdOver(string name, Formula type, Formula body) => Seq(new Formula.Subscript(Prod, Seq(F.Id(name), Colon, type)), Sp, body);
    private static Formula NatType() => Seq(Mathbb, Grp(F.Id("N")));
    private static Formula IntType() => Seq(Mathbb, Grp(F.Id("Z")));
    private static Formula RealType() => Seq(Mathbb, Grp(F.Id("R")));
    private static DocumentBlock SourceQuotation() => Paragraph(Text("Section V, p. 4: \"This seems to indicate that the symmetric polytope is affinely equivalent to the cross-polytope in dimension ⌈m/2⌉. Although we considered the orbits giving rise to the extreme points of this polytope and tried to infer a generalisable pattern, we could not establish this fact. We conjecture, however, that it holds in general, and hope that further research will identify these general extreme points.\" The encoding takes N >= 3 and m >= 2, the range of parties in Table II. The dimension uses Nat.div(m+1,2), natural integer division. Affine equivalence is expressed by an affine map injective on the projected polytope and with image the cross-polytope; no ambient-dimensional isomorphism is required."));}
