using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S1.Words.EvilOdious;

internal sealed class SixfoldMonotonicityDocument : IScribeDocumentDefinition
{
    private static readonly LibraryNoteRef Note = LibraryNoteRef.Create("D5/L/Words/allouche2021evilodious");
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Dyadic coefficient recurrences control the sixfold evil and odious representation counts.",
        H("SixfoldMonotonicity"), Blocks(
        Describe.Lean(DescribeId.Create("declaration-initialr-0"), DeclarationHandle.Create("D5/S1/Words/EvilOdious/SixfoldMonotonicity.initialr_0"), H("initialr 0"), StatementSource.FromAuthor(Disp(Seq(Seq(Operatorname, Grp(F.Id("initialChunk"))), Sp, D(1), Sp, D(3,8), Sp, D(0), Sp, D(3,2), Sp, Eq, Sp, Seq(Operatorname, Grp(F.Id("true")))))), AssessedProvenance.FromRepo(Note), Blocks(Paragraph(Text("The formula uses the indicated natural or integer carriers. Natural subtraction is truncated; a slash between natural numbers denotes floor division, Nat.div. Dotted operations and the displayed casts retain their Lean meanings."))), DescribeRole.Theorem),
        Describe.Lean(DescribeId.Create("declaration-initialr-1"), DeclarationHandle.Create("D5/S1/Words/EvilOdious/SixfoldMonotonicity.initialr_1"), H("initialr 1"), StatementSource.FromAuthor(Disp(Seq(Seq(Operatorname, Grp(F.Id("initialChunk"))), Sp, D(1), Sp, D(3,8), Sp, D(3,2), Sp, D(3,2), Sp, Eq, Sp, Seq(Operatorname, Grp(F.Id("true")))))), AssessedProvenance.FromRepo(Note), Blocks(Paragraph(Text("The formula uses the indicated natural or integer carriers. Natural subtraction is truncated; a slash between natural numbers denotes floor division, Nat.div. Dotted operations and the displayed casts retain their Lean meanings."))), DescribeRole.Theorem),
        Describe.Lean(DescribeId.Create("declaration-tail-positive"), DeclarationHandle.Create("D5/S1/Words/EvilOdious/SixfoldMonotonicity.tail_positive"), H("tail positive"), StatementSource.FromAuthor(Disp(Seq(Forall, Sp, Parenthesized(Seq(Seq(Operatorname, Grp(F.Id("sigma"))), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Comma, Sp, Parenthesized(Seq(Seq(Operatorname, Grp(F.Id("sigma"))), Sp, Eq, Sp, D(1), Sp, Lor, Sp, Seq(Operatorname, Grp(F.Id("sigma"))), Sp, Eq, Sp, Minus, Sp, D(1))), Sp, To, Sp, Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Parenthesized(Seq(D(2,0,4,8), Sp, Le, Sp, F.Id("n"))), Sp, To, Sp, D(0), Sp, Lt, Sp, Parenthesized(Seq(Parenthesized(Seq(F.Id("n"), Sp, Plus, Sp, D(4))), Sp, Dot, Sp, Seq(Operatorname, Grp(F.Id("choose"))), Sp, D(4), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("Z"))))), Sp, Plus, Sp, Seq(Operatorname, Grp(F.Id("errorTerm"))), Sp, Seq(Operatorname, Grp(F.Id("sigma"))), Sp, F.Id("n")))), AssessedProvenance.FromRepo(Note), Blocks(Paragraph(Text("The formula uses the indicated natural or integer carriers. Natural subtraction is truncated; a slash between natural numbers denotes floor division, Nat.div. Dotted operations and the displayed casts retain their Lean meanings."))), DescribeRole.Theorem),
        Describe.Lean(DescribeId.Create("declaration-claim"), DeclarationHandle.Create("D5/S1/Words/EvilOdious/SixfoldMonotonicity.claim"), H("claim"), StatementSource.FromAuthor(Disp(Seq(Seq(Operatorname, Grp(F.Id("claim"))), Sp, Iff, Sp, Parenthesized(Seq(Parenthesized(Seq(Parenthesized(Seq(Exists, Sp, Parenthesized(Seq(F.Id("N"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, F.Id("n"), Sp, Ge, Sp, F.Id("N"), Sp, To, Sp, F.Id("r"), Sp, D(6), Sp, F.Id("n"), Sp, Lt, Sp, F.Id("r"), Sp, D(6), Sp, Parenthesized(Seq(F.Id("n"), Sp, Plus, Sp, D(1))))), Sp, Land, Sp, Parenthesized(Seq(Exists, Sp, Parenthesized(Seq(F.Id("N"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, F.Id("n"), Sp, Ge, Sp, F.Id("N"), Sp, To, Sp, F.Id("s"), Sp, D(6), Sp, F.Id("n"), Sp, Lt, Sp, F.Id("s"), Sp, D(6), Sp, Parenthesized(Seq(F.Id("n"), Sp, Plus, Sp, D(1))))))), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, F.Id("n"), Sp, Ge, Sp, D(3,7), Sp, To, Sp, F.Id("r"), Sp, D(6), Sp, F.Id("n"), Sp, Lt, Sp, F.Id("r"), Sp, D(6), Sp, Parenthesized(Seq(F.Id("n"), Sp, Plus, Sp, D(1))))), Sp, Land, Sp, Parenthesized(Seq(Forall, Sp, Parenthesized(Seq(F.Id("n"), Sp, Colon, Sp, Seq(Mathbb, Grp(F.Id("N"))))), Sp, Comma, Sp, F.Id("n"), Sp, Ge, Sp, D(5), Sp, To, Sp, F.Id("s"), Sp, D(6), Sp, F.Id("n"), Sp, Lt, Sp, F.Id("s"), Sp, D(6), Sp, Parenthesized(Seq(F.Id("n"), Sp, Plus, Sp, D(1)))))))))), AssessedProvenance.FromLiterature(Note), Blocks(Paragraph(Text("Conjecture 12, page 10: “(a) Both r₆(n) and s₆(n) are eventually strictly increasing. (a) r₆(n) < r₆(n + 1) for n ≥ 37. (b) s₆(n) < s₆(n + 1) for n ≥ 5.” The duplicated label (a) is printed in the source. Both eventual clauses quantify a natural threshold and all natural n beyond it. Tuple coordinates are ordered, range over the nonnegative integers, and admit repetitions."))), DescribeRole.Definition),
        Describe.Lean(DescribeId.Create("declaration-result"), DeclarationHandle.Create("D5/S1/Words/EvilOdious/SixfoldMonotonicity.result"), H("result"), StatementSource.FromAuthor(Disp(Seq(Seq(Operatorname, Grp(F.Id("claim")))))), AssessedProvenance.FromRepo(Note), Blocks(Paragraph(Text("The formula uses the indicated natural or integer carriers. Natural subtraction is truncated; a slash between natural numbers denotes floor division, Nat.div. Dotted operations and the displayed casts retain their Lean meanings."))), DescribeRole.Theorem))));
    private static Formula Parenthesized(Formula value) => Seq(Open, value, Close);
}
