<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>StrataLint.Scribe</RootNamespace>
    <AssemblyName>StrataLint.Scribe</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../StrataLint.Engine/StrataLint.Engine.csproj" />
    <PackageReference Include="Dunet" />
    <PackageReference Include="QuestPDF" />
  </ItemGroup>
</Project>
