<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>StrataLint.Scribe</RootNamespace>
    <AssemblyName>StrataLint.Scribe</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Blueprint/**/*.scribe.cs" LinkBase="Definitions" />
    <ProjectReference
      Include="../StrataLint.Definitions/StrataLint.Definitions.csproj"
      ReferenceOutputAssembly="false" />
    <Reference Include="StrataLint.Definitions">
      <HintPath>../StrataLint.Definitions/bin/$(Configuration)/$(TargetFramework)/StrataLint.Definitions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <ProjectReference Include="../StrataLint.Engine/StrataLint.Engine.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" PrivateAssets="all" />
    <PackageReference Include="QuestPDF" />
    <AdditionalFiles Include="../Architecture/BannedSymbols.txt" />
  </ItemGroup>
</Project>
