using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Arith.FibonacciAtomic;

internal sealed class AdditiveObstructionDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S3/Arith/FibonacciAtomic/AdditiveObstruction.";

    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Finite additive joint readouts have a complete descent obstruction and exact record cost.",
        H("Additive joint descent obstruction"),
        Blocks(
            Describe.Lean(DescribeId.Create("left-readout"), DeclarationHandle.Create(Prefix + "leftReadout"), H("Left readout"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The homomorphism alpha is applied to the first coordinate of every source element."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("right-readout"), DeclarationHandle.Create(Prefix + "rightReadout"), H("Right readout"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The homomorphism beta is applied to the second coordinate of every source element."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("left-coordinate"), DeclarationHandle.Create(Prefix + "leftCoordinate"), H("First coordinate"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The first-coordinate projection is restricted to the source subgroup."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("right-coordinate"), DeclarationHandle.Create(Prefix + "rightCoordinate"), H("Second coordinate"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The second-coordinate projection is restricted to the source subgroup."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("joint-readout"), DeclarationHandle.Create(Prefix + "jointReadout"), H("Joint readout"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The joint readout pairs the two additive component readouts."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("joint-kernel"), DeclarationHandle.Create(Prefix + "jointKernel"), H("Joint kernel"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The joint kernel consists of source elements whose two readout values vanish."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("left-kernel"), DeclarationHandle.Create(Prefix + "leftKernel"), H("Left single-side kernel"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The left kernel is the joint kernel with zero second coordinate."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("right-kernel"), DeclarationHandle.Create(Prefix + "rightKernel"), H("Right single-side kernel"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The right kernel is the joint kernel with zero first coordinate."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("left-obstruction-kernel"), DeclarationHandle.Create(Prefix + "leftObstructionKernel"), H("Left obstruction subgroup"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The left single-side kernel is viewed as a subgroup of the joint kernel."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("right-obstruction-kernel"), DeclarationHandle.Create(Prefix + "rightObstructionKernel"), H("Right obstruction subgroup"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The right single-side kernel is viewed as a subgroup of the joint kernel."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("obstruction"), DeclarationHandle.Create(Prefix + "obstruction"), H("Descent obstruction"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The obstruction is the additive quotient of the joint kernel by the sum of the two single-side kernels."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("vanishes-on"), DeclarationHandle.Create(Prefix + "vanishesOn"), H("Vanishing on a subgroup"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A homomorphism vanishes on a subgroup when every element of that subgroup is sent to zero."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("left-sufficient"), DeclarationHandle.Create(Prefix + "leftSufficient"), H("Left single-side sufficiency"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The task is unchanged whenever the second source coordinate and the left readout agree."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("right-sufficient"), DeclarationHandle.Create(Prefix + "rightSufficient"), H("Right single-side sufficiency"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The task is unchanged whenever the first source coordinate and the right readout agree."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("jointly-sufficient"), DeclarationHandle.Create(Prefix + "jointlySufficient"), H("Joint sufficiency"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The task is constant on every fibre of the joint readout."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("restricted-task"), DeclarationHandle.Create(Prefix + "restrictedTask"), H("Restricted task"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The task restricted to the joint kernel is an additive homomorphism into the target."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("descended-task"), DeclarationHandle.Create(Prefix + "descendedTask"), H("Descended task"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("When both single-side kernels are killed, the restricted task descends to the obstruction quotient."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("record-capacity"), DeclarationHandle.Create(Prefix + "recordCapacity"), H("Record capacity"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The record capacity is the cardinality of the image of the descended task."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("record-separates"), DeclarationHandle.Create(Prefix + "recordSeparates"), H("Separating record"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("A record on the joint kernel separates restricted task values when equal records force equal task values."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("minimal-record-cardinality"), DeclarationHandle.Create(Prefix + "minimal_record_cardinality"), H("Minimal record alphabet"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Every finite record alphabet that separates restricted task values has cardinality at least the task image, and the restricted task itself supplies a separating record with exactly that image cardinality."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("additive-obstruction-complete"), DeclarationHandle.Create(Prefix + "additive_obstruction_complete"), H("Complete additive obstruction theorem"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Each single-side sufficiency condition is equivalent to vanishing on its kernel. Under both conditions, joint sufficiency is equivalent to the descended task being zero, and the descended image has the same cardinality as the restricted task image."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("obstruction-nontrivial-failed-task"), DeclarationHandle.Create(Prefix + "obstruction_nontrivial_has_feasible_failed_task"), H("Nontrivial obstruction witness"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("When the obstruction quotient is nontrivial, the quotient map from the source by the sum of the two single-side kernels is single-side sufficient but fails joint sufficiency."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("obstruction-zero-all-tasks"), DeclarationHandle.Create(Prefix + "obstruction_zero_iff_all_tasks_jointly_descend"), H("Zero obstruction criterion"), StatementSource.WithoutFormula(), AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The obstruction quotient is subsingleton exactly when every additive task with both single-side sufficiency conditions is jointly sufficient."))), DescribeRole.Theorem)),
        []));
}
