using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.FiniteGroups.NikolovSegal.TypeA.Unitriangular;

internal sealed class PartIIUnitriangularGraphOddSupplyDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Type-A Unitriangular Graph Odd Supply.",
        H("Type-A Unitriangular Graph Odd Supply"),
        Blocks(
            Describe.Lean(
                DescribeId.Create("typea-partiiunitriangulargraphoddsupply-actual-uniform-field-graph-odd-layer-product"),
                DeclarationHandle.Create("D5/S3/FiniteGroups/NikolovSegal/TypeA/Unitriangular/PartIIUnitriangularGraphOddSupply.actual_uniform_field_graph_odd_layer_product"),
                H("actual uniform field graph odd layer product"), StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Actual norm witness for prescribed q-divisor powers. Its leading commutator is the doubled-power value. This is an equality in the genuine layer, never an asserted nonabelian inclusion of single commutator sets. -/ private theorem norm_value (lambda : Fˣ) (phi : RingAut F) (eps : Bool) (d k : ℕ) (hk : 0<k) (hodd : k%2=1) (a : Matrix.SpecialLinearGroup (Fin n) F) (ha : LayerDepth k (a.val-1)) : let beta : MulAut (Matrix.SpecialLinearGroup (Fin n) F) := (mirrorTorus lambda*fieldGraphAut phi eps)^d let x := a*beta a LayerDepth k (x.val-1) ∧ LayerDepth k ((x⁻¹*beta x).val-1) ∧ ∀ i : Fin (n-k), (unitOdd% coordinate) k (x⁻¹*beta x) i= fieldValue phi 1 (2*d) 1 (if positiveRoot k i then (lambda:F) else ((lambda⁻¹:Fˣ):F)) ((unitOdd% coordinate) k a i) := by classical dsimp only let beta : MulAut (Matrix.SpecialLinearGroup (Fin n) F) := (mirrorTorus lambda*fieldGraphAut phi eps)^d let x := a*beta a have hb : LayerDepth k ((beta a).val-1) := (unitGraph% mirror_graph_depth) lambda phi eps k hk a ha d have hx : LayerDepth k (x.val-1) := (unitRec% product_depth) k hk a (beta a) ha hb have hbx : LayerDepth k ((beta x).val-1) := (unitGraph% mirror_graph_depth) lambda phi eps k hk x hx d refine ⟨hx,(unitRec% product_depth) k hk _ _ ((unitOdd% inverse_depth) k hk x hx) hbx,?_⟩ intro i have hbb := actual_mirror_field_graph_doubled_power lambda phi eps k hk hodd a ha d have he : beta (beta a)=((mirrorTorus lambda*fieldGraphAut phi eps : MulAut (Matrix.SpecialLinearGroup (Fin n) F))^(2*d)) a := by simp only [beta,← MulAut.mul_apply,← pow_add,show d+d=2*d by omega] rw [(unitOdd% product_coordinate) k hk x⁻¹ (beta x) ((unitOdd% inverse_depth) k hk x hx) hbx, (unitOdd% inverse_coordinate) k hk x hx] change -(unitOdd% coordinate) k (a*beta a) i+(unitOdd% coordinate) k (beta (a*beta a)) i=_ rw [map_mul,(unitOdd% product_coordinate) k hk a (beta a) ha hb, (unitOdd% product_coordinate) k hk (beta a) (beta (beta a)) hb ((unitGraph% mirror_graph_depth) lambda phi eps k hk (beta a) hb d),he,hbb.2 i, root_sign lambda k hk hodd i] simp only [fieldValue,one_mul,pow_one] by_cases hp : positiveRoot k i · simp only [if_pos hp]; ring · simp only [if_neg hp,Units.val_inv_eq_inv_val]; ring /-- Printed PartII Lemma9.2 odd-layer product for arbitrary prescribed field/positive-graph tuples. The proved scalar theorem is consumed at exponents 2*d dividing 2*q. One torus tuple is fixed before all odd heights and targets. Witnesses retain their actual norm-of-strip shape, including unused root coordinates. The endpoint uses the prescribed dth-power commutator valueS, not substituted doubled-power values."))),
                DescribeRole.Theorem),
            Paragraph(Text("Nikolov and Segal, On finitely generated profinite groups, I: Strong completeness and uniform bounds, Annals of Mathematics165 (2007),171-238, DOI10.4007/annals.2007.165.171, Section10, Proposition10.2 and equations(45)-(50). PartII: Products in quasisimple groups, Annals of Mathematics165 (2007),239-273, DOI10.4007/annals.2007.165.239, Theorem1.2, Lemma4.1, Sections2,5,6 and9, Proposition6.2, Propositions6.5 and6.7, and equation(13). The type-A arguments use explicit matrix and central-quotient geometry, finite-field arithmetic, Sylow conjugacy and constructive ordered class products. They establish the untwisted projective type-A family above uniform group-cardinality cutoffs. They do not establish exhaustion of all finite simple groups, general central covers, general width/RBP or strong completeness. The explicit fixed-power class and supported-factor width proofs replace the cited Section5 [SW]/[LS2] inputs in this type-A application. No originality claim or redistribution of the papers is made.")))));
}
