<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    <RootNamespace>StrataLint.RepositoryConfiguration.Tests</RootNamespace>
    <AssemblyName>StrataLint.RepositoryConfiguration.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../TestSupport/StrataLint.ConfigurationTestSupport/StrataLint.ConfigurationTestSupport.csproj" />
    <ProjectReference Include="../../StrataLint.Configuration/StrataLint.Configuration.csproj" />
    <ProjectReference Include="../../StrataLint.Engine/StrataLint.Engine.csproj" />
    <ProjectReference Include="../../TestSupport/StrataLint.TestSupport/StrataLint.TestSupport.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
